<?php require_login(); ?>
<h1>Aegia Aeterna - Heliadora </h1>
<section id="heliadora">
  <h2>Heliadora - <em>"Gift of the Sun"</em></h2>
  
  <!-- Image Map Generated by http://www.image-map.net/ -->
<img src="images/harmontide-aa.webp" alt="World map" usemap="#worldmap" class="world-map" />
  <map name="image-map">
    <area target="" alt="ruins" title="ruins" href="aa-adventure" coords="1127,12,1496,205" shape="rect">
    <area target="" alt="pizzaria" title="pizzaria" href="aa-pizza" coords="858,495,1320,883" shape="rect">
   </map>

  
  <div class="card glass">
    <h3>Explore the abandoned ruins of Heliadora</h3>
    <p class="muted">Try to find your way around the old ruins of this ancient capital.</p>
    <a class="btn" href="?pg=aa-adventure">Begin</a>
  </div>

  <div class="card glass">
    <h3>Pizzeria Sol Invicta</h3>
    <p class="muted">Brick-fired pies, sun-braised olives, and red sauce argued over by civic poets.</p>
    <a class="btn" href="?pg=aa-pizza">Enter</a>
  </div>

  <p><strong>Heliadora</strong> is the antique capital of democracy in Aegia Aeterna-marble forums, vow-stones that hum under your palm, 
  and boulevards laid to a ruler's line. The old stories say the city was founded where a sunbeam struck the sea and turned to stone; 
  the people have kept those stones <em>meticulously</em> ever since. Mistreat a monument and you'll learn how quickly a smile becomes a 
  summons-<strong>fines in the millions</strong> (denars, usually) are not a myth.</p>

  <p>The city's spirit is a braid of <strong>Aegian civic pride</strong> and a lively <strong>diaspora return</strong>: Aegians who grew 
  up across the ocean brought back street music, quick talk, and a fierce love of red sauce. You'll hear orators rehearsing in the 
  <em>Forum Aeternum</em> at dawn, then stumble past a lamplit trattoria where a Nonna argues with a poet about olive oil like it's law.</p>

  <hr>

  <h3>Districts & Landmarks</h3>
  <ul>
    <li><strong>Forum Aeternum</strong> - The marble heart of Heliadora. Citizens debate beneath bronze laurels; the <em>Speaker's Circle</em> 
    amplifies truth and shrinks boastfulness.</li>
    <li><strong>Curia Solaris</strong> - Senate Hill. Murals of the <em>Dii Aeterni</em> (everyday folk call them the <em>Capitolympians</em>) 
    watch over deliberations. 
    Oaths here are sworn on <strong>vow-stones</strong>; break one and the stone will hairline crack for all to see.</li>
    <li><strong>Aegis Causeways</strong> - Ancient bridges seeded with justice runes. If public hubris spikes during a festival, 
    the causeways ring like shields until the crowd cools.</li>
    <li><strong>Baths of Alba</strong> - White-stone baths that hold the city's whispered deals and civic gossip in equal measure. 
    Mind your volume; even tiles have memories here.</li>
    <li><strong>Sunmarket</strong> - Arcades of citrus, olives, parchment, and street theater. Watch for pickpockets with immaculate manners-they'll 
    apologize as they hand your purse back (after a lecture on situational awareness).</li>
  </ul>

  <hr>

  <h3>Food</h3>
  <p><strong>Pizza is a civic virtue.</strong> The export and the return shaped each other; Aegians abroad invented new styles, and Heliadora 
  welcomed them home like prodigal slices. Swing by <strong>Capitolo</strong>-touristy, yes, and priced like a senatorial toga, but the 
  <em>Nonna Slice</em> with sun-basil and charred crust may convert you. If you're hunting less famous perfection, ask a courier for "a lunch 
  for the marble men" and you'll be pointed to a back-alley pie with ash-salt that tastes like victory.</p>

  <p>Other musts: <em>garum-chili oil</em> (don't ask, just drizzle), <em>lemon-ricotta sfoglia</em> after dusk, and a paper cone of fried 
  anchovies sold on the Aegis steps-sacrilege to some, sacrament to others.</p>

  <hr>

  <h3>Order & Underworld</h3>
  <p>Heliadora loves laws almost as much as it loves loopholes. The city watch-<strong>the Marble Ward</strong>-keeps the forums civil, but 
  rumors persist of "<strong>Capitoline Families</strong>," oath-tight crews that grew from old guilds into velvet-gloved protection rackets. 
  They call their quiet code the <em>Silent Concord</em>, and they <em>do not</em> appreciate outsiders using the word "mafia."</p>

  <p>Still, the sun sees everything. The Ward's <strong>Vigil of Vows</strong> has been unpicking those shadow ledgers for years, seizing ghost 
  accounts and shunting the recovered coin into public fountains, schools, and monument care. In Heliadora, even the underworld gets a civic audit.</p>

  <hr>

  <h3>Etiquette & Practicalities</h3>
  <ul>
    <li><strong>At vow-stones:</strong> palm, breath, <em>then</em> speak. Boasts are considered litter.</li>
    <li><strong>On the steps:</strong> never sit on roped stairs; those are reserved for witnesses and elders.</li>
    <li><strong>Festival nights:</strong> the Aegis Causeways chime at "pride peak." When they do, cheer softly or the Ward will "invite" you to help 
    scrub mosaics at sunrise.</li>
    <li><strong>Prices:</strong> tourist strips run 5-10x normal. Ask for a <em>civic cut</em>-some vendors honor it if you can name the current 
    Speaker.</li>
  </ul>

  <hr>

  <h3>Calendar & Belief</h3>
  <p>The city keeps the <strong>Procession of the Aegis</strong> every solstice-candles drift along canals while choruses sing humility verses older 
  than the marble. Temples of the <em>Dii Aeterni</em> share courtyards with schools and courts; in Heliadora, <strong>piety, pedagogy, and policy
  </strong> share a wall.</p>

  <hr>

  <h3>Traveler's Note</h3>
  <p>Heliadora is a city that wants you to <em>stand up straight and say something worth the echo</em>. Do that, treat the stone kindly, and the sun 
  will lend you its good side. And if you must overpay for a slice at <strong>Capitolo</strong>? Call it a tax on nostalgia-and tip like you mean 
  it.</p>
</section>