<?php require_login(); ?>
<h1>Auronia Map</h1>
<div id="container map-container">
    <img src="images/harmontide-auronia.png" alt="World map" usemap="#worldmap" class="world-map" />
    <!-- Image Map Generated by http://www.image-map.net/ -->
    <map name="worldmap">
        <area target="" alt="Aegia Aeterna" title="Aegia Aeterna" href="index.php?pg=aegia_aeterna" coords="625,1268,566,1555,319,1662,74,1597,23,1270,42,1234,71,1224,65,1202,86,1194,97,1152,134,1140,163,1162,224,1177,260,1175,278,1184,309,1158,333,1150,509,1187,541,1204,557,1228,590,1265" shape="poly">
        <area target="" alt="Rheinland" title="Rheinland" href="index.php?pg=rheinland" coords="154,764,112,793,62,799,5,851,16,1230,57,1220,66,1199,80,1190,99,1144,131,1134,163,1154,213,1169,272,1172,315,1148,344,1146,560,1208,590,1253,645,1262,764,1114,798,1104,855,1156,933,1142,971,1063,931,1004,849,931,618,943,505,904,470,916,450,882,384,850,354,817,324,829" shape="poly">
        <area target="" alt="Bretonreach" title="Bretonreach" href="index.php?pg=bretonreach" coords="5,830,58,793,116,780,136,766,165,760,189,768,317,816,357,810,395,842,428,852,445,872,473,905,500,893,624,930,755,781,903,751,915,636,891,565,875,541,768,479,698,431,700,392,681,386,657,391,637,395,602,350,576,334,56,532" shape="poly">
        <area target="" alt="Nornheim" title="Nornheim" href="index.php?pg=nornheim" coords="965,602,903,586,885,538,780,478,705,422,704,385,642,389,609,347,543,306,500,23,749,14,999,16,1075,34,1095,230,1045,482" shape="poly">
    </map>
</main>