<?php
require_login();
require_once __DIR__.'/../lib/shops.php';
?>
<h1>Baharamandal - Padmanagara</h1>
<section id="padmanagara">
  <h2>Padmanagara - <em>"City of the Lotus"</em></h2>
  
  <!-- Image Map Generated by http://www.image-map.net/ -->
<img src="images/harmontide-padmanagara.webp" alt="World map" usemap="#worldmap" class="world-map" />
  <map name="image-map">
   </map>
  
  <div class="card glass">
    <h3>Paint Shack</h3>
    <p class="muted">Here you can paint your creatures from this region.</p>
    <a class="btn" href="?pg=bm_paint_shack">Explore</a>
  </div>
  
  <div class="card glass">
    <h3>Picnic Tree</h3>
    <p class="muted">Grab some random goodies.</p>
    <a class="btn" href="?pg=bm_pt">Explore</a>
  </div>

  <div class="card glass">
    <h3>Back to Dawnmarch</h3>
    <a class="btn" href="?pg=dawnmarch">Back</a>
  </div>

  <p><strong>Padmanagara</strong> sits on a braid of holy rivers, its ghats stepping down like open palms to the water. Bells carry on the morning mist; saffron flags tilt above carved gateways; and everywhere the scent of cardamom, sandal, and river silt. The city keeps its stones polished not from nostalgia alone but from duty: in Baharamandal, beauty is a public trust. Scratch a pillar, and a priest-accountant may hand you a broom faster than a fine.</p>

  <p>Its spirit is a weave of <strong>temple scholarship</strong>, <strong>bazaar craft</strong>, and a warm diaspora return. Students argue dharma under neem trees while spice merchants count with quick fingers; pilgrims trade songs for sweet tea; and returning families bring back street snacks and cinema posters that the old quarter promptly blesses with marigolds.</p>

  <hr>

  <h3>Districts &amp; Landmarks</h3>
  <ul>
    <li><strong>Lotus Ghats</strong> - Terraced steps where lamps float at dusk. The water courts sit above the 3rd landing; disputes are heard after a shared sip from the same brass cup.</li>
    <li><strong>Mandala Chowk</strong> - The bazaar-heart. Garlands, pigments, brasswork, silk, and street theater. The ground is chalked with designs that ask feet to walk kindly.</li>
    <li><strong>Devalok Gate</strong> - The temple quarter. Shrines stand shoulder to shoulder with schools and kitchens. Oaths spoken here are sealed with a pinch of ash on the wrist.</li>
    <li><strong>River Colleges</strong> - Red-stone cloisters where monks and mathematicians share a board. Sand tables map the floodplain; prayer wheels share space with abacuses.</li>
    <li><strong>Peacock Arcade</strong> - A colonnade of artisans: miniature painters, veena makers, perfumers. The roof feathers are tile; when the monsoon drums, it sounds like a dance.</li>
    <li><strong>Sunshade Garden</strong> - Banyan, neem, lotus ponds. Public shade is a civic right; readers and chess players keep quiet score while parakeets argue.</li>
  </ul>

  <hr>

  <h3>Food &amp; the Diaspora Touch</h3>
  <p><strong>Eat with your eyes first.</strong> Padmanagara plates are color and comfort: banana-leaf thalis with lentils, pickles, rice, and flatbreads that puff like proud cheeks. Street sides fry masala fritters and green-chili pakoras; clay cups pour cardamom chai. The diaspora brought back new cravings, and the city obliged. Try <strong>Lotus Lassi</strong> with rose and pistachio, or the <strong>Returnee Roll</strong>: spiced paneer wrapped in a flaky bread and seared on a steel drum.</p>

  <p>For a famous bite, queue at <strong>Mandala Meals</strong> where the line moves like a prayer. For less fanfare and more soul, ask a bookseller for a "student plate" and you will be sent to a lane canteen that serves rice, dal, ghee, and a chutney that tastes like a monsoon afternoon. Prices near the ghats can multiply by 5 to 10. Smile, ask for the "local measure," and name the day of the temple calendar; the vendor will probably knock the number down.</p>

  <hr>

  <h3>Order &amp; Underlane</h3>
  <p>Padmanagara prides itself on soft authority. The <strong>Lamp Ward</strong> keeps watch with ledgers and lanterns; patrols end by relighting a shrine, not by slamming doors. Still, there are whispers about the <strong>Silk Houses</strong>: old merchant families who maintain quiet monopolies on certain lanes, charging a "thread fee" to keep the peace. They insist they are guardians of tradition, not rackets. The Lamp Ward shrugs and audits their charity lines every season. In this city, even shadow accounts must show a receipt for donated rice.</p>

  <hr>

  <h3>Etiquette &amp; Practicalities</h3>
  <ul>
    <li><strong>At ghats:</strong> shoes off at the last step; no photos during lamp rituals unless invited. Do not touch a floating lamp; bless it with a bow instead.</li>
    <li><strong>At shrines:</strong> right hand for offerings; left hand stays quiet. Ring the bell once, not as a drum.</li>
    <li><strong>Haggling:</strong> begin with a greeting and a compliment; bargains made with honey last longer than those made with thunder.</li>
    <li><strong>Lines:</strong> there are visible queues and invisible ones. Ask "who is last" and inherit the place gracefully.</li>
    <li><strong>Heat:</strong> drink water, not pride. Vendors will offer clay-cup water as courtesy; refuse only if you must, and then with thanks.</li>
  </ul>

  <hr>

  <h3>Calendar &amp; Belief</h3>
  <p>The city keeps the <strong>Festival of Lamps</strong> at river-drop: thousands of flames ride the current while verses of the Devalok Path are sung from the steps. The <strong>Kite Monsoon</strong> paints the sky in midyear, strings humming like sitars across roofs. On the night of <strong>Quiet Lamps</strong>, markets dim their lanterns together for one minute so promises can be heard. Temples, schools, and courts share walls; in Padmanagara the triad is simple: <strong>study, serve, celebrate</strong>.</p>

  <hr>

  <h3>Traveler's Note</h3>
  <p>Padmanagara asks for unhurried steps and bright eyes. Touch stone with respect, taste what is offered, and count your change with a grin rather than a glare. If the bazaar tempts your purse thin, call it a donation to the gods of appetite and art. The rivers remember generosity longer than any receipt.</p>
</section>