<?php require_login(); ?>
<h1>Borealia</h1>
<img src="images/harmontide-borealia.png" alt="World map" usemap="#worldmap" class="world-map" />
<!-- Image Map Generated by http://www.image-map.net/ -->
<map name="worldmap">
</map>
  
  <div class="card glass">
    <h3>United free Republic of Borealia (URB)</h3>
    <p class="muted">A post industrial bundle of states, that manifested destiny.</p>
    <a class="btn" href="?pg=urb">Explore</a>
  </div>
  
  <div class="card glass">
    <h3>Sovereign Tribes of the Ancestral Plains (STAP)</h3>
    <p class="muted">Plains, wigwams and a whole lot of nature</p>
    <a class="btn" href="?pg=stap">Explore</a>
  </div>
  
  <div class="card glass">
    <h3>Back to world map</h3>
    <a class="btn" href="?pg=map">Explore</a>
  </div>