<?php require_login(); ?>
<h1>Bretonreach - Avalore</h1>
<section id="avalore">
  <h2>Avalore - <em>"Crown of the Mists"</em></h2>
  
  <!-- Image Map Generated by http://www.image-map.net/ -->
<img src="images/harmontide-avalore.webp" alt="World map" usemap="#worldmap" class="world-map" />
  <map name="image-map">
   </map>

  <p><strong>Avalore</strong> rises from green hills and river fog, a ring-walled capital where guest-right is law and songs count as currency. Half-timber lanes lean over cobbles, ivy climbs watchtowers, and way-bakers set out warm loaves before dawn so travelers leave the gates with crumbs and gratitude. In Bretonreach, hospitality is not a nicety. It is how the roads stay safe when the mists grow curious.</p>

  <p>The city lives at the seam of <strong>Celtic and old English lore</strong>: courts of oak and rowan, ballads that bargain with the weather, hearths that keep room for strangers and for the not-quite-mortal. The elders say Avalore was founded where a silver branch chimed over a spring. True or not, bells still hang at doorframes and ring when a lie tries to enter.</p>

  <hr>

  <h3>Districts and Landmarks</h3>
  <ul>
    <li><strong>Green Crown</strong> - The hill-fort heart. Moot oak at the center, council benches circling out. Petitioners tie ribbon-pledges to the rail; the beadle snips them loose at dusk when promises are kept.</li>
    <li><strong>Rowan Gate</strong> - Eastern gate strung with red berries and iron nails. Market stalls spill under faded pennants. If a hawker will not name a price, they want a story, not coin.</li>
    <li><strong>Bridge of Three Larks</strong> - A triple-arched span over the River Kindly. Lark carvings face upstream, downstream, and skyward. Lovers carve initials on the underside where the river keeps secrets.</li>
    <li><strong>Lantern Close</strong> - Lamplit alley of inns and music houses. Fiddles, pipes, and hand drums until curfew. The inn called <em>The Silver Branch</em> is said to pour ale that cannot sour even in bad years.</li>
    <li><strong>Willow Court</strong> - A crescent green with three living willows trained into an open-air hall. Here the <em>Courts of Courtesy</em> hear disputes with tea and shortbread before fines.</li>
    <li><strong>Warden Walk</strong> - Patrol path along the inner wall. Chalk sigils mark true north, and brass mirrors hang to catch glamours trying to cross as shadows.</li>
  </ul>

  <hr>

  <h3>Food and Drink</h3>
  <p><strong>Eat like a guest, not a raider.</strong> Avalore feeds the road: root pies with cheddar lids, leek and nettle soup, oat bannocks, and river trout with lemon and thyme. Street trays carry honeyed apples in autumn and cream scones year-round. Try <strong>Mistbrew</strong>, a pale ale cut with heather, or the <strong>Green Crown Stew</strong> that arrives with a warning about wishing out loud while you eat it.</p>

  <p>Tourist tip: Lantern Close can run 5 to 10 times dearer than lanes one street back. Ask for the "traveler plate" and name the day of the last Bellfast (city bell maintenance day) to earn a smile and a fairer price.</p>

  <hr>

  <h3>Order and Underlane</h3>
  <p>The <strong>Road Wardens</strong> wear blue cloaks and carry ash staves banded with iron. They settle quarrels with courtesy first and kettles second. Beneath the civility, Avalore remembers that mists have teeth. There is whisper of the <strong>Gentle Folk</strong> who prefer gifts to taxes, guiding certain high-value wagons through fog for a fee of bread, salt, and silence. The Wardens pretend not to hear, while the <em>Courts of Courtesy</em> post bounties for those who steal without leaving thanks.</p>

  <hr>

  <h3>Etiquette and Practicalities</h3>
  <ul>
    <li><strong>At doors:</strong> knock twice, then once. Bells at lintels decide if you are welcome. If the bell does not ring, try again with a softer breath.</li>
    <li><strong>Guest-right:</strong> accept bread and salt before bargaining. If you decline, you have declared a duel of prices.</li>
    <li><strong>Stories:</strong> some stalls take tales as tender. Keep one clean and one spooky. Do not trade a true name for pudding.</li>
    <li><strong>Mist manners:</strong> never call a stranger "friend" until sunrise. Offer your name but not your shadow. Iron in your pocket keeps the road honest.</li>
    <li><strong>Curfew:</strong> when the Watch-horn sounds, the lanterns of Lantern Close dim. After-curfew singing must be whispered or be very, very good.</li>
  </ul>

  <hr>

  <h3>Calendar and Belief</h3>
  <p>Avalore keeps <strong>Breadfirst</strong> at harvest, a procession where loaves baked with carved faces ride to the Green Crown and are broken among strangers. Spring belongs to <strong>Rowanrise</strong>, when red ribbons move from winter charms to marriage poles. On fog-thick nights the city lights <strong>Kindly Lamps</strong> along the river, and children float paper boats with good-luck lines written inside.</p>

  <hr>

  <h3>Traveler's Note</h3>
  <p>Avalore will make room for you if you make room for others. Share a bench. Leave a coin on a windowsill when the fiddler plays your name out of the air. If a fox salutes you at dawn, salute back and say nothing else. And if the price of a scone seems wicked, remember: some of what you pay goes to keep the mists telling nicer stories about strangers.</p>
</section>
