<?php require_login(); ?>
<h1>Crescent Caliphate</h1>
<p>Ansurah.</p>
<img src="images/harmontide-cc.png" alt="World map" usemap="#worldmap" class="world-map" />
<!-- Image Map Generated by http://www.image-map.net/ -->
<map name="worldmap">
</map>
  
  <div class="card glass">
    <h3>Back to world map</h3>
    <a class="btn" href="?pg=map">Explore</a>
  </div>