<?php require_login(); ?>
<h1>Dawnmarch</h1>
<img src="images/harmontide-dawnmarch.png" alt="World map" usemap="#worldmap" class="world-map" />
<!-- Image Map Generated by http://www.image-map.net/ -->
<map name="worldmap">
</map>
  
  <div class="card glass">
    <h3>Lotus-Dragon Kingdom</h3>
    <p class="muted">Quit, don't quit. Noodles.</p>
    <a class="btn" href="?pg=ldk">Explore</a>
  </div>
  
  <div class="card glass">
    <h3>Baharamandal</h3>
    <p class="muted">Yoga bros are gonna make you believe that this is not a shit sty</p>
    <a class="btn" href="?pg=baharamandal">Explore</a>
  </div>
  
  <div class="card glass">
    <h3>Yamanokubo</h3>
    <p class="muted">The land of honor and responsibility.</p>
    <a class="btn" href="?pg=yamanokubo">Explore</a>
  </div>
  
  <div class="card glass">
    <h3>Back to world map</h3>
    <a class="btn" href="?pg=map">Explore</a>
  </div>