<?php require_login(); ?>
<h1>Eagle Serpent Dominion</h1>
<img src="images/harmontide-esd.webp" alt="World map" usemap="#worldmap" class="world-map" />
<!-- Image Map Generated by http://www.image-map.net/ -->
<map name="worldmap">
</map>
  
  <div class="card glass">
    <h3>Paint Shack</h3>
    <p class="muted">Here you can paint your creatures from this region.</p>
    <a class="btn" href="?pg=esd_paint_shack">Explore</a>
  </div>
  
  <div class="card glass">
    <h3>Back to Gulfbelt</h3>
    <a class="btn" href="?pg=gulfbelt">Explore</a>
  </div>

  <section id="coatlxochi">
  <h2>Coatlxochi - <em>"Flower of the Eagle and Serpent"</em></h2>

  <p><strong>Coatlxochi</strong> rises from a wide lake on stone islands linked by long causeways. White walls catch the sun; painted serpent rails coil along bridges; eagle standards tilt over plazas bright with banners and flower garlands. Gardens float on reed beds at the edges of the water, and canals stitch the city together like turquoise thread. In the Eagle Serpent Dominion, power is balance: sky and earth, blade and blossom, decree and gift.</p>

  <p>The capital is a planner's dream and a pilgrim's maze. Council houses face stepped temples; ballcourts echo with rubber thunder; market squares bloom at dawn with maize, cacao, bright feathers, copper bells, obsidian blades, and woven cloth that holds whole stories. Priests pace shaded porticoes burning copal; scribes score tribute tallies on bark-paper; and canal boats carry both news and melons. Visitors learn fast: follow the banners, keep right on the causeways, and do not block the couriers in red paint.</p>

  <hr>

  <h3>Districts and Landmarks</h3>
  <ul>
    <li><strong>Sun Crown Precinct</strong> - The central plaza with twin stepped temples. Political proclamations are read from the northern stair at midday; flower offerings and incense climb the southern stair at dusk.</li>
    <li><strong>Market of Feathers</strong> - The grand market. Guild lanes for jade, featherwork, textiles, pottery, and tools. Inspectors weigh measures and test obsidian edges with a practiced thumb.</li>
    <li><strong>Causeway Gates</strong> - Three great roads over water with gatehouses that lift wooden spans at night. Toll is light for traders, lighter for couriers, and paid in coin or maize cakes.</li>
    <li><strong>Canal Quarter</strong> - Neighborhoods of bridges and boat docks. Painters stripe door lintels with family colors; herons hunt from roof corners at dawn.</li>
    <li><strong>Ballcourt of Two Skies</strong> - A long sunken court where teams play under eagle and serpent carvings. Festival finals draw banners from every district.</li>
    <li><strong>House of Reed and Stone</strong> - Council compound and scribal schools. Bark-paper books dry on racks; stone slabs hold tribute lists cut so clean they look like water.</li>
    <li><strong>Chinampa Gardens</strong> - Floating fields anchored by willow stakes. Maize, beans, squash, flowers for the precinct altars, and a thousand dragonflies keeping summer honest.</li>
  </ul>

  <hr>

  <h3>Food and Drink</h3>
  <p><strong>Eat the lake and the garden.</strong> Steamed tamales, maize griddle cakes, lake fish with green herbs, squash blossom stews, black beans bright with chile and lime. Street sellers pour <strong>atole</strong> hot and sweet, or hand you a gourd of spiced <strong>cacao</strong> that hums like a drumline. Try the <strong>Eagle Skewer</strong> (pepper and herb chicken) or the <strong>Serpent Green</strong> (tomatillo and pumpkin seed sauce) at the Causeway Gates.</p>

  <p>Tourist note: stalls facing the Sun Crown Precinct charge 5 to 10 times the lane rate. Ask for the "garden measure" and mention which chinampa you visited; most vendors will nod and drop the price to something a canal boatman would pay.</p>

  <hr>

  <h3>Order and Underlane</h3>
  <p>Peace is kept by the <strong>Eagle Guard</strong> on the plazas and the <strong>Serpent Ward</strong> on the canals. Fines turn into labor on causeways, gardens, and fountains; pride turns into a lecture from a grandmother who outranks any captain. Yet Coatlxochi keeps shadows under its bridges. People whisper about the <strong>Night Jaguars</strong>, merchant-brotherhood guides who move tribute and rare goods after curfew for a fee of shells and silence. They call it courtesy and flow, not a racket. The Ward audits their "charity baskets" at the Market of Feathers each moon; in this city even a shadow must show a receipt.</p>

  <hr>

  <h3>Etiquette and Practicalities</h3>
  <ul>
    <li><strong>Causeways:</strong> keep right, leave the center to runners and litters. Do not stop on a bridge crest; step aside to look.</li>
    <li><strong>Precincts:</strong> remove hats, speak low, and follow the hand signs of ushers. Do not point at temple tops; open your palm if you must indicate.</li>
    <li><strong>Markets:</strong> greet the stall, praise the craft, then bargain. If a seller ties a red thread to your wrist, you owe a small tale with the coin.</li>
    <li><strong>Gifts:</strong> flowers are safe, salt is strong, feathers are a compliment. Never gift a knife without a coin to "buy back" the cut.</li>
    <li><strong>Water:</strong> step aside for water carriers and canal priests. If a boy with a shell horn asks you to hold a rope, you are helping dock a boat. Smile and pull.</li>
  </ul>

  <hr>

  <h3>Calendar and Belief</h3>
  <p>Coatlxochi keeps the <strong>Rising Eagle</strong> at dry-season peak, when banners climb the stairs and ballgames crown champions. The first rains bring the <strong>Serpent Welcoming</strong>: canals fill with floating flowers and the city thanks the lake with music and maize. Every 52 years the <strong>Reed Year Binding</strong> renews civic oaths with lamps in every district and a night when the causeways glow like constellations across the water.</p>

  <hr>

  <h3>Traveler's Note</h3>
  <p>Let the city teach you its steps: right foot on the causeway, left on the boat, eyes on the banners. Eat what the gardens offer, tip the water carriers, and keep a flower for the precinct stairs. If you pay too much at the Sun Crown, call it a gift to the balance that lets eagles and serpents share a flag. The lake will remember your courtesy.</p>
</section>
