<?php require_login(); ?>
<h1>Eagle Serpent Dominion</h1>
<p>Coatlxochi.</p>
<img src="images/harmontide-esd.png" alt="World map" usemap="#worldmap" class="world-map" />
<!-- Image Map Generated by http://www.image-map.net/ -->
<map name="worldmap">
</map>
  
  <div class="card glass">
    <h3>Paint Shack</h3>
    <p class="muted">Here you can paint your creatures from this region.</p>
    <a class="btn" href="?pg=esd_paint_shack">Explore</a>
  </div>
  
  <div class="card glass">
    <h3>Back to Gulfbelt</h3>
    <a class="btn" href="?pg=gulfbelt">Explore</a>
  </div>