<?php require_login(); ?>
<h1>Eretz-Shalem League</h1>
<img src="images/harmontide-esl.webp" alt="World map" usemap="#worldmap" class="world-map" />
<!-- Image Map Generated by http://www.image-map.net/ -->
<map name="worldmap">
</map>
  
  <div class="card glass">
    <h3>Paint Shack</h3>
    <p class="muted">Here you can paint your creatures from this region.</p>
    <a class="btn" href="?pg=esl_paint_shack">Explore</a>
  </div>
  
  <div class="card glass">
    <h3>Back to Orienthem</h3>
    <a class="btn" href="?pg=orienthem">Explore</a>
  </div>

  <section id="shalemdor">
  <h2>Shalemdor - <em>"Gate of Wholeness"</em></h2>

  <p><strong>Shalemdor</strong> climbs a sunlit ridge of pale stone, its lanes curling between courtyards, vaulted gates, and market arcades. Doorways carry small prayer-scroll cases at the lintel, olive trees lean over cisterns, and rooftops glow with clay lamps at dusk. In the Eretz-Shalem League, law is argued with learning and kindness is counted as much as coin; in Shalemdor those two threads are knotted on every street.</p>

  <p>The city is a braid of study, trade, and song. Scholars debate in cool study halls, scribes mend letters in the shade, and the shuk rings with copper, textiles, spices, and children chasing pomegranate seeds. When the sun lowers, you will hear a ram horn from a gate tower and smell bread from every block oven. Visitors learn quickly: touch the mezuzah lightly, say "shalom," and follow the shade lines laid by generations of builders who knew the noon heat well.</p>

  <hr>

  <h3>Districts and Landmarks</h3>
  <ul>
    <li><strong>Beit Midrash Quarter</strong> - Linked study houses where pages turn like wings. Disputes are written in wide margins; answers are walked, not shouted.</li>
    <li><strong>Shuk HaShalem</strong> - The great market under woven canopies. Olive oil, figs, dates, copperwork, wool, glass beads, parchment, and good gossip. Scales are inspected at midday.</li>
    <li><strong>Gate of Peace</strong> - Main eastern gate. A small court sits in its shade; travelers share water and get their first lesson in local prices.</li>
    <li><strong>Water Steps</strong> - A tiered spring with stone basins. Families draw water at dawn; in the heat, elders sit and trade short proverbs for long stories.</li>
    <li><strong>Hall of Scales</strong> - Civic hall and beit din. Cases are heard after both sides share bread; judgments prefer restitution and public charity.</li>
    <li><strong>Oil Lamp Street</strong> - Lamp makers, metalworkers, and scribes. At dusk the whole lane lights at once and looks like a river of fireflies.</li>
    <li><strong>Roofline Walk</strong> - Joined roofs where guards and neighbors cross in the cool hours. The view tells a quiet history in domes, chimneys, and fig trees.</li>
  </ul>

  <hr>

  <h3>Food and Drink</h3>
  <p><strong>Begin with bread and olives.</strong> Braided loaves for the rest day, flatbreads for the road, bowls of chickpea purees, sesame sauces, grilled eggplant, herbs, and river fish. Street sellers carry sesame rings, date cakes, and cups of herb tea. Try the <strong>Lion Gate Stew</strong> with chickpeas and lemon or a plate of <strong>Market Salads</strong> with pickles and fresh cheese. Coffee comes dark with cardamom; sweet mint tea chases the dust down.</p>

  <p>Tourist note: stalls beside the main arches charge 5 to 10 times the lane rate. Ask for the "charity measure" and nod at the fountain fund box; most sellers will soften the price and point you toward a family stall one street over.</p>

  <hr>

  <h3>Order and Underlane</h3>
  <p>Peace is kept by the <strong>Olive Ward</strong>, a watch that counts lamps as carefully as fines. The market steward walks the shuk at noon, checking weights and tempers. Records of public charity are posted weekly at the Hall of Scales. Even so, Shalemdor keeps a few shadows for hot afternoons. People whisper about the <strong>Courtyard Keys</strong>, a circle of fixers who smooth permits and night deliveries for a fee of coin and silence. They claim to serve continuity, not coin alone. Each season their donation jars are opened in public; in this city even a shadow must show a receipt.</p>

  <hr>

  <h3>Etiquette and Practicalities</h3>
  <ul>
    <li><strong>Greetings:</strong> right hand to heart and "shalom." Bargain with patience; begin with a blessing, not a number.</li>
    <li><strong>Doorways:</strong> touch the mezuzah lightly, do not kiss it unless invited. Step in with respect and a smaller voice.</li>
    <li><strong>Dress and courtyards:</strong> cover shoulders and knees in study houses and synagogues. Remove hats only when hosts do; head coverings are common.</li>
    <li><strong>Rest day:</strong> from sundown to sundown shops close, lanes quiet, and lamps glow. Plan travel and purchases around it; neighbors will help if you misjudge the hour.</li>
    <li><strong>Water:</strong> do not waste fountain water. Offer your place in line to elders and children; you will gain five friends and a better route across town.</li>
  </ul>

  <hr>

  <h3>Calendar and Belief</h3>
  <p>Shalemdor keeps a calendar of light and harvest. The <strong>Festival of Lights</strong> brightens winter with small lamps in every window and stories of old courage. The <strong>Festival of Booths</strong> fills rooftops and courtyards with shaded huts where families eat and welcome guests. In early spring the <strong>New Year of Trees</strong> sees children planting saplings along the Water Steps. Between spring and summer, the days of <strong>Counting Weeks</strong> tie learning to harvest with daily verses posted on courtyard walls.</p>

  <hr>

  <h3>Traveler's Note</h3>
  <p>Walk in the shade and keep a proverb ready. Share water, leave a coin in a charity box, and ask a scribe to write your name in a good hand. If you pay too much under the Gate of Peace, call it a gift to the lamps that make strangers look like neighbors. The city will remember you kindly and in detail.</p>
</section>
