<?php require_login(); ?>
<h1>Eretz-Shalem League</h1>
<p>Shalemdor.</p>
<img src="images/harmontide-esl.png" alt="World map" usemap="#worldmap" class="world-map" />
<!-- Image Map Generated by http://www.image-map.net/ -->
<map name="worldmap">
</map>
  
  <div class="card glass">
    <h3>Paint Shack</h3>
    <p class="muted">Here you can paint your creatures from this region.</p>
    <a class="btn" href="?pg=esl_paint_shack">Explore</a>
  </div>
  
  <div class="card glass">
    <h3>Back to Orienthem</h3>
    <a class="btn" href="?pg=orienthem">Explore</a>
  </div>