<?php require_login(); ?>
<h1>Frankenondermeer</h1>
<img src="images/harmontide-fom.webp" alt="World map" usemap="#worldmap" class="world-map" />
<!-- Image Map Generated by http://www.image-map.net/ -->
<map name="worldmap">
</map>
  
  <div class="card glass">
    <h3>Back to Rheingard</h3>
    <a class="btn" href="?pg=rheinland">Explore</a>
  </div>

  <section id="frankenondermeer">
  <h2>Frankenondermeer - 
  <em>"Where Rivers Weigh the Sky"</em>
  </h2> 
  <p>
  <strong>Frankenondermeer</strong> 
  lies where the great Rhinefork loosens into flat green polders, reed-choked creeks, and mirror-still canals. From above it looks like a ledger 
  drawn on water: long dikes, straight roads on raised embankments, and square fields shining with dew. Bell towers and tide-sails rise from the mist, 
  and the air always smells faintly of river salt, peat smoke, and frying batter.
  </p> 
  <p>The lowlands are careful and stubborn. Farmers walk the dike crowns at dawn, fingers on the wind; barge captains read the current like script; 
  children learn to count by lock-gates and flood marks. Here, law is written in water levels and ledgers more than walls. When feelings run too high, 
  the mists thicken and the old stories say the canals remember - spawning willful currents and mood-struck spirits that tug at unwary boats. 
  The people of Frankenondermeer live by three equal measures: keep the water, keep the books, keep your temper.
  </p> 
  <hr> 
  <h3>Districts and Landmarks</h3> 
  <ul> 
  <li>
  <strong>Onderhaven Chain</strong> - A string of harbor towns on a shared ring dyke, their brick gables and crane-beams leaning over the main trade canal like they are eavesdropping on every cargo.
  </li> 
  <li>
  <strong>Keerstide Locks</strong> - A massive stair of lock-gates and sluices where river and sea bargain daily. Tollkeepers keep both pages and tempers balanced; arguments wait until the next lock pool.
  </li> 
  <li>
  <strong>Mistfen Commons</strong> - Wide peat marshes and grazing meadows edged with willow and rush. Lantern posts mark safe paths; locals say the lights flicker when emotions sour.
  </li> 
  <li>
  <strong>Gable Crown Market</strong> - A barge-borne market that drifts between towns each week. Colorful awnings, cheese wheels, dried fish, canal-flowers, and ledger clerks with ink-stained cuffs.
  </li> 
  <li>
  <strong>Stillekerk Spire</strong> - An old river-chapel on a manmade hill, its tower used as a flood mark. Bells ring three times when waters rise too fast, once when the village needs calm.
  </li> 
  <li>
  <strong>Windward Mills</strong> - Tall tide-sails and windmills that grind grain and pump water, painted in house colors. At dusk their turning arms look like slow, patient guardians sweeping the sky.
  </li> 
  <li>
  <strong>Ledgerhall of Frankenondermeer</strong> - Regional seat in a modest brick town, its great chamber lined with water gauges and open ledgers. Fines feed the dikes and the lamp fund before any purse.
  </li> 
  <li>
  <strong>Reedsong Canals</strong> - Narrow side-canals where reed beds crowd the banks. Boatmen swear the wind in the reeds repeats overheard secrets and worries back to you in softer words.
  </li> 
  </ul> 
  <hr> 
  <h3>Food and Drink</h3> 
  <p>
  <strong>Eat with the weather.</strong> 
  On bright days you will find fried river fish, pickled eel, and thick slices of rye bread spread with sharp cheese and sweet syrup. In the damp chill, 
  kitchens steam with cabbage stews, potato and leek soups, and pan-cakes poured thin and rolled around apples or canal-berry jam. Try a plate of 
  <strong>Dikewalker Stew</strong> 
  with smoked sausage and beans, or a cone of 
  <strong>Harbor Crisps</strong>, 
  tiny fish fried whole with lemon and herb salt. Brewers favor light, foamy ales for day work and dark, molasses-rich beers for long stories.</p> 
  <p>
  Tourist note: barge-front stalls at the busiest locks charge 5 to 10 times the village tavern rate. Ask for the "polder share" with a smile 
  and nod toward the nearest dike box; most hosts will tap the price back to fair and suggest a family quay one bridge away.
  </p> 
  <hr> 
  <h3>Order and Underlane
  </h3> 
  <p>Water and peace are watched by the 
  <strong>Dikewardens</strong>, a civic ward that walks the embankments in blue-lined cloaks, carrying sounding poles and stamp-sealed notebooks. 
  Their judgments favor restitution: repair the dike you neglected, share half the catch you hid, fund a new lamp along the foggiest towpath. 
  Beneath the surface, boatmen whisper of the 
  <strong>Canal Ledger</strong>, 
  a loose fellowship of bargemasters and warehouse keepers who arrange quiet cargo shifts, night lockings, and discreet passage for those who 
  pay and behave. They claim their work keeps trade flowing, not lawbreaking, and each thaw they nail their redacted accounts to the Ledgerhall 
  door, line by line, for all to read.
  </p> 
  <hr> 
  <h3>Etiquette and Practicalities</h3> 
  <ul> 
  <li>
  <strong>Mind the dikes:</strong> 
  ever sit on a dike edge with your feet kicking at the turf, and do not drive stakes without asking a Dikewarden.
  </li> 
  <li>
  <strong>Step and greet:</strong> 
  on narrow towpaths, step to the field side for those leading horses or hauling barges and offer a simple "dag" or "good tide."
  </li> 
  <li>
  <strong>Boots and doorways:</strong> 
  scrape or leave muddy boots at the threshold of farmhouses and lockhouses; wood floors are harder to dry than you think.
  </li> 
  <li>
  <strong>Lantern law:</strong> 
  carry a lantern or wear a reflector charm after dusk near canals. Locals will press a spare into your hand rather than let you walk dark.
  </li> 
  <li>
  <strong>Bargaining:</strong> 
  haggle gently at the moving markets, never at the flood-time relief stalls. Begin with thanks, not accusation, and let the seller write the final number.
  </li> 
  <li>
  <strong>Mist manners:</strong> 
  in heavy fog, keep your voice low and your temper lower. Shouting on the water is said to wake brooding spirits and invite tricky currents.
  </li> 
  <li>
  <strong>Signals:</strong> 
  learn the common bell and horn calls; three short notes at night usually mean "lock closed" or "do not approach."
  </li> 
  </ul> 
  <hr> 
  <h3>Calendar and Belief</h3> 
  <p>
  The year in Frankenondermeer turns on water and wind. At the 
  <strong>First Pumping</strong> 
  in early spring, mills and tide-sails are blessed with chalk marks and songs to keep them turning true. The midsummer 
  <strong>Night of Open Locks</strong> 
  sees gates raised in careful sequence, lanterns strung along the canals, and flotillas of decorated boats gliding under quiet fireworks. 
  In autumn, the 
  <strong>Harvest of Reeds</strong> 
  brings reed-cutters, weavers, and instrument makers together for markets and music. When winter fog lays thick, families share stories during the 
  <strong>Mistwatch Evenings</strong>, 
  telling of times when anger made the waters rise and how calm words brought them down again.
  </p> 
  <hr> 
  <h3>Traveler's Note</h3> 
  <p>
  Keep your feet dry, your notebook handy, and your feelings folded, not bottled. Walk a dike at sunrise, listen to the reeds rehearse your worries, 
  and let a lockkeeper tell you how many kinds of tide there are. If you pay too much for your first cone of Harbor Crisps at Keerstide, count it as a 
  toll to the river and a lesson: in Frankenondermeer, everything flows back into balance, given time and a good ledger.
  </p> 
  </section>