<?php require_login(); ?>
<h1>Frankenondermeer</h1>
<img src="images/harmontide-fom.png" alt="World map" usemap="#worldmap" class="world-map" />
<!-- Image Map Generated by http://www.image-map.net/ -->
<map name="worldmap">
</map>
  
  <div class="card glass">
    <h3>Back to Rheingard</h3>
    <a class="btn" href="?pg=rheinland">Explore</a>
  </div>