<?php require_login(); ?>
<h1>Gran Columbia</h1>
<img src="images/harmontide-gc.webp" alt="World map" usemap="#worldmap" class="world-map" />
<!-- Image Map Generated by http://www.image-map.net/ -->
<map name="worldmap">
</map>
  
  <div class="card glass">
    <h3>Paint Shack</h3>
    <p class="muted">Here you can paint your creatures from this region.</p>
    <a class="btn" href="?pg=gc_paint_shack">Explore</a>
  </div>
  
  <div class="card glass">
    <h3>Back to Verdania</h3>
    <a class="btn" href="?pg=verdania">Explore</a>
  </div>

  <section id="solvine">
  <h2>Solvine - <em>"City of Sun and Vines"</em></h2>

  <p><strong>Solvine</strong> is a modern metropolis where glass towers climb above old plazas and hillside barrios spill down like terraces of green. The riverfront glitters at night, streetcars hum, and murals bloom across concrete like jacaranda. Gran Columbia built Solvine as a promise: culture, commerce, and sunlight in the same square meter.</p>

  <p>The vibe is present-day and proud. Cafes open before dawn for cyclists and dockworkers, tech incubators share blocks with print shops, and corner tiendas sit beside regulated pharmacies. The city runs a clear legal framework for controlled substances and harm-reduction: licensed dispensaries, ID checks, health desks, and strict zoning. Street festivals feel electric but organized; you will see safety tents and water stations beside food trucks and sound stages.</p>

  <hr>

  <h3>Districts and Landmarks</h3>
  <ul>
    <li><strong>Golden Mile</strong> - Riverwalk of parks, museums, and towers. Sunset turns the glass gold. Runners, families, and buskers share the path; food carts cluster near the footbridges.</li>
    <li><strong>Cerro Verde</strong> - Hillside neighborhoods with cable-cars, stair murals, pocket gardens, and community ovens. Best city views, best street arepas.</li>
    <li><strong>Plaza Sol</strong> - Historic core. Cathedral shadow on modern bricks, palms around a long fountain. Weekend book markets and artisan fairs set up here.</li>
    <li><strong>Mercado Andino</strong> - Covered market with fruit pyramids, ceviche bars, coffee roasters, florists, and vinyl stalls. Prices honest, lines long for the roast pork stand.</li>
    <li><strong>Juramento Complex</strong> - Civic and legal quarter. City Hall, public ombuds, and the Health & Safety Pavilion where the harm-reduction desks live.</li>
    <li><strong>Parque del Vino</strong> - Riverbank amphitheater and lawns under vineyard trellises. Outdoor films, concerts, and evening dance classes.</li>
    <li><strong>Solar Yard</strong> - Start-up sheds turned studios. Makerspaces, indie galleries, and food halls; most doors are murals waiting to happen.</li>
  </ul>

  <hr>

  <h3>Food and Drink</h3>
  <p><strong>Eat the valley.</strong> Arepas and empanadas at dawn, ceviche with sweet corn and plantain chips at noon, roast pork with crackling and aji by evening. Street coconuts, passionfruit juices, and coffee that could move a bus. Try a <strong>Solvine Cooler</strong> (lime, panela, sparkling water) or a glass from the urban wineries along Parque del Vino.</p>

  <p>Tourist note: riverfront kiosks mark up 5 to 10 times compared to Mercado Andino. Ask for the "vecino rate" with a smile and a "por favor"; most vendors will meet you halfway and point you to the stall they eat at.</p>

  <hr>

  <h3>Order and Underlane</h3>
  <p>The <strong>Civic Guard</strong> runs on cameras, body cams, and a lot of paperwork. Fines tilt toward community service and cleanup. Health teams work the nightlife beat with water, info cards, and free rides to clinics when needed. Still, whispers cling to the viaducts: the <strong>Vine Syndicate</strong> moves favors and fast deliveries through a web of couriers and coded stickers. They call it logistics, not a racket. The Guard audits charity ledgers and zoning permits every quarter; in Solvine even shadows get spreadsheeted.</p>

  <p>Legal note: licensed pharmacies and lounges operate under zoning. Street sellers do not. If a price sounds too good, it is; the Civic Guard will agree. Use common sense, follow posted rules, and keep the emergency number saved.</p>

  <hr>

  <h3>Etiquette and Practicalities</h3>
  <ul>
    <li><strong>Transit:</strong> tap card for streetcar and cable-car. Offer seats to elders. Keep doors clear; platform lines are not decorative.</li>
    <li><strong>Nightlife:</strong> carry ID. Stay in lit corridors. Hydrate. Follow staff instructions at security checks and health tents.</li>
    <li><strong>Markets:</strong> greet first, bargain second. Do not squeeze fruit you are not buying. Cash is king for small stalls; cards work most elsewhere.</li>
    <li><strong>Hills:</strong> respect the stairs and the neighbors. Quiet hours start at 22:00 off the main drags.</li>
    <li><strong>Safety:</strong> keep your bag zipped and your phone off the railings. If you feel watched, step into a lit shop or callbox; staff are trained to help.</li>
  </ul>

  <hr>

  <h3>Calendar and Belief</h3>
  <p>Solvine keeps a calendar of light. <strong>Sunvine Week</strong> brings parades and vineyard nights. <strong>River Bloom</strong> turns the Golden Mile into a flower corridor. <strong>Night of Lanterns</strong> floats candles from the hill to the river. Civic days post budgets on city walls and hand out saplings for balcony gardens; kids race to claim the tallest ones.</p>

  <hr>

  <h3>Traveler's Note</h3>
  <p>Solvine wants you fed, sunlit, and on time. Walk the river at dusk, ride the cable-car at blue hour, tip street musicians, and drink water between coffees. If the kiosk charges too much, call it a view tax and move one block inland next time. The city will repay your patience with a mural, a melody, and a plate that tastes like warm stone and bright fruit.</p>
</section>
