<?php require_login(); ?>
<h1>Gran Columbia</h1>
<p>Solvine.</p>
<img src="images/harmontide-gc.png" alt="World map" usemap="#worldmap" class="world-map" />
<!-- Image Map Generated by http://www.image-map.net/ -->
<map name="worldmap">
</map>
  
  <div class="card glass">
    <h3>Paint Shack</h3>
    <p class="muted">Here you can paint your creatures from this region.</p>
    <a class="btn" href="?pg=gc_paint_shack">Explore</a>
  </div>
  
  <div class="card glass">
    <h3>Back to Verdania</h3>
    <a class="btn" href="?pg=verdania">Explore</a>
  </div>