<?php require_login(); ?>
<h1>Gulfbelt</h1>
<p>State selection coming soon.</p>
<img src="images/harmontide-gulfbelt.png" alt="World map" usemap="#worldmap" class="world-map" />
<!-- Image Map Generated by http://www.image-map.net/ -->
<map name="worldmap">
</map>
  
  <div class="card glass">
    <h3>Eagle Serpent Dominion</h3>
    <p class="muted">Home of Quetzalcoatl.</p>
    <a class="btn" href="?pg=esd">Explore</a>
  </div>
  
  <div class="card glass">
    <h3>Itzam Empire</h3>
    <p class="muted">Rainforests... Lotsa Rainforests.</p>
    <a class="btn" href="?pg=ie">Explore</a>
  </div>
  
  <div class="card glass">
    <h3>Back to world map</h3>
    <a class="btn" href="?pg=map">Explore</a>
  </div>