<?php require_login(); ?>
<h1>Hammurabia</h1>
<img src="images/harmontide-hammurabia.webp" alt="World map" usemap="#worldmap" class="world-map" />
<!-- Image Map Generated by http://www.image-map.net/ -->
<map name="worldmap">
</map>
  
  <div class="card glass">
    <h3>Paint Shack</h3>
    <p class="muted">Here you can paint your creatures from this region.</p>
    <a class="btn" href="?pg=h_paint_shack">Explore</a>
  </div>
  
  <div class="card glass">
    <h3>Back to Orienthem</h3>
    <a class="btn" href="?pg=orienthem">Explore</a>
  </div>

  <section id="ziggurab">
  <h2>Ziggurab - <em>"Stepped City of River-Law"</em></h2>

  <p><strong>Ziggurab</strong> rises from the fork of two brown rivers, a city of sun-baked brick, 
  blue glaze, and shadowed lanes. Canals stitch the quarters like seams; reed boats nose the wharves; the air smells of date syrup, clay, 
  and bitumen after heat. At its heart stands the great stepped temple that gave the city its name. In Hammurabia, the river teaches justice: 
  measure fairly, keep channels clear, and do not move your neighbor's marker stone.</p>

  <p>This is a city of tablets and toll-gates. Scribes press wedges into wet clay under porticoes while gaugers read rods and cords in the sun. 
  Laws are posted as steles in market courts; elders recite them by memory with a hand on a basket of grain. When the south wind drops, you can 
  hear the ziggurat stair hum with pilgrims counting each step like a quiet abacus of days.</p>

  <hr>

  <h3>Districts and Landmarks</h3>
  <ul>
    <li><strong>Stair of the Stars</strong> - The ziggurat precinct. Stepped terraces, a shrine at the top for dawn offerings, and a shadow-court below where verdicts are read with water shared first.</li>
    <li><strong>Tablet House</strong> - Scribal quarter. Schools for numbers, contracts, and maps of canals. Public tablets record floodmarks going back farther than anyone's grandmother remembers.</li>
    <li><strong>Gate of Lions</strong> - Glazed-brick processional gate. Market toll is taken here; weights are checked at noon on a public balance beam.</li>
    <li><strong>Canal of Measures</strong> - Main waterway lined with workshops. Potters, metal casters, fabric dyers, and the House of Reed where boaters mend their craft.</li>
    <li><strong>Bitumen Wharf</strong> - Low wharf where barges load jars and bricks. Smells strong but honest. The tide board here is the city's metronome.</li>
    <li><strong>Date Grove Quarter</strong> - Lanes of palms and mud-brick courtyards. Press houses boil syrup; children climb stone ricks pretending they are towers.</li>
    <li><strong>House of Weights and Rods</strong> - Civic office that certifies measures. Marks are re-cut at the new year; fines for tampered scales are severe and public.</li>
  </ul>

  <hr>

  <h3>Food and Drink</h3>
  <p><strong>Eat from grove and river.</strong> Flatbreads, grilled river fish with herbs, lentil pots, onion stews, goat skewers with coriander, 
  and date cakes sticky as afternoon sun. Street sellers pour barley beer and pressed date water; travelers swear by clay cups of sour yogurt in the heat. 
  Try the <strong>Stele Platter</strong> near the Gate of Lions: bread, soft cheese, olives, pickles, and a scoop of sweet date paste.</p>

  <p>Tourist note: stalls beside the ziggurat steps and the Gate of Lions run 5 to 10 times the lane rate. Ask for the "canal measure" and 
  mention the last floodmark year; most sellers will smile and shave the number.</p>

  <hr>

  <h3>Order and Underlane</h3>
  <p>Peace is kept by the <strong>Canal Ward</strong>, a watch that travels on foot and by skiff with ledgers and rods. Restitution and canal 
  work are the usual sentences; those who foul the water sweep the steps at dawn. Even so, Ziggurab keeps a few shadows under its arches. 
  Travelers whisper about the <strong>Marker Guild</strong>, quiet fixers who arrange night deliveries and "lost-and-found" marker stones for a fee in 
  silver and silence. They call it keeping flow, not a racket. Each season the Canal Ward opens their charity jars in public at the House of Weights; 
  in this city even a shadow must show a receipt.</p>

  <hr>

  <h3>Etiquette and Practicalities</h3>
  <ul>
    <li><strong>Water:</strong> step aside for carriers. Do not bathe or wash animals in public channels. Offer a dipper to elders before yourself.</li>
    <li><strong>Gates and courts:</strong> hats off under the Gate of Lions. Speak low; verdicts are heard after both sides share water.</li>
    <li><strong>Markets:</strong> greet the stall, praise the craft, then bargain. Weights may be checked on the public beam; smart sellers will offer before you ask.</li>
    <li><strong>Stairs:</strong> on the ziggurat, keep to the right, count your steps if you like, and do not block the landings. Offerings are small: flowers, grain, clean water.</li>
    <li><strong>Heat:</strong> rest in shade at high sun. The city wakes again when the brick cools and lamps glow in niches.</li>
  </ul>

  <hr>

  <h3>Calendar and Belief</h3>
  <p>Ziggurab keeps the <strong>Flood Calling</strong> at river-rise: clay tablets with last year's height are washed and re-inscribed, and officials cast bread to thank the river. 
  The <strong>Binding of Measures</strong> at new year re-marks rods and recalibrates weights. On <strong>Night of Lamps</strong> families place oil lights on canal edges so 
  the water can find its way. Harvest ends with the <strong>Date Boil</strong>, when syrup kettles run all night and the air tastes like copper and honey.</p>

  <hr>

  <h3>Traveler's Note</h3>
  <p>Ziggurab is patient and exact. Walk its lines, mind its markers, and drink its water with gratitude. If you pay too much by the Gate of Lions, call it a contribution to 
  the balance beam that keeps trade honest. The river will remember your manners when the banks grow tight.</p>
</section>
