<?php require_login(); ?>
<h1>Itzam Empire</h1>
<img src="images/harmontide-ie.webp" alt="World map" usemap="#worldmap" class="world-map" />
<!-- Image Map Generated by http://www.image-map.net/ -->
<map name="worldmap">
</map>
  
  <div class="card glass">
    <h3>Paint Shack</h3>
    <p class="muted">Here you can paint your creatures from this region.</p>
    <a class="btn" href="?pg=ie_paint_shack">Explore</a>
  </div>
  
  <div class="card glass">
    <h3>Back to Gulfbelt</h3>
    <a class="btn" href="?pg=gulfbelt">Explore</a>
  </div>

  <section id="itzankaan">
  <h2>Itzankaan - <em>"Serpent of the Sky"</em></h2>

  <p><strong>Itzankaan</strong> crowns a limestone ridge between jungle and sinkhole lakes. White plaster gleams on stepped temples, serpent balustrades curl down sun-stairs, and straight stone causeways cut the green like pale lightning. In the Itzam Empire the city is both calendar and crown: days are read in shadows along stair edges, laws are carved in glyphs on stelae, and water is counted as carefully as tribute.</p>

  <p>This is a capital of astronomers, builders, and gardeners. Stargazers watch from roof platforms, masons smooth lime by hand, and scribes paint codices in red and black. Canal canoes slide from cenote to market; runners carry shell trumpets and reed messages along the sacbe roads. Visitors learn fast: follow the white stones, keep your voice low at temple feet, and step wide of the iguanas sunning on the plaza edge.</p>

  <hr>

  <h3>Districts and Landmarks</h3>
  <ul>
    <li><strong>Serpent Stair Precinct</strong> - Twin pyramids frame the main plaza. On equinox, serpent shadows ripple down the north stair to greet the crowd. Decrees are read at noon from the south terrace.</li>
    <li><strong>House of Glyphs</strong> - Scribes, painters, and binders. Bark-paper codices dry on racks; apprentices grind pigment while masters mend old histories.</li>
    <li><strong>Ballcourt of Banners</strong> - A long sunken court where teams play under scarlet pennants. The crowd speaks with rattles and hand signs more than shouts.</li>
    <li><strong>Cenote Quarter</strong> - Plazas around open blue water. Rope ladders, shaded steps, and shrines for thanks. Water officials log levels on a stone board at dawn.</li>
    <li><strong>Sacbe Gate</strong> - Start of the straight white road to the outlands. Runners rest in shade niches, traders stack baskets by glyph-marked weights.</li>
    <li><strong>Garden Terraces</strong> - Maize, beans, squash, and flowers step the hill in green combs. Beehives sit in clay pots; honey is treaty and dessert both.</li>
    <li><strong>Sounding Court</strong> - A plaza where a clap comes back as a flock of echoes. Musicians meet here at dusk with drums and shell horns.</li>
  </ul>

  <hr>

  <h3>Food and Drink</h3>
  <p><strong>Eat the terrace and the lake.</strong> Fresh tortillas, tamales steamed in leaves, chiltomate salsas, squash blossom stews, lake fish with herbs, and turkey with achiote. Street cups brim with atole hot and thick or cacao spiced and frothy. Try the <strong>Serpent Green</strong> sauce at the market grills or a pile of lime-cured fish with maize crisps at the cenote steps.</p>

  <p>Tourist note: stalls facing the Serpent Stair Precinct cost 5 to 10 times more than lane stands. Ask for the "garden measure" and name a terrace you visited; vendors usually nod and pour you the price a canal boatman pays.</p>

  <hr>

  <h3>Order and Underlane</h3>
  <p>Peace is kept by the <strong>White Road Ward</strong> on the sacbe and the <strong>Cenote Guard</strong> at the water. Fines favor labor on terraces, steps, and drains. Even so, the city keeps shade. People whisper about the <strong>Night Bats</strong>, a courier brotherhood that moves sealed bundles and delicate favors after curfew for a fee of shells and silence. They call it flow, not a racket. Each moon the Ward opens their charity baskets in public at the House of Glyphs; in Itzankaan even a shadow shows a receipt.</p>

  <hr>

  <h3>Etiquette and Practicalities</h3>
  <ul>
    <li><strong>Temples:</strong> hats off, voices low. Do not climb beyond the rope rail. Offer a flower, a little maize, or clean water.</li>
    <li><strong>Cenotes:</strong> rinse feet, not clothes. No soap in open water. Let elders descend first and keep the steps clear.</li>
    <li><strong>Markets:</strong> greet with an open palm, praise the craft, then bargain. If a seller ties a thread to your wrist, you owe a short tale with your coin.</li>
    <li><strong>Causeways:</strong> keep right for runners. Step aside at shell horn, then wave them through.</li>
    <li><strong>Heat:</strong> rest in shade at high sun. The city wakes again when the plaster cools and drums begin.</li>
  </ul>

  <hr>

  <h3>Calendar and Belief</h3>
  <p>Itzankaan keeps the <strong>Binding of Years</strong> when cycle stones are turned and oaths renewed with lamps across the sacbe. Equinox brings the <strong>Serpent Descent</strong> at the north stair; the first rains host the <strong>Flowering Waters</strong> as boats spill petals into the cenotes. On the <strong>Night of Echoes</strong> musicians test the Sounding Court and children chase the clap that turns into birds.</p>

  <hr>

  <h3>Traveler's Note</h3>
  <p>Walk the white roads, count the stair shadows, and drink water with thanks before wit. Tip the runner who answers your lost look, buy honey where the bees fly, and keep a flower for the temple steps. If you pay too much by the serpent stair, call it tribute to the calendar that keeps the city and the sky in step. Itzankaan will remember you kindly in glyph and in gossip.</p>
</section>
