<?php require_login(); ?>
<h1>Kemet</h1>
<img src="images/harmontide-k.webp" alt="World map" usemap="#worldmap" class="world-map" />
<!-- Image Map Generated by http://www.image-map.net/ -->
<map name="worldmap">
</map>
  
  <div class="card glass">
    <h3>Paint Shack</h3>
    <p class="muted">Here you can paint your creatures from this region.</p>
    <a class="btn" href="?pg=k_paint_shack">Explore</a>
  </div>
  
  <div class="card glass">
    <h3>Shelter</h3>
    <p class="muted">A shelter where you can either abandon or adopt.</p>
    <a class="btn" href="?pg=k_shelter">Explore</a>
  </div>
  
  <div class="card glass">
    <h3>Back to Saharene</h3>
    <a class="btn" href="?pg=saharene">Explore</a>
  </div>

  <section id="ankhmeru">
  <h2>Ankhmeru - <em>"City of the Living Pillar"</em></h2>

  <p><strong>Ankhmeru</strong> stands on a bend of the Great River, its twin banks joined by barges and a long stone bridge of lion pylons. East-bank temples lift painted pylons against the sun; west-bank terraces climb toward the desert where tomb roads vanish into golden cliffs. In Kemet, measure and memory keep the world upright; in Ankhmeru both are written on stone and water.</p>

  <p>The city breathes in three beats: temple, granary, river. Priests time the day with shadow and incense; scribes tally grain with reed pens in cool storehouses; boatmen muscle cedar oars under nets of swallows. At noon the hypostyle halls hold shade like a lake, and the blue of the ceiling is speckled with stars to remind the heat it is only borrowing the sky.</p>

  <hr>

  <h3>Districts and Landmarks</h3>
  <ul>
    <li><strong>Pylon of the Dawn</strong> - Eastern temple gate painted with banners of sun and lotus. Courts inside stage processions; the sacred lake lies beyond a colonnade where palm shadows stripe the water.</li>
    <li><strong>Hall of Pillars</strong> - Forest of painted columns. Petitioners tie linen wishes to railings; the air smells of resin, cool water, and old stories.</li>
    <li><strong>House of Life</strong> - Scriptorium and clinic. Scribes copy healing texts; herb jars line mud-brick shelves; novices learn letters by tracing birds, hands, and waves.</li>
    <li><strong>Nilometer Court</strong> - Stair and shaft cut to the river for reading the flood. Officials carve the height on stone; tax and feast both follow the mark.</li>
    <li><strong>Granary Row</strong> - Long vaulted barns with seal-rooms and tally niches. Wheat dunes under reed mats; cats patrol like little gods with whiskers.</li>
    <li><strong>Market of Palms</strong> - Palm-roofed stalls, copper and alabaster, baskets, faience, linen, dates, onions, fish strung like silver. Drummers call the cool hour when prices soften.</li>
    <li><strong>Westbank Necropolis Way</strong> - Processional road between guardian statues. Carvers tap reliefs by lamplight; tomb stewards water acacia trees and chase away hyenas with jokes.</li>
    <li><strong>Harbor of Papyrus</strong> - Boat sheds and net yards. Reed skiffs, broad-bellied grain barges, cedar ships with painted eyes that watch the current.</li>
  </ul>

  <hr>

  <h3>Food and Drink</h3>
  <p><strong>Bread and beer first, then stories.</strong> Flat loaves warm from dome ovens, barley beer poured cool and cloudy, river fish with coriander, fava stews, cucumbers with salt, figs and dates, honey cakes shaped like lotus buds. Try <strong>Flood Platter</strong> near the Nilometer: bread, soft cheese, pickled onions, olives, and a sweet spoon of date paste. In the evening, sip <strong>Lotus Water</strong> (herb and blossom infusion) or a cup of desert wine from a clay jug that sweats in the shade.</p>

  <p>Tourist note: stalls under the Pylon of the Dawn and at the westbank ferry charge 5 to 10 times the lane rate. Ask for the "scribe measure" and compliment the tally marks; most sellers will smile and lower the number to something a boatman would pay.</p>

  <hr>

  <h3>Order and Underlane</h3>
  <p>Peace is kept by the <strong>Medjay Ward</strong>, sand-cloaked watch with ledgers and batons. Fines favor restitution and temple work: sweeping courts at dawn, hauling water to gardens, repairing quay stones. Yet Ankhmeru is old and shade grows in old places. People whisper of the <strong>Copper Jackals</strong>, night runners who move sealed bundles between tomb ramps and river sheds for a fee of silence and bronze. They call it keeping flow, not a racket. Each season the Medjay open their charity jars in public at the House of Life; in this city even a shadow must show a receipt.</p>

  <hr>

  <h3>Etiquette and Practicalities</h3>
  <ul>
    <li><strong>Temples:</strong> hats off, shoulders covered. Walk sunwise unless told otherwise. Do not touch reliefs; stone remembers fingers.</li>
    <li><strong>Offerings:</strong> small and simple: a flower, a pinch of incense, a cup of clean water. Announce your name softly to the gate.</    li>
    <li><strong>Necropolis:</strong> voices low, feet careful. Do not sit on sarcophagi or lean on painted walls. Guides earn their copper by knowing where not to point a torch.</li>
    <li><strong>Markets:</strong> greet with a palm over heart, praise the craft, then bargain. Weights are stones; ask to see the balance and you will be trusted more, not less.</li>
    <li><strong>River:</strong> make way for water carriers and funerary barges. If a boy asks you to hold a rope, you are helping dock a grain boat. Smile and pull.</li>
    <li><strong>Heat:</strong> rest at high sun in colonnades and gardens. The city wakes again when the brick cools and lamps bloom in niches.</li>
  </ul>

  <hr>

  <h3>Calendar and Belief</h3>
  <p>Ankhmeru keeps the <strong>Opening of the Year</strong> when the first flood marks are cut and garlands float down the river. The <strong>Procession of the Living God</strong> carries a veiled image by boat between east and west with music and cheers on both banks. In the <strong>Festival of the Valley</strong> families picnic at tomb doors, sharing bread with the quiet. At the <strong>Weighing of Words</strong> (a civic rite, not a trial) scribes read old promises in the Hall of Pillars and citizens add one new line to the ledger of Ma at.</p>

  <hr>

  <h3>Traveler's Note</h3>
  <p>Ankhmeru prefers measure to hurry. Walk in straight lines and cool shadows, count your change with a smile, and leave a cup of water where a stranger will find it. If you pay too much at the pylon, call it an offering to the pillars that keep the sky up. The river will remember your courtesy when the flood comes thin.</p>
</section>
