<?php require_login(); ?>
<h1>Kemet</h1>
<p>Ankhmeru.</p>
<img src="images/harmontide-kemet.png" alt="World map" usemap="#worldmap" class="world-map" />
<!-- Image Map Generated by http://www.image-map.net/ -->
<map name="worldmap">
</map>
  
  <div class="card glass">
    <h3>Back to Saharene</h3>
    <a class="btn" href="?pg=saharene">Explore</a>
  </div>