<?php require_login(); ?>
<h1>Lotus-Dragon Kingdom</h1>
<img src="images/harmontide-ldk.webp" alt="World map" usemap="#worldmap" class="world-map" />
<!-- Image Map Generated by http://www.image-map.net/ -->
<map name="worldmap">
</map>
  
  <div class="card glass">
    <h3>Paint Shack</h3>
    <p class="muted">Here you can paint your creatures from this region.</p>
    <a class="btn" href="?pg=ldk_paint_shack">Explore</a>
  </div>
  
  <div class="card glass">
    <h3>Daycare</h3>
    <p class="muted">You can leave the creatures with them. Maybe you will find a surprise.</p>
    <a class="btn" href="?pg=ldk_breeding">Explore</a>
  </div>
  
  <div class="card glass">
    <h3>Back to Dawnmarch</h3>
    <a class="btn" href="?pg=dawnmarch">Explore</a>
  </div>

  <section id="shenhedu">
  <h2>Shenhedu - <em>"Capital of the Divine River"</em></h2>

  <p><strong>Shenhedu</strong> spreads along a slow blue river, its skyline a forest of upturned eaves and watchtowers. Red pillars, green tiles, white plaster, and shadowed courtyards stitch together canals, scholar gardens, and teahouse lanes. Think late imperial splendor: drum and bell towers mark the hours, guild halls face stone bridges, and pagodas step skyward like prayer in wood and tile. In the Lotus-Dragon Kingdom, harmony is policy; in Shenhedu it is carpentered into every beam.</p>

  <p>The city breathes in rhythms of study, craft, and rite. Magistrates read petitions under veranda shade; calligraphers grind ink until it shines; boatmen punt beneath willow arches while tea steam climbs like a quiet dragon. The Lotus-Dragon Way is lived as courtesy: balance your steps, your price, and your voice. The river does not hurry and neither does good work.</p>

  <hr>

  <h3>Districts and Landmarks</h3>
  <ul>
    <li><strong>Bell and Drum Terrace</strong> - Twin towers on a stone rise. The bell calls dawn, the drum settles dusk. Climb at the hour change and feel the timbers sing.</li>
    <li><strong>Celadon Gate</strong> - Main southern gate with guardian beasts and a plaque in gilt characters. Market inspectors and storytellers share the shade here.</li>
    <li><strong>Lotus Court</strong> - Temple and cloister around a mirror pond. Monks tend lanterns; Daoist adepts read wind over water. Offer a single flower, not a bouquet.</li>
    <li><strong>Scholar Gardens</strong> - Rock, pine, water, and pavilion in perfect argument. Windows frame borrowed views; paths invite slow feet and fast thoughts.</li>
    <li><strong>Hutong North</strong> - Alley neighborhoods of gray brick, red doors, and courtyard homes. Cricket sellers, kite makers, paper shops, and the best sesame noodles after rain.</li>
    <li><strong>Jade Canal</strong> - Working waterway lined with warehouses and tea barges. Stone humpback bridges give boats a polite headache and painters a living.</li>
    <li><strong>Guild Street</strong> - Carpenters, lacquerers, silk weavers, and bronze casters behind carved plaques. Apprentices bow with sawdust in their hair.</li>
    <li><strong>Azure Pagoda</strong> - Seven stories of timber and tile. Pilgrims circle sunwise; the wind at the fifth landing smells like pine and old paper.</li>
  </ul>

  <hr>

  <h3>Food and Tea</h3>
  <p><strong>Eat with balance, drink with patience.</strong> Steamed buns with pork or mushrooms, river fish with ginger and scallion, tofu braised in clay pots, pea shoots with garlic, duck lacquered until the skin crackles, and noodles pulled like silk. Teahouses pour green, oolong, and dark leaf with a bow and a timer. Try the <strong>Lotus Banquet</strong> in Lotus Court for festival days or a <strong>Boatman Bowl</strong> of rice, pickles, and hot broth along Jade Canal.</p>

  <p>Tourist note: stalls under the Celadon Gate and by the pagoda steps charge 5 to 10 times the lane price. Ask for the "neighbor measure" and compliment the brushwork on the signboard; most sellers will smile and shave the number.</p>

  <hr>

  <h3>Order and Underlane</h3>
  <p>Peace is kept by the <strong>River Magistracy</strong> and the <strong>City Watch</strong>, more ledgers than spears on most days. Fines favor restoration: sweeping temple courts, mending bridge rails, or copying rules in neat hand. Even so, Shenhedu has shade beneath its eaves. People mention the <strong>Night Couriers</strong>, discreet go-betweens who move sealed letters and delicate shipments after curfew for a fee of tea bricks and silence. They call it courtesy, not a racket. Each season their donation chests are opened in public at the Bell Terrace; in this city even a shadow shows a receipt.</p>

  <hr>

  <h3>Etiquette and Practicalities</h3>
  <ul>
    <li><strong>Greetings:</strong> a small bow with hands folded. Loud voices are for rivers in flood, not markets.</li>
    <li><strong>Shrines and halls:</strong> hats off, shoes clean. Incense one stick at a time. Do not tap carved dragons for luck; they bite in stories and splinter in truth.</li>
    <li><strong>Tea:</strong> tap the table with two fingers to thank a pour. Do not drown leaves. Your cup will be filled if your manners are.</li>
    <li><strong>Markets:</strong> praise the craft, then bargain. If a vendor ties a red cord around your purchase, it is blessed against clumsiness; do not cut it until you get home.</li>
    <li><strong>Curfew:</strong> drum at second watch. Lanterns dim in hutongs; keep to main lanes or hire a licensed lantern guide.</li>
    <li><strong>Boats and bridges:</strong> give way to water bearers and funeral barges. On humpbacks, do not stop at the crest to pose; step aside to look.</li>
  </ul>

  <hr>

  <h3>Calendar and Belief</h3>
  <p>Shenhedu keeps the <strong>Lantern River</strong> at first full moon: canals glow with floating lights and bridges wear silk. <strong>Clear Bright</strong> sends families to sweep graves and picnic under willow. In midsummer the <strong>Dragon Boat Days</strong> thunder down the Jade Canal, oars beating like drums. At <strong>Autumn Moon</strong> neighbors trade cakes and poems on rooftops. Temples, academies, and guild halls share courtyards; the Lotus-Dragon Way likes truth to sit where tea can reach it.</p>

  <hr>

  <h3>Traveler's Note</h3>
  <p>Walk softly, watch closely, and let the city measure your steps to its drum and bell. If you overpay under the Celadon Gate, call it a donation to the eaves that keep rain off strangers. The river will forgive math done with a bow.</p>
</section>
