<?php require_login(); ?>
<h1>Moana Crown</h1>
<img src="images/harmontide-moana_crown.png" alt="World map" usemap="#worldmap" class="world-map" />
<!-- Image Map Generated by http://www.image-map.net/ -->
<map name="worldmap">
</map>
  
  <div class="card glass">
    <h3>Spice Route League</h3>
    <p class="muted">Lots of islands and their fascinating culture.</p>
    <a class="btn" href="?pg=srl">Explore</a>
  </div>
  
  <div class="card glass">
    <h3>Back to world map</h3>
    <a class="btn" href="?pg=map">Explore</a>
  </div>