<?php require_login(); ?>
<section id="skeldgard">
  <h1>Nornheim</h1>
  
<!-- Image Map Generated by http://www.image-map.net/ -->
<img src="harmontide-skeldgard.webp" usemap="#image-map">
<map name="image-map">
    <area target="" alt="paint shack" title="paint shack" href="?pg=nh_paint_shack" coords="558,373,495,388,469,433,465,465,531,483,591,457,585,419" shape="poly">
    <area target="" alt="adventure" title="adventure" href="?pg=nh-adventure" coords="686,146,653,222,701,254,731,153" shape="poly">
</map>
  
  <div class="card glass">
    <h3>Paint Shack</h3>
    <p class="muted">Here you can paint your creatures from this region.</p>
    <a class="btn" href="?pg=nh_paint_shack">Explore</a>
  </div>


  <div class="card glass">
    <h3>Adventure: The Weeping Lanes</h3>
    <p class="muted">A time-locked horror adventure set in a deserted village near Skeldgard.</p>
    <a class="btn" href="?pg=nh-adventure">Enter at Dusk</a>
  </div>

  <div class="card glass">
    <h3>Back to Auronia</h3>
    <a class="btn" href="?pg=auronia">Back</a>
  </div>

  <h2>Skeldgard - <em>“Shield-Yard of the North”</em></h2>
  <p><strong>Skeldgard</strong> stands at the head of a blue fjord where wind and glacier bargain. It is the thingstead-capital of Nornheim-stone circles for law, longhalls for counsel, and a cliff-side terrace where roots like iron twist from the earth. The city lives by a simple measure: <em>oaths keep the cold out</em>. Break them, and the cold remembers your name.</p>

  <p>At the city’s crown rises the <strong>Shieldring</strong>, a broad assembly ground where the folk gather to speak under the eye of the <em>Nornweave</em>. Three loom-poles stand at the center. Citizens tie grievance-ribbons to the warp and, before witnesses, weave them into the public cloth-anger measured and put away, draugr kept from forming. The saga-singers say the Worldtree once brushed this hill; Skeldgard treats every law as a branch that must flex, not freeze.</p>

  <hr>

  <h3>Districts &amp; Landmarks</h3>
  <ul>
    <li><strong>The Shieldring (Thingstead)</strong> - Stone tiers encircle the <em>Law Rock</em>. Oaths are spoken in low voices; boasting counts as wind and is struck from the record.</li>
    <li><strong>Worldroot Terrace</strong> - Terraced gardens braided with living roots and the <em>Public Loom</em>. At dusk the cloth glows faintly-proof that today’s quarrels were made small.</li>
    <li><strong>Whale-Gate Harbor</strong> - Ice-scored piers and a gate carved as a breaching leviathan. The harbor bell is a whale rib; it tolls when storms or strangers come in numbers.</li>
    <li><strong>Hall of Runes</strong> - The runographers’ college. Runes are cut in patient strokes; quick cuts turn to curses. Visitors may commission a <em>truth stave</em> (tiny, worn at the throat) to keep tongues honest.</li>
    <li><strong>Valkyrie Steps</strong> - A steep stair of black stone leading to the wind-shrine. Shields hang there, gifts to the storm for safe roads; take one without trade and the gale will take your hat first, your footing second.</li>
    <li><strong>Oath-Ice Bridge</strong> - A frostbound span seeded with vow-stone. It sings when a promise is kept upon it and hairline-cracks when one is not. Couples cross it hand-in-hand; traders cross it counting.</li>
    <li><strong>Hearthlane Market</strong> - Night stalls lit by oil and amber. Smoked fish, hot berry-cakes, brass clasp-work, and quiet bargains over felted mittens.</li>
  </ul>

  <hr>

  <h3>Table &amp; Tankard</h3>
  <p>Skeldgard hospitality is plain and proud. Bowls of <strong>root stew</strong> arrive with dark bread and a pat of cultured cream; <strong>fir-smoked trout</strong> flakes beside pickled greens; and the kettle yields <strong>pine-needle tea</strong> for clear heads or <strong>honey-mead</strong> for warm boasts. Try the winter specialty: <em>ember-cheese on rye</em>, crisped on a stone and eaten standing. Outsiders ask for “glory cuts”; locals laugh and serve you the end-slice with extra char.</p>

  <p>If you need a place name to remember, find the longhouse called <strong>Three Looms</strong>. The stewing pot never empties, and the keeper can recite the last ten oaths sworn at the Shieldring without peeking at the board. Prices rise with the wind; calmer days are cheaper days.</p>

  <hr>

  <h3>Order &amp; Shadow</h3>
  <p>The city watch is the <strong>Shield-Thing</strong>, oath-bound neighbors in wolf-gray cloaks. They carry <em>weregild ledgers</em> and little patience for “clever law.” Skeldgard admits there are <strong>Ice-Deeds</strong>-unsigned contracts that pass hand-to-hand in the thaw, binding favors outside the ring. The Shield-Thing doesn’t call it a mafia; they call it <em>frozen pride</em>. When an Ice-Deed harms guest-right, the public loom takes the names and the draugr go hungry that week.</p>

  <hr>

  <h3>Etiquette &amp; Practicalities</h3>
  <ul>
    <li><strong>At thresholds:</strong> touch the lintel rune with two fingers, then speak your name. Names said softly freeze less.</li>
    <li><strong>Guest-right:</strong> accept bread, salt, and stew before business. Refusal is an insult; overeager bargaining is worse.</li>
    <li><strong>Boasts:</strong> speak deeds, not “will-dos.” If you must promise, tie a red thread to your sleeve until it is kept.</li>
    <li><strong>Weather:</strong> the north wind keeps a tally. Whistling at it adds one to the wrong column.</li>
    <li><strong>Prices:</strong> harbor stalls mark <em>storm rates</em>. Ask for the <em>calm measure</em> after the bell; most will oblige.</li>
  </ul>

  <hr>

  <h3>Calendar &amp; Belief</h3>
  <p>Skeldgard keeps the <strong>Weaving Nights</strong> at midwinter. Families bring ribbons of quarrels and gratitude; the city weaves them into the public cloth while skalds sing the <em>Wyrd Verses</em>-lines that bend fate toward mercy. In spring, the <strong>Ravenfast</strong> blesses messengers and road-guards. Temples to the <em>Æsir-Vanir Concord</em> stand shoulder to shoulder with shrines to river, wind, and hearth; the goðar (priests) share benches with runographers and Shield-Thing captains. Oath and craft drink from the same horn.</p>

  <hr>

  <h3>Traveler’s Note</h3>
  <p>Skeldgard does not care if you are important; it cares if you are <em>kept</em>. Keep your word, keep your boots by the door, keep a <?= htmlspecialchars(APP_CURRENCY_LONG_NAME) ?> coin for the ferry-boy, keep a story for the night-do these and the city will keep you. Fail, and you may feel the law like a cold hand on the back of your neck, guiding you politely to the loom.</p>
</section>