<?php require_login(); ?>
<h1>Orienthem</h1>
<!-- Image Map Generated by http://www.image-map.net/ 
<img src="images/harmontide-orienthem-smol.png" usemap="#image-map">

<map name="image-map">
    <area target="" alt="esl" title="esl" href="index.php?pg=esl" coords="167,0,129,11,75,44,35,51,1,137,7,169,32,170,45,243,147,199,169,183,201,148,217,73" shape="poly">
    <area target="" alt="hammurabia" title="hammurabia" href="index.php?pg=hammurabia" coords="216,86,170,191,46,248,27,173,2,169,0,276,72,362,94,327,210,282,366,255,357,168,329,153,263,83" shape="poly">
    <area target="" alt="cc" title="cc" href="index.php?pg=cc" coords="370,259,219,287,96,338,102,389,162,439,304,441,395,433,395,331,393,277" shape="poly">
</map>
-->

<!-- Image Map Generated by http://www.image-map.net/ -->
<img src="images/harmontide-orienthem.png" usemap="#image-map">

<map name="image-map">
    <area target="" alt="esl" title="esl" href="index.php?pg=esl" coords="606,259,567,409,488,489,489,520,437,522,409,552,398,575,376,597,338,588,324,617,268,617,232,622,206,643,174,648,163,667,136,695,116,675,128,597,128,566,95,538,96,503,77,459,30,475,4,431,2,359,54,349,32,281,42,233,80,185,111,143,158,143,217,127,261,109,314,94,353,93,372,35,415,23,436,23,454,1,490,9" shape="poly">
    <area target="" alt="hammurabia" title="hammurabia" href="index.php?pg=hammurabia" coords="610,258,571,413,502,483,479,528,439,525,414,556,386,597,344,594,327,624,255,625,203,647,152,685,125,698,110,662,120,598,111,572,84,496,69,469,4,488,16,766,207,1000,248,977,258,926,275,912,298,894,329,911,350,873,384,870,411,854,420,827,468,829,494,815,528,825,554,807,580,797,618,787,650,755,705,727,732,735,770,729,803,728,837,725,866,717,892,715,926,700,962,707,993,712,1016,714,1008,653,950,549,988,492,989,455,808,369,758,320,734,221" shape="poly">
    <area target="" alt="cc" title="cc" href="index.php?pg=cc" coords="1050,733,927,705,716,742,702,733,651,763,618,791,566,807,532,825,497,820,466,836,426,829,412,860,382,875,355,877,332,912,296,897,262,929,262,1016,315,1041,374,1081,401,1143,448,1223,482,1251,531,1257,592,1217,632,1228,636,1251,671,1255,696,1229,733,1209,775,1186,828,1181,862,1181,950,1150,1098,1191,1119,1135,1118,1065,1118,787" shape="poly">
</map>
  
  <div class="card glass">
    <h3>Crescent Caliphate</h3>
    <p class="muted">Sheikhs and Oil.</p>
    <a class="btn" href="?pg=cc">Explore</a>
  </div>
  
  <div class="card glass">
    <h3>Hammurabia</h3>
    <p class="muted">Zoroastrians.</p>
    <a class="btn" href="?pg=hammurabia">Explore</a>
  </div>
  
  <div class="card glass">
    <h3>Eretz-Shalem League</h3>
    <p class="muted">A state wrapped in controversy.</p>
    <a class="btn" href="?pg=esl">Explore</a>
  </div>
  
  <div class="card glass">
    <h3>Back to world map</h3>
    <a class="btn" href="?pg=map">Explore</a>
  </div>