<?php require_login(); ?>
<h1>Orienthem</h1>
<img src="images/harmontide-orienthem.png" alt="World map" usemap="#worldmap" class="world-map" />
<!-- Image Map Generated by http://www.image-map.net/ -->
<map name="worldmap">
</map>
  
  <div class="card glass">
    <h3>Crescent Caliphate</h3>
    <p class="muted">Sheikhs and Oil.</p>
    <a class="btn" href="?pg=cc">Explore</a>
  </div>
  
  <div class="card glass">
    <h3>Hammurabia</h3>
    <p class="muted">Zoroastrians.</p>
    <a class="btn" href="?pg=hammurabia">Explore</a>
  </div>
  
  <div class="card glass">
    <h3>Ersetz-Shalem League</h3>
    <p class="muted">A state wrapped in controversy.</p>
    <a class="btn" href="?pg=esl">Explore</a>
  </div>
  
  <div class="card glass">
    <h3>Back to world map</h3>
    <a class="btn" href="?pg=map">Explore</a>
  </div>