<?php require_login(); ?>
<h1>Rheinland - Rheingard</h1>
<section id="rheingard">
  <h2>Rheingard - <em>"Keep of the River Crown"</em></h2>
  
  <!-- Image Map Generated by http://www.image-map.net/ -->
<img src="images/harmontide-rheingard.webp" alt="World map" usemap="#worldmap" class="world-map" />
  <map name="image-map">
   </map>
  
  <div class="card glass">
    <h3>Paint Shack</h3>
    <p class="muted">Here you can paint your creatures from this region.</p>
    <a class="btn" href="?pg=rl_paint_shack">Explore</a>
  </div>
  
  <div class="card glass">
    <h3>Frankenondermeer</h3>
    <p class="muted">Koks, einen Haufen Koks.</p>
    <a class="btn" href="?pg=fom">Explore</a>
  </div>

  <div class="card glass">
    <h3>Back to Auronia</h3>
    <a class="btn" href="?pg=auronia">Back</a>
  </div>

  <p><strong>Rheingard</strong> rises where the broad river bends like a mailed arm around a hill. Half the city is stone and bell, the other half oak and guildmark: pointed roofs, steep lanes, bridge towers with iron grilles, and a market square that can hold a coronation at noon and a cattle fair by dusk. In Rheinland, law wears a tabard and carries a ledger; faith keeps company with craft; and the river decides who prospers by who minds the tides.</p>

  <p>The city keeps a memory of the old empires without pretending they were simple. You will find an <strong>Imperial Hall</strong> where electors once argued charters, a dozen guildhouses with saints painted on their beams, and cloisters where scribes debate angels and tariffs with equal heat. Ask about the marshlands downriver and people lower their voices: somewhere beyond the weirs lies <strong>Frankenondermeer</strong>, the low country of dikes and long memories. The river knows how to keep a secret and so do Rheingarders.</p>

  <hr>

  <h3>Districts and Landmarks</h3>
  <ul>
    <li><strong>Imperial Hall</strong> - Timbered and stone, bannered with old colors. The Diet met here in sterner days; now the city council reads accounts and swears new watch captains on a brass-bound Gospel of Law.</li>
    <li><strong>Cathedral March</strong> - The cathedral close and its processional way. Stone saints look down on merchants and poor alike; on feast days the nave fills with candle smoke and song.</li>
    <li><strong>Schanz Gate</strong> - Bastioned gate with a killing lane that now serves as a toll court. The tollbook is public at noon; cheating earns a bellring and a day hauling water.</li>
    <li><strong>Stonebridge Quarter</strong> - Houses built like laced boots along the great bridge, with mills turning under the arches. Bridge chapels bless travelers and keep ledgers of alms.</li>
    <li><strong>Guildring</strong> - Smiths, tanners, masons, vintners. Guild signs creak above doors; apprentices chalk pride on doorsteps after a good day at the forge.</li>
    <li><strong>Watchers Walk</strong> - The wall path. Belltowers speak across the roofs; a triple ring means fire, a steady roll means flood. Visitors are welcome to climb the south tower for the view if they mind their hat on the wind.</li>
    <li><strong>Scholars Cloister</strong> - A sober court of lime trees and disputation. Manuscript rooms, a disputation hall, and a modest press that smells of ink and ambition.</li>
  </ul>

  <hr>

  <h3>Food and Drink</h3>
  <p><strong>Eat like a guild guest.</strong> Pretzels the size of shields, onion tarts, roasts with dark gravy, river-fish with butter and dill, and red cabbage sweet as a hymn. Street braziers hiss with sausages; bakers dust rye loaves with malt. Order a <strong>Rheingard Freibrau</strong>, a copper-dark beer, or a pale wine from terraces upriver. If you are offered a monk cheese with caraway, take it and the advice that comes with it: never speak business until the second slice.</p>

  <p>Tourist truth: anything sold under cathedral eaves or on the bridge will cost 5 to 10 times more. Ask for the "guild rate" and be ready to name a craft you admire; the seller will likely lower the number and tell you where to find the good stuff off the square.</p>

  <hr>

  <h3>Order and Underlane</h3>
  <p>Peace is kept by the <strong>Belltower Ward</strong>, a watch that writes as much as it arrests. Their captains are called <em>Ledger Knights</em>; their swords are shorter than their ink lists. Fines prefer restitution and public work. Yet Rheingard is old, and old cities have shade. People murmur about the <strong>Tollring</strong>, a brotherhood that oils hinges and opens stubborn gates for a fee after curfew. They insist they are a courtesy, not a racket. The Ward disagrees, politely, and audits their alms to flood widows each spring.</p>

  <p>Downriver talk of <strong>Frankenondermeer</strong> comes wrapped in weather. Some say its dike-keepers can slow a flood with a prayer and a spade. Others say the river writes a different law there. Rheingard listens and keeps a second weir just in case.</p>

  <hr>

  <h3>Etiquette and Practicalities</h3>
  <ul>
    <li><strong>Bells:</strong> remove your hat at the first toll of the hour if you are on the square. Bless yourself or bow, as you prefer, when the Angelus rings; no one will force you, everyone will notice.</li>
    <li><strong>Titles:</strong> "Master" for a guild head, "Brother" or "Sister" for monastics, "Captain" for a Ward officer, "Canon" for a cathedral scholar. If you are unsure, say "Goodman" or "Goodwoman" and smile.</li>
    <li><strong>Market sense:</strong> weigh your coin in your palm and your words in your mouth. Haggling is expected on the outer stalls, frowned on inside the Guildring.</li>
    <li><strong>Curfew:</strong> the second bell after sunset. Lanterns out on the wall; fines for singing on rooftops unless you are very good or very far from the captain.</li>
    <li><strong>River:</strong> never mock a flood year in earshot of a waterman. River luck turns quick.</li>
  </ul>

  <hr>

  <h3>Calendar and Belief</h3>
  <p>Rheingard keeps the <strong>Saints March</strong> in late spring when guilds process with their tools and relics to bless bridges and mills. In harvest the <strong>Angel Fair</strong> fills the square with cloth, bells, books, and show-wrestling between tanners and coopers. On <strong>Night of the Watchfires</strong> the wall is lit end to end and the Ward reads the floodbook aloud. Pilgrims come year-round to the cathedral to ask angels for small mercies and big ones. The city answers with bread and a bench if the angels are busy.</p>

  <hr>

  <h3>Traveler's Note</h3>
  <p>Rheingard likes clear accounts: of coin, of promises, of stories. Bring a tale for the tavern and an apology for the bellringer if you climb the tower at the wrong hour. If a bargeman offers you a ride down toward the low country, pay double and ask what the river is thinking today. He will look at the sky, spit once, and tell you in a few careful words more than the council will write in a day.</p>
</section>
