<?php require_login(); ?>
<h1>Red Sun Commonwealth</h1>
<p>Redwind.</p>
<img src="images/harmontide-rsc.webp" alt="World map" usemap="#worldmap" class="world-map" />
<!-- Image Map Generated by http://www.image-map.net/ -->
<map name="worldmap">
</map>
  
  <div class="card glass">
    <h3>Paint Shack</h3>
    <p class="muted">Here you can paint your creatures from this region.</p>
    <a class="btn" href="?pg=rsc_paint_shack">Explore</a>
  </div>

  <div class="card glass">
    <h3>Wheel of Fortune</h3>
    <p class="muted">Spin once per day for a Red Sun prize (1,000 <?= htmlspecialchars(APP_CURRENCY_LONG_NAME) ?>).</p>
    <a class="btn" href="?pg=rsc-wof">Spin</a>
  </div>
  
  <div class="card glass">
    <h3>Back to Uluru</h3>
    <a class="btn" href="?pg=uluru">Explore</a>
  </div>

  <section id="redwind">
  <h2>Redwind - <em>"Harbor of the Red Sun"</em></h2>

  <p><strong>Redwind</strong> wraps a deep blue harbor where ferries draw white stitches across the water and glass towers catch the morning blaze. Surf breaks on pale beaches a short tram ride from the business core; cockatoos heckle joggers in bayside parks; and a salt breeze threads coffee lanes at dawn. In the Red Sun Commonwealth the city creed is simple: work bright, play safer, and leave no trace but footprints.</p>

  <p>Think modern harbor energy with coastal ease. Longboarders share paths with suits, galleries sit above boat sheds, and weekend markets spill under fig trees. The skyline has its icon too: a sail of white shells where music and theater pour into the night. Redwind talks fast, swims often, and tips its hat to the sun with factor 50 and a wide brim.</p>

  <hr>

  <h3>Districts and Landmarks</h3>
  <ul>
    <li><strong>Glass Harbor Quay</strong> - Ferries, buskers, and waterside cafes. Sunset turns tower windows copper; gulls audit chips with alarming rigor.</li>
    <li><strong>Sun Shell Hall</strong> - The sail-roofed arts house. Daytime tours, night shows, and a forecourt where dancers rehearse under sea breeze.</li>
    <li><strong>Redwind Arch</strong> - Steel span over the harbor. Walk the top with a clipped line or watch climbers from the shade with an ice pop.</li>
    <li><strong>Breaker Bay</strong> - Flagged surf beach with red-and-yellow posts, lifeguard towers, and a salt-stained kiosk that swears the best chips in town.</li>
    <li><strong>Bushline Reserve</strong> - Harbor headlands of eucalyptus and sandstone. Coastal tracks, dragonflies, and lookouts where the city feels very small.</li>
    <li><strong>Laneway Quarter</strong> - Espresso bars, small plates, murals, and late-night ramen. Order at the counter; learn to love the flat white.</li>
    <li><strong>Outback Exchange</strong> - Market halls for regional produce and crafts. Oysters on ice, mangoes by the crate, leather hats you will not wear later.</li>
    <li><strong>Ferry Triangle</strong> - Three wharves, six routes, zero patience for dawdlers. Tap on, tap off, and mind the gap at swell.</li>
  </ul>

  <hr>

  <h3>Food and Drink</h3>
  <p><strong>Eat the coast, sip the sun.</strong> Fish and chips with lemon, prawns on the barbie, grilled snapper with lime, meat pies with sauce, bush tomato salads, and fruit bowls that taste like holidays. Coffee culture is a civic sport: flat whites, long blacks, and iced lattes on hot mornings. Try a <strong>Harbor Plate</strong> at Glass Harbor (prawns, oysters, pickles) or a <strong>Breakers Roll</strong> at the beach kiosk (battered fish, slaw, chili). Craft beers live in converted sheds; mocktails sparkle with finger lime and mint.</p>

  <p>Tourist note: waterfront menus run 5 to 10 times dearer than laneways one block inland. Ask for the "local pour" and a half carafe of tap water; most servers will steer you to the better-value plate.</p>

  <hr>

  <h3>Order and Underlane</h3>
  <p>Peace is kept by the <strong>Harbor Watch</strong> on the quays and the <strong>Surf Wardens</strong> on the beaches. Fines for litter and glass on sand land fast; community service often means dawn beach sweeps. Redwind has a gentle shadow too: the <strong>Harbor Runners</strong>, a courier circle that moves last-minute gear between wharves and stages for a fee of cash and silence. They claim it is logistics, not a racket. Once a quarter, the Watch audits their charity jars on the ferry steps; in this town even a shadow shows a receipt.</p>

  <hr>

  <h3>Etiquette and Practicalities</h3>
  <ul>
    <li><strong>Sun sense:</strong> hat, shirt, sunscreen. Reapply. The UV does not care how tough you feel.</li>
    <li><strong>Swim flags:</strong> swim between red-and-yellow flags only. Rips are real. If in doubt, ask a Warden.</li>
    <li><strong>Ferries:</strong> queue single file, let passengers off, tap your card, keep bags clear of doors.</li>
    <li><strong>Bins:</strong> pack it in, bin it right. Recycling is color coded; fines for beach litter sting.</li>
    <li><strong>Wildlife:</strong> do not feed gulls, ibises, or the big lizard sunning by the path. They take fingers as tips.</li>
    <li><strong>Night:</strong> stay on lit paths, share rides from marked zones, hydrate between rounds.</li>
  </ul>

  <hr>

  <h3>Calendar and Belief</h3>
  <p>Redwind keeps a calendar of light and water. <strong>Harbor Lights</strong> launches a flotilla of lantern boats each spring. <strong>Surf Carnival</strong> pits clubs in rescue drills and sprints along Breaker Bay. <strong>Bush to Bay</strong> closes the headland road for runners at dawn. On <strong>Firefly Night</strong> the foreshore dims for an hour so kids can spot sparks in the trees and ships at anchor. City days publish budgets on quay boards and hand out saplings for balcony pots.</p>

  <hr>

  <h3>Traveler's Note</h3>
  <p>Redwind wants you salty, safe, and smiling. Ride a ferry at golden hour, walk a bush track when the cicadas start, tip the busker who makes a seagull dance, and take your rubbish with you. If you overpay on the quay, call it a view tax and try the laneways tomorrow. The harbor will pay you back with a breeze and a sky that looks hand polished.</p>
</section>
