<?php require_login(); ?>
<h1>Rodinian Tsardom</h1>
<img src="images/harmontide-rt.png" alt="World map" usemap="#worldmap" class="world-map" />
<!-- Image Map Generated by http://www.image-map.net/ -->
<map name="worldmap">
</map>
  
  <div class="card glass">
    <h3>Paint Shack</h3>
    <p class="muted">Here you can paint your creatures from this region.</p>
    <a class="btn" href="?pg=rt_paint_shack">Explore</a>
  </div>
  
  <div class="card glass">
    <h3>Back to Auronia</h3>
    <a class="btn" href="?pg=auronia">Explore</a>
  </div>

  <section id="velesgrad">
  <h2>Velesgrad - <em>"Between Root and Storm"</em></h2>

  <p><strong>Velesgrad</strong> sits where a wide river bends under birch and bell. Timber walls and red-brick towers ring a hill-citadel; onion-cap roofs shine like old copper when the sun grieves its way through winter cloud. In the Rodinian Tsardom this is a city of crossroads: forest paths meet caravan roads, river barges kiss frost-bitten piers, and oaths are sworn with one eye on the sky for thunder and one hand on the earth for luck.</p>

  <p>The name honors the old patron of cattle, craft, and hidden gold. Here people say, "Perun keeps the storm, Veles keeps the store." Priests bless the gates; woodcarvers hang house-totems; and every hearth keeps a crust for the domovoi, the stove spirit who minds the brooms and mutters about muddy boots.</p>

  <hr>

  <h3>Districts and Landmarks</h3>
  <ul>
    <li><strong>Kremlin Hill</strong> - Citadel of brick and oak. The Tsar's envoys read decrees in the yard; a bell-tower counts floods and fires. Touch the gate nail with two fingers and a quiet hope.</li>
    <li><strong>Veles Market</strong> - Arcades of felt, linen, icons, iron. Horse bells, barrel hoops, smoked fish, honey cakes. Swindlers fear the market scales; fines are paid in coin and public sweeping.</li>
    <li><strong>River Wharf</strong> - Low piers, high gossip. Bargemen trade news before bread. A small chapel to Saint of Fords shares a wall with the Guild of Ropes and Knots.</li>
    <li><strong>Birch Quarter</strong> - Lanes of carved izbas with warm stoves and cold porches. Window boards show bears, geese, and saints; cats own the thresholds.</li>
    <li><strong>Forge Street</strong> - Black hammers, red mouths of ovens. Smiths temper tools, not just swords; watch for sparks and the tea boy with the tin kettle.</li>
    <li><strong>Banya Gardens</strong> - Bathhouse courtyards steaming even in deep frost. Birch switches whisper advice; quarrels left at the door are said to melt into the snow.</li>
    <li><strong>Oak and Thunder</strong> - A twin shrine: oak for the sky, stone well for the under-earth. Couples circle the oak once for courage, twice for children, thrice for patience.</li>
  </ul>

  <hr>

  <h3>Food and Drink</h3>
  <p><strong>Eat for warmth, then for luck.</strong> Dumplings swim in broth; cabbage and mushrooms share a clay pot; river fish meet rye crust and butter. Street grills hiss with skewers; bakers plait poppy buns; pickles grin from jars like green moons. Wash it down with <strong>kvas</strong> from a barrel cart or honey <strong>medovukha</strong> when the wind sharpens its teeth. In deep winter the stall called <em>Little Stove</em> ladles buckwheat porridge and a blessing to anyone with cold hands.</p>

  <p>Tourist truth: anything beside the Kremlin gate or on the wharf runs 5 to 10 times dearer. Ask for the "craft rate" and praise a maker's handiwork; a good word for a good joint will usually shave the number and win you a story about an anvil.</p>

  <hr>

  <h3>Order and Underlane</h3>
  <p>The city watch is the <strong>River-Spear</strong>: cloaks the color of wet bark, spears for floods as well as thieves, and ledgers for every fine. They like restitution better than spectacle; a brawler may find himself hauling water to the banya and scrubbing the steam benches by lantern light.</p>

  <p>Shadows have jerseys too. People hint about the <strong>Market Wolves</strong>, a brotherhood with patient teeth and tidy books, who "guard" night wagons and collect "wolf silver" so that lamps stay lit. They call it courtesy, not a racket. The River-Spear disagrees, politely, and audits their winter alms to widows each thaw. Farther downriver, beyond the weirs, the low country of <strong>Frankenondermeer</strong> watches floods with its own math and its own laws; Velesgrad nods uphill and keeps a second bell in case the river chooses a lesson day.</p>

  <hr>

  <h3>Etiquette and Practicalities</h3>
  <ul>
    <li><strong>Thresholds:</strong> knock, step in with the right foot, greet the stove before the host. The domovoi hears manners first.</li>
    <li><strong>Bread and salt:</strong> accept with both hands and a nod. Refuse and you have started a price duel you will lose.</li>
    <li><strong>Names:</strong> titles sit heavy here. "Master," "Mistress," "Father," "Sister," or name and patronymic if you know it.</li>
    <li><strong>Banya rules:</strong> leave quarrels with your boots. Do not boast; steam remembers and repeats.</li>
    <li><strong>Winter sense:</strong> hats off for bells, not for frost. Mind the ice ribs on the wharf and the sled boys who drift like heroes.</li>
  </ul>

  <hr>

  <h3>Calendar and Belief</h3>
  <p>Velesgrad keeps the <strong>Week of Butter Fires</strong> before spring: pancakes in the square, sled races, and a straw effigy pulled laughing to the river. Summer brings <strong>Night of Fern Flame</strong>: wreaths on the water, leaps over small fires, and brave fools hunting a flower that never grows. In autumn, <strong>Ancestor Evenings</strong> invite names to the table with extra plates and quiet songs. The year turns with bells and doors, and every turn asks for a thank-you to something larger than a ledger.</p>

  <hr>

  <h3>Traveler's Note</h3>
  <p>Come with a tale, leave with a proverb. Tip the tea boy, praise a carving, and keep a crust for the house spirit. If a storm speaks your name from the oak, speak it back softly and offer a coin to the well. The city will keep you between root and storm if you keep your promises between tongue and teeth.</p>
</section>
