<?php require_login(); ?>
<h1>Saharene</h1>
<img src="images/harmontide-saharene.png" alt="World map" usemap="#worldmap" class="world-map" />
<!-- Image Map Generated by http://www.image-map.net/ -->
<map name="worldmap">
</map>
  
  <div class="card glass">
    <h3>Kemet</h3>
    <p class="muted">Sand as far as the Scarab can see.</p>
    <a class="btn" href="?pg=kemet">Explore</a>
  </div>
  
  <div class="card glass">
    <h3>Back to world map</h3>
    <a class="btn" href="?pg=map">Explore</a>
  </div>