<?php require_login(); ?>
<h1>Sila Council</h1>
<p>Qilaktuk.</p>
<img src="images/harmontide-sc.png" alt="World map" usemap="#worldmap" class="world-map" />
<!-- Image Map Generated by http://www.image-map.net/ -->
<map name="worldmap">
</map>
  
  <div class="card glass">
    <h3>Back to Tundria</h3>
    <a class="btn" href="?pg=tundria">Explore</a>
  </div>