<?php require_login(); ?>
<h1>Sila Council</h1>
<img src="images/harmontide-sc.webp" alt="World map" usemap="#worldmap" class="world-map" />
<!-- Image Map Generated by http://www.image-map.net/ -->
<map name="worldmap">
</map>
  
  <div class="card glass">
    <h3>Paint Shack</h3>
    <p class="muted">Here you can paint your creatures from this region.</p>
    <a class="btn" href="?pg=sc_paint_shack">Explore</a>
  </div>
  
  <div class="card glass">
    <h3>Back to Tundria</h3>
    <a class="btn" href="?pg=tundria">Explore</a>
  </div>

  <section id="qilaktuk">
  <h2>Qilaktuk - <em>"Under the Sky Dome"</em></h2>

  <p><strong>Qilaktuk</strong> sits on a gravel shore where sea ice grinds like old teeth and the wind writes fast in snow. Color-bright houses climb a low ridge around a sheltered cove; boardwalks stitch neighborhoods over permafrost; sled trails cut straight lines to the horizon. In the Sila Council, weather is teacher and law. Qilaktuk listens hard, plans long, and keeps the lamps filled.</p>

  <p>This is an Arctic town of craft, radio, and careful logistics. Snowmachines and qamutik sleds wait nose-out. VHF chatter fills the mornings. The weekly sealift ties the year together with crates of fuel, flour, guitar strings, and hockey tape. When the wind drops, you hear boots on boardwalk and the small bell of a door that does not want to let heat escape.</p>

  <hr>

  <h3>Districts and Landmarks</h3>
  <ul>
    <li><strong>Aurora Ridge</strong> - A wind-hardened rise with a heated shelter and an aurora camera. Best view in town when the sky starts to dance.</li>
    <li><strong>Harbor Pack</strong> - Ice-protected cove with a short pier. Skiffs in summer, komatik loads in winter. The tide board here is everybody's favorite rumor mill.</li>
    <li><strong>Council House</strong> - Community hall and radio room. Meetings, youth nights, craft markets, weather briefings, and the big coffee pot.</li>
    <li><strong>Qulliq Square</strong> - Plaza around the memorial oil lamp. Elders light it for first ice, first thaw, and remembrance days. Benches face out to the sea.</li>
    <li><strong>Outfitter Row</strong> - Sled runners, rope, fuel, camp stoves, parkas, and borrowed wisdom. The wall map is patched with tape and stories.</li>
    <li><strong>Ice Road Gate</strong> - Start of the flagged winter road. Check the board for conditions and do not move a flag unless you want a very public lecture.</li>
    <li><strong>Inuksuk Point</strong> - Stone markers stand like careful people on the headland. Good place to watch whitecaps decide if they mean it.</li>
    <li><strong>Clinic and Warm Line</strong> - Small but stubborn. Nurses run checks, counselors run a kettle, and the sat link keeps the wider world close enough to help.</li>
  </ul>

  <hr>

  <h3>Food and Warmth</h3>
  <p><strong>Eat for heat, then for stories.</strong> Arctic char grilled or dried, muskox stew, caribou with juniper, seal soup, and bannock from cast iron. In berry time there are cloudberries and blueberries by the mug. Winter drinks run hot and sweet: tea with condensed milk, cocoa thick as a mitten, and coffee that could kick a snowmachine awake.</p>

  <p>Tourist note: anything beside the pier or at Aurora Ridge runs 5 to 10 times town price. Ask for the "neighbor measure" and point at the notice board of community rides; most vendors will smile and drop the number to what a deckhand would pay.</p>

  <hr>

  <h3>Order and Underlane</h3>
  <p>Peace is kept by the <strong>Ice Ward</strong>: a small watch with radios, reflective stripes, and a habit of carrying extra mitts for kids. Fines lean toward work everyone benefits from: shoveling boardwalks, hauling water, checking flags. Qilaktuk also has a quiet network of fixers called the <strong>Night Trail</strong> who arrange after-hours fuel drops and airport runs when weather squeezes schedules. They call it kindness with a clipboard, not a racket. Each month the Council posts Night Trail donations on the hall wall; in this town even a shadow shows a receipt.</p>

  <hr>

  <h3>Etiquette and Practicalities</h3>
  <ul>
    <li><strong>Doors:</strong> knock, then wait. Shake off snow in the porch. Close what you open, every time.</li>
    <li><strong>Elders:</strong> offer the first seat, the first cup, and the last word. If an Elder says "not today," it means not today.</li>
    <li><strong>Photos:</strong> ask people first. Never shoot a hunt without permission. Do not chase wildlife for a picture.</li>
    <li><strong>Trails:</strong> do not move flags, do not block sleds, keep your dog on a line near houses. On ice, follow tracks or stay home.</li>
    <li><strong>Cold sense:</strong> metal is hungry and wind has opinions. Dress for ten degrees worse than you think. Batteries lie; carry a spare.</li>
    <li><strong>Greetings:</strong> a nod and a "hi" or "qujanaq" goes a long way. The weather is always an acceptable first topic.</li>
  </ul>

  <hr>

  <h3>Calendar and Belief</h3>
  <p>Qilaktuk keeps a calendar of sky and ice. <strong>First Ice</strong> lights the qulliq and blesses the sleds. <strong>Sun Return</strong> brings a noon feast outside no matter the chill. <strong>Longest Day</strong> runs games on the gravel until midnight sun calls it. In late summer <strong>Berry Time</strong> sends families out with buckets and stories. In winter, the town holds <strong>Night Lights</strong> when the aurora is strong: generators quiet down, kids lie on caribou skins, and everyone tries to hear the sky crackle.</p>

  <hr>

  <h3>Traveler's Note</h3>
  <p>Qilaktuk is small on purpose and large where it counts. Walk with the wind, not against advice. Pay for the ride you take and the heat you borrow. If you overp
