<?php require_login(); ?>
<h1>Sapa Inti Empire</h1>
<p>Intirumi.</p>
<img src="images/harmontide-sie.png" alt="World map" usemap="#worldmap" class="world-map" />
<!-- Image Map Generated by http://www.image-map.net/ -->
<map name="worldmap">
</map>
  
  <div class="card glass">
    <h3>Paint Shack</h3>
    <p class="muted">Here you can paint your creatures from this region.</p>
    <a class="btn" href="?pg=sie_paint_shack">Explore</a>
  </div>
  
  <div class="card glass">
    <h3>Back to Gulfbelt</h3>
    <a class="btn" href="?pg=gulfbelt">Explore</a>
  </div>