<?php require_login(); ?>
<h1>Sapa Inti Empire</h1>
<img src="images/harmontide-sie.webp" alt="World map" usemap="#worldmap" class="world-map" />
<!-- Image Map Generated by http://www.image-map.net/ -->
<map name="worldmap">
</map>
  
  <div class="card glass">
    <h3>Paint Shack</h3>
    <p class="muted">Here you can paint your creatures from this region.</p>
    <a class="btn" href="?pg=sie_paint_shack">Explore</a>
  </div>
  
  <div class="card glass">
    <h3>Back to Gulfbelt</h3>
    <a class="btn" href="?pg=gulfbelt">Explore</a>
  </div>

  <section id="intirumi">
  <h2>Intirumi - <em>"Sun-Stone City"</em></h2>

  <p><strong>Intirumi</strong> sits high in the thin blue air where terraced mountains step like stairs to the sky. Cyclopean walls fit stone to stone so tight a knife finds no path; trapezoid doors lean inward like shoulders taking weight; water sings in carved channels day and night. In the Sapa Inti Empire, reciprocity is law and the sun is calendar; in Intirumi both are written in granite and light.</p>

  <p>This is a capital of terraces, roads, and quiet precision. Runners trade shell horns on way stations; stone-cutters polish joints by hand; farmers climb with baskets of quinoa and potatoes; priests read noon-shadow on a golden pin to set work and feast. Visitors learn fast: climb slow, drink water, step wide of the alpacas, and follow the keepers when they sweep the steps at dusk.</p>

  <hr>

  <h3>Districts and Landmarks</h3>
  <ul>
    <li><strong>Sun Temple Quarter</strong> - Courtyards of cut stone and gold plates. At noon a thin line of light crosses a niche to mark the day. Offer a yellow flower; keep your voice small.</li>
    <li><strong>Four Roads Gate</strong> - Where the royal road divides toward the four quarters of the realm. Runners rest in shade niches; tribute tallies are knotted in colored cords.</li>
    <li><strong>Water Stair</strong> - A cascade of stone basins stepping down a slope. Women wash maize, children race leaf boats, and a water steward logs flow on a carved board.</li>
    <li><strong>Terrace Crown</strong> - Green combs of earth held by stone. Maize near the sun, potatoes below, flowers everywhere for the temples. Llamas graze the edges like tidy clouds.</li>
    <li><strong>Stone School</strong> - Scribes with khipu cords teach counts and records; builders teach plumb and angle with string and sun. A hall of maps shows roads like veins.</li>
    <li><strong>Market of the Quarters</strong> - Arcades where each province sets out cloth, gourds, salt, fish, coca, copper tools. Inspectors check measures with calm eyes and good scales.</li>
    <li><strong>Sky Path</strong> - A high ledge walk with low walls and a long view. Bells ring if fog comes in fast; guides tie ropes and wait without hurry.</li>
  </ul>

  <hr>

  <h3>Food and Drink</h3>
  <p><strong>Eat the terraces and the herds.</strong> Quinoa with herbs, potato stews thick as blankets, river trout with kola mint, roasted cuy, alpaca skewers with aji, tamales steamed in leaves. Street cups pour mate de coca for the climb and chicha morada sweet and cold for the afternoon. Try the <strong>Sun Plate</strong> near the temple steps (quinoa, cheese, peppers, and a gold-sided potato you will talk about later) or a <strong>Runner Bowl</strong> at the Four Roads Gate (hot broth, maize, greens, and a second wind).</p>

  <p>Tourist note: stalls beside the Sun Temple and the Sky Path price 5 to 10 times the lane rate. Ask for the "ayni measure" and mention the terrace you helped weed; most sellers will smile and lower the number to what a porter pays.</p>

  <hr>

  <h3>Order and Underlane</h3>
  <p>Peace is kept by the <strong>Sun Ward</strong> on the plazas and the <strong>Road Keepers</strong> on the ledges. Fines lean toward labor that serves all: mending stairs, hauling water, setting stones true. Intirumi also keeps a shaded courtesy. People whisper about the <strong>Nightrunners</strong>, a courier circle that moves sealed bundles and late travelers between gates after curfew for a fee of coca and silence. They call it flow, not a racket. Each moon the Ward opens their charity baskets in public at the Stone School; in this city even a shadow shows a receipt.</p>

  <hr>

  <h3>Etiquette and Practicalities</h3>
  <ul>
    <li><strong>Altitude:</strong> climb slowly, drink water, take coca tea, and let pride walk behind you. Headaches bow to patience and shade.</li>
    <li><strong>Temples:</strong> hats off, shoulders covered. Do not touch gold plates or carved niches. Step aside for processions without being asked.</li>
    <li><strong>Terraces:</strong> do not cut switchbacks or step on stone lips. If a farmer offers a hoe, take two rows and leave them straighter than you found them.</li>
    <li><strong>Markets:</strong> greet, praise the cloth or the cut, then bargain. If a seller knots a bright cord to your purchase, it is a blessing; keep it on until you get home.</li>
    <li><strong>Roads and ledges:</strong> keep right, give way to llamas and porters. When a shell horn sounds, get your elbows in and your feet sure.</li>
    <li><strong>Night:</strong> curfew at second bell. Lanterns dim; stars do not. Hire a licensed guide if you must cross districts.</li>
  </ul>

  <hr>

  <h3>Calendar and Belief</h3>
  <p>Intirumi keeps the <strong>Sun-Standing</strong> at solstice when the noon pin writes the tightest line and dancers turn like compass points. At <strong>Planting Promise</strong> families trade seed and labor for the year and priests bless the first terrace rows. <strong>Return of Rains</strong> brings flute parades and water poured on stone steps. At <strong>Festival of Roads</strong> runners carry torches along the ledges so the city looks like a necklace from the valley. The year ends with the <strong>Weighing of Work</strong>, when each district reads its gifts and asks neighbors for what balance still lacks.</p>

  <hr>

  <h3>Traveler's Note</h3>
  <p>Intirumi keeps its voice low and its stones true. Walk kindly, pay your share, help where a hand will do, and keep a flower for the temple stairs. If you overpay with the sun in your eyes, call it gratitude for walls that do not fall and roads that go everywhere. The mountain will remember your steps.</p>
</section>
