<?php require_login(); ?>
<h1>Spice Route League</h1>
<img src="images/harmontide-srl.webp" alt="World map" usemap="#worldmap" class="world-map" />
<!-- Image Map Generated by http://www.image-map.net/ -->
<map name="worldmap">
</map>
  
  <div class="card glass">
    <h3>Paint Shack</h3>
    <p class="muted">Here you can paint your creatures from this region.</p>
    <a class="btn" href="?pg=srl_paint_shack">Explore</a>
  </div>

  <div class="card glass">
    <h3>Back to Moana Crown</h3>
    <a class="btn" href="?pg=moana_crown">Back</a>
  </div>

  <section id="navakai">
  <h2>Navakai - <em>"Harbor of the Wayfinders"</em></h2>

  <p><strong>Navakai</strong> curls around a clear lagoon where reef and deep water shake hands. Outrigger canoes rest on timber cradles, breadfruit trees shade sandy lanes, and meeting houses lift open rafters to trade wind and song. In the Spice Route League, the sea is road and teacher; in Navakai the stars are street signs and the tide is the town clock.</p>

  <p>The city moves by rhythm: dawn launches, noon nets, dusk drums. Navigators practice on a sand star compass, elders plait pandanus and sennit, and children race along the seawall with kites cut like frigate birds. Visitors learn fast: greet first, step off woven mats with clean feet, and ask before you touch anything carved or corded.</p>

  <hr>

  <h3>Districts and Landmarks</h3>
  <ul>
    <li><strong>Star Compass Green</strong> - A packed-sand circle marked with swell lines and star houses. Lessons at dawn; at night the whole green tilts its face to the sky.</li>
    <li><strong>Marae Terrace</strong> - Sacred courtyard and community green. Ceremonies, welcomes, and quiet counsel under the eyes of carved ancestors. Shoes and loud voices stay outside.</li>
    <li><strong>Lagoon Quay</strong> - Canoe slips, fish racks, shell traders, net menders. The tide board here is law; the bell warns when the reef path turns tricky.</li>
    <li><strong>Fale Longhouse</strong> - Open-sided hall of posts and lashings. Food, talk, craft markets, and the conch that calls meetings and dance practice.</li>
    <li><strong>Tapa Walk</strong> - Cloth makers, wood carvers, shell inlay, and nose flute shops. Dye bowls sit like small moons, and every doorway smells of oil and smoke.</li>
    <li><strong>Reef Gate</strong> - A gap in the coral marked by pale stakes. The pilot boat sits here; cross without a pilot and the whole quay will fold arms and watch you learn.</li>
    <li><strong>Palm Ridge</strong> - Low rise with lookouts over lagoon and ocean. Best place for first-light and last-light. Bring water, leave thanks.</li>
  </ul>

  <hr>

  <h3>Food and Drink</h3>
  <p><strong>Eat what the reef and grove give.</strong> Reef fish steamed in leaves, octopus with coconut cream, taro and breadfruit from the earth oven, mango and lime salads, grilled bananas with palm syrup. Street cups hold coconut water and hibiscus tea; evenings pour kava in half shells with slow talk and long listening. Try the <strong>Navigator Bowl</strong> at Lagoon Quay (fish, taro, greens, coconut) or the <strong>Reef Fire Plate</strong> from the earth oven by the longhouse.</p>

  <p>Tourist note: stalls on the quay and beside the Marae Terrace run 5 to 10 times lane price. Ask for the "neighbor measure" and point to the water fund barrel; most sellers will smile and shave the number.</p>

  <hr>

  <h3>Order and Underlane</h3>
  <p>Peace is kept by the <strong>Lagoon Ward</strong>, a small watch with conch horns, ledgers, and more patience than rope. Fines become reef work, quay sweeps, or night watch shifts. Navakai also keeps a quiet network called the <strong>Moon Runners</strong> who ferry late cargo and guests after curfew for a fee of shells and silence. They call it courtesy, not a racket. Each moon the Ward opens their donation baskets in public at the Fale; in this town even a shadow shows a receipt.</p>

  <hr>

  <h3>Etiquette and Practicalities</h3>
  <ul>
    <li><strong>Greetings:</strong> smile, a light touch at the shoulder, and a "talofa" or "aloha" style hello. Follow the host s lead.</li>
    <li><strong>Marae and mats:</strong> ask before entering, remove shoes, do not step over people or food, and never plant feet on woven mats.</li>
    <li><strong>Canoes:</strong> do not touch hulls, lashings, or paddles without permission. A canoe is family.</li>
    <li><strong>Reef sense:</strong> mind the tide and your toes. Shuffle to warn rays, do not break coral, and leave shells for the ocean to keep.</li>
    <li><strong>Curfew:</strong> drum at second star rise. Lantern guides are licensed; hire one or stay in the lit lanes.</li>
    <li><strong>Gifts:</strong> bring fruit, a song, or a strong back. Work shared is work halved.</li>
  </ul>

  <hr>

  <h3>Calendar and Belief</h3>
  <p>Navakai keeps the <strong>Wayfinder Nights</strong> when the Pleiades rise and the star compass fills with footsteps and stories. <strong>First Fruits</strong> thanks grove and reef with shared plates in the longhouse. <strong>Outrigger Days</strong> bring canoe races along the reef and drumlines on the quay. In storm season the town holds <strong>Quiet Sea</strong>: boats stay in, nets get mended, and elders tell routes you cannot see on any chart.</p>

  <hr>

  <h3>Traveler s Note</h3>
  <p>Walk soft on sand and loud in praise. Ask, offer, and listen more than you speak. If you overpay at the quay, call it a tide tax and learn a knot from the seller. The lagoon will remember your courtesy when the pilot boat meets you at the Reef Gate.</p>
</section>
