<?php require_login(); ?>
<h1>Sovereign Tribes of the Ancestral Plains</h1>
<img src="images/harmontide-stap.webp" alt="World map" usemap="#worldmap" class="world-map" />
<!-- Image Map Generated by http://www.image-map.net/ -->
<map name="worldmap">
</map>
  
  <div class="card glass">
    <h3>Paint Shack</h3>
    <p class="muted">Here you can paint your Yara Nations creatures.</p>
    <a class="btn" href="?pg=stap_paint_shack">Explore</a>
  </div>
  
  <div class="card glass">
    <h3>Back to Borealia</h3>
    <a class="btn" href="?pg=borealia">Explore</a>
  </div>

  <section id="turtlestar">
  <h2>Turtlestar - <em>"Council at the Sky Road"</em></h2>

  <p><strong>Turtlestar</strong> stands where tall grass meets two patient rivers, a confederation capital set in rings instead of blocks. Wind moves the prairie like water; bison trails cross old earth mounds; and at night the sky falls close enough to count. In the Sovereign Tribes of the Ancestral Plains, roads follow stars before they follow stakes. Turtlestar keeps that memory in how it listens, feeds guests, and votes by circle rather than by shout.</p>

  <p>The city gathers many nations and lifeways. Timber council houses and canvas lodges share the same wind; beadwork and quillwork hang beside bronze tools and solar panels; horse lines stand near bike racks. The central fire is tended by rota, and visiting delegations plant their banners in the ground instead of on walls. You learn quickly: speak after you have listened; step lightly on grass that feeds more than you; ask before you point a lens at living ceremony.</p>

  <hr>

  <h3>Districts and Landmarks</h3>
  <ul>
    <li><strong>Circle of Fires</strong> - The council green. Rings for elders, speakers, and guests; a shared fire at the center. Decisions are carried by consensus, not by hurry.</li>
    <li><strong>Star Walk</strong> - A path laid out to mirror a northern constellation. Story poles mark seasons and routes; guides walk the tale at dusk.</li>
    <li><strong>River Bend Market</strong> - Stalls of wild rice, corn, beans, squash, bison jerky, berries, crafts, drums, flutes, and books. Prices are posted plain and change with the wind, not with the face.</li>
    <li><strong>Winter Count Lodge</strong> - A hall of painted hides and canvases recording years by shared memory. Youths learn to keep a count without losing a laugh.</li>
    <li><strong>Bison Gate</strong> - Timber gate and overlook toward the managed herd. Rangers speak about burns, grass, and how not to be very stupid with a very large animal.</li>
    <li><strong>Sky House</strong> - An open-roof observatory with windbreak walls. Star lessons, eclipse watches, and the quiet joy of a clear night.</li>
    <li><strong>River Ford</strong> - Old crossing kept shallow with stone ribs. A place to sit, cool your feet, and remember that water is elder to the road.</li>
    <li><strong>Craft Rings</strong> - Bead, quill, leather, clay, wood, and metal. Makers sit facing the door and the sun, and there is always a spare stool for a lesson if you mind your hands.</li>
  </ul>

  <hr>

  <h3>Food and Drink</h3>
  <p><strong>Eat what the prairie and river give.</strong> Bison stew, corn and bean succotash, wild rice with cranberries, frybread and honey, squash roasted in wedges, trout with sage, chokecherry pudding. Coffee is strong and shared; cedar and mint teas cool a hot day. Try the <strong>Trail Bowl</strong> at River Bend (bison, beans, corn, greens) or the <strong>Sky Cakes</strong> at dawn (blue corn griddle cakes with berry sauce).</p>

  <p>Tourist note: anything right on the Circle of Fires or the Star Walk runs 5 to 10 times the lane rate. Ask for the "neighbor measure" and point at the youth fund box; most vendors will smile and set the number to what a drummer pays.</p>

  <hr>

  <h3>Order and Underlane</h3>
  <p>Peace is kept by the <strong>Trail Wardens</strong>, a cross-tribal watch in red sashes. Their first tools are a whistle and a water jug; their second are radios. Fines tend to be service: picking trash from the river, cutting invasive brush, tending fires at the council green. Turtlestar also keeps a quiet network called the <strong>Night Riders</strong> who move elders, medicine, and late guests after curfew for a fee of gas and silence. They call it kin duty, not a racket. Each month the council posts Night Rider donations and routes on a board by the clinic; in this town even a shadow shows a receipt.</p>

  <hr>

  <h3>Etiquette and Practicalities</h3>
  <ul>
    <li><strong>Greetings:</strong> hello first, business second. A handshake may be light; follow the lead you are given.</li>
    <li><strong>Circles:</strong> do not cut across a circle while people speak; walk the outside. Wait to be invited to the inner ring.</li>
    <li><strong>Ceremony:</strong> ask before photos or recording. If told "not today," believe it, thank them, and put the lens away.</li>
    <li><strong>Food:</strong> elders and kids first in line. If you take the last piece, you also take the job of slicing more.</li>
    <li><strong>Land:</strong> stay on marked paths near nests and burn plots. Do not pick plants without a ranger or a teacher beside you.</li>
    <li><strong>Horses and bison:</strong> admire with eyes, not hands. A ranger will tell you the safe fence; believe the fence.</li>
    <li><strong>Night:</strong> curfew is gentle but real. Lanterns dim; stars take over. Use lit lanes or hire a Night Rider.</li>
  </ul>

  <hr>

  <h3>Calendar and Belief</h3>
  <p>Turtlestar keeps a calendar by sky and grass. <strong>First Thunder</strong> opens planting with songs and coffee at dawn. <strong>Berries In</strong> is a sweet month of baskets and stained smiles. <strong>Long Sun</strong> brings dances, horse races, and river games. <strong>First Frost</strong> moves the city inward to story nights and winter counts. The year closes with <strong>Stars Return</strong> when families bring warm food to the Sky House and point out where their names sit among the lights.</p>

  <hr>

  <h3>Traveler s Note</h3>
  <p>Turtlestar will treat you like a neighbor if you act like one. Listen twice, step softly, pack out trash that is not yours, and keep a cup ready for shared coffee. If you overpay on the Star Walk, call it a sky tax and drop a few bills in the youth fund. The prairie remembers good footprints.</p>
</section>
