<?php require_login(); ?>
<h1>Sovereign Tribes of the Ancestral Plains</h1>
<p>Turtlestar.</p>
<img src="images/harmontide-stap.png" alt="World map" usemap="#worldmap" class="world-map" />
<!-- Image Map Generated by http://www.image-map.net/ -->
<map name="worldmap">
</map>
  
  <div class="card glass">
    <h3>Paint Shack</h3>
    <p class="muted">Here you can paint your Yara Nations creatures.</p>
    <a class="btn" href="?pg=stap_paint_shack">Explore</a>
  </div>
  
  <div class="card glass">
    <h3>Back to Borealia</h3>
    <a class="btn" href="?pg=borealia">Explore</a>
  </div>