<?php require_login(); ?>
<h1>Tundria</h1>
<img src="images/harmontide-tundria.webp" alt="World map" usemap="#worldmap" class="world-map" />
<!-- Image Map Generated by http://www.image-map.net/ -->
<map name="worldmap">
</map>
  
  <div class="card glass">
    <h3>Sila Council</h3>
    <p class="muted">The only country on this continent.</p>
    <a class="btn" href="?pg=sc">Explore</a>
  </div>
  
  <div class="card glass">
    <h3>Back to world map</h3>
    <a class="btn" href="?pg=map">Explore</a>
  </div>