<?php require_login(); ?>
<h1>Uluru</h1>
<img src="images/harmontide-uluru.webp" alt="World map" usemap="#worldmap" class="world-map" />
<!-- Image Map Generated by http://www.image-map.net/ -->
<map name="worldmap">
</map>
  
  <div class="card glass">
    <h3>Red Sun Commonwealth</h3>
    <p class="muted">Someone comes from a land down under.</p>
    <a class="btn" href="?pg=rsc">Explore</a>
  </div>
  
  <div class="card glass">
    <h3>Yara Nations</h3>
    <p class="muted">Ancient nation of these lands.</p>
    <a class="btn" href="?pg=yn">Explore</a>
  </div>
  
  <div class="card glass">
    <h3>Back to world map</h3>
    <a class="btn" href="?pg=map">Explore</a>
  </div>