<?php require_login(); ?>
<h1>United free Republic of Borealia</h1>
<img src="images/harmontide-urb.webp" alt="World map" usemap="#worldmap" class="world-map" />
<!-- Image Map Generated by http://www.image-map.net/ -->
<map name="worldmap">
</map>
  
  <div class="card glass">
    <h3>Meridian Arc Paint Shack</h3>
    <p class="muted">Here you can paint your URB creatures.</p>
    <a class="btn" href="?pg=urb_paint_shack">Explore</a>
  </div>
  
  <div class="card glass">
    <h3>Back to Borealia</h3>
    <a class="btn" href="?pg=borealia">Explore</a>
  </div>

  <section id="meridian-arc">
  <h2>Meridian Arc - <em>"City on the Line"</em></h2>

  <p><strong>Meridian Arc</strong> sits on a broad river where rail, freeway, and flight paths cross like compass marks. Glass and brick share the skyline; street trees run in straight rows; a ring of neighborhoods feeds a downtown that glows after dark. In the United Free Republic of Borealia, the civic pitch is simple: show up, vote often, coach youth sports, and keep the crosswalks painted.</p>

  <p>The vibe is classic American city with a fresh coat. Unions and start-ups share blocks, diners and ramen bars share corners, and murals argue with billboards in good humor. On game nights the riverfront thrums; on Saturday mornings the farmers market is a traffic pattern of strollers, dogs, and iced coffee. Bring good shoes and a patient horn hand.</p>

  <hr>

  <h3>Districts and Landmarks</h3>
  <ul>
    <li><strong>Capitol Row</strong> - Statehouse dome, courts, and museums. Lawns for rallies, steps for selfies, food trucks at lunch. Security is visible and polite.</li>
    <li><strong>Arcworks</strong> - Brick warehouses turned studios, tech lofts, and brew halls. String lights, bikes, dogs, and a hundred laptops glowing behind plants.</li>
    <li><strong>Rivermile</strong> - Riverwalk, ballpark, concert shell, and the big fountain. Joggers at dawn, fireworks on holidays, jazz on Sundays.</li>
    <li><strong>Old Grid</strong> - Historic blocks of brownstone and stoops. Porch flags, tiny libraries, and the candy store that somehow made it to this century.</li>
    <li><strong>Northside Markets</strong> - Food halls, produce sheds, and flea stalls. Best tacos, best pierogi, best argument about both.</li>
    <li><strong>Meridian Exchange</strong> - Grand station under a steel vault. Trains, light rail, bus concourse, and a coffee stand that knows your order by your shoes.</li>
    <li><strong>Commons Park</strong> - Big green with a carousel, dog run, and summer movies. Fireflies in June if the kids hold still long enough.</li>
    <li><strong>Skyline Bridge</strong> - Signature span with a pedestrian deck and lookouts. Sunset here is a local religion; bring a jacket for the wind.</li>
  </ul>

  <hr>

  <h3>Food and Drink</h3>
  <p><strong>Eat neighborhood by neighborhood.</strong> Diners pour bottomless coffee with stacks of pancakes. Food trucks sling birria and bulgogi. Delis stack impossible sandwiches. Riverfront grills do salmon and sweet corn in season. Breweries pour flights; cafes pull serious espresso; soda fountains still stir a cherry phosphate if you ask.</p>

  <p>Order a <strong>Meridian Melt</strong> at a lunch counter (patty, onions, rye), a <strong>River Bowl</strong> at Rivermile (greens, grains, smoked fish), and a <strong>Commons Cone</strong> after the carousel. Tourist note: anything right on the riverwalk or inside the ballpark runs 5 to 10 times the neighborhood rate. Ask for the "local pour" and the server will usually point you one block back for the same plate cheaper.</p>

  <hr>

  <h3>Order and Underlane</h3>
  <p>Peace is kept by the <strong>Civic Department</strong> with patrol bikes, cruisers, and lots of body cams. Fines lean toward service: park cleanups, mural touch-ups, and crosswalk duty. Health teams work festivals with water, info cards, and ride vouchers.</p>

  <p>There is a quiet courier loop called the <strong>Arc Line</strong> that moves last-minute gear and documents between venues after hours for a fee of cash and silence. They call it logistics, not a racket. Once a quarter, the city posts their donation receipts to youth leagues and library programs; in Meridian Arc even a shadow shows a spreadsheet.</p>

  <hr>

  <h3>Etiquette and Practicalities</h3>
  <ul>
    <li><strong>Transit:</strong> tap cards on trains and buses, stand right on escalators, let riders off first. Bikes yield to feet on the riverwalk.</li>
    <li><strong>Street sense:</strong> eyes up at crosswalks, bags zipped, headphones at one ear after dark. Use lit routes and posted rideshares.</li>
    <li><strong>Sports nights:</strong> book parking or take rail. Learn the chant or at least clap on the beat.</li>
    <li><strong>Markets:</strong> greet first, sample second, pay the posted price. Cash helps small vendors; card taps fine everywhere else.</li>
    <li><strong>Parks:</strong> leashes, litter bags, no glass on the grass. Grills are first come; share the heat if asked nicely.</li>
    <li><strong>Weather:</strong> summer storms hit fast, winter bites. Layer up; the bridge always runs colder than the street.</li>
  </ul>

  <hr>

  <h3>Calendar and Belief</h3>
  <p>Meridian Arc loves a schedule. <strong>Opening Day</strong> for baseball turns Rivermile into a parade. <strong>Arc Fest</strong> fills Arcworks with art, food, and night markets. <strong>River Lights</strong> brings boats and fireworks on the fourth. <strong>Harvest Weekend</strong> stacks pumpkins on the Commons, and <strong>First Snow</strong> flips the switch on a mile of holiday lights down Old Grid. City days post budgets on the station board and hand out tree saplings for stoops and balconies.</p>

  <hr>

  <h3>Traveler s Note</h3>
  <p>Meridian Arc wants you caffeinated, oriented, and five minutes early. Walk the river at golden hour, take the train once for fun and once because it is faster, tip the busker who sounds like a record, and carry a water bottle. If you overpay on the riverwalk, call it a view tax and loop back through the lanes tomorrow. The city will repay you with a shortcut, a sandwich, and a seat for the sunset.</p>
</section>
