<?php require_login(); ?>
<h1>United free Republic of Borealia</h1>
<p>Meridian Arc.</p>
<img src="images/harmontide-urb.png" alt="World map" usemap="#worldmap" class="world-map" />
<!-- Image Map Generated by http://www.image-map.net/ -->
<map name="worldmap">
</map>
  
  <div class="card glass">
    <h3>Back to Borealia</h3>
    <a class="btn" href="?pg=borealia">Explore</a>
  </div>