<?php require_login(); ?>
<h1>Verdania</h1>
<img src="images/harmontide-verdania.png" alt="World map" usemap="#worldmap" class="world-map" />
<!-- Image Map Generated by http://www.image-map.net/ -->
<map name="worldmap">
</map>
  
  <div class="card glass">
    <h3>Gran Columbia</h3>
    <p class="muted">Cocaine.</p>
    <a class="btn" href="?pg=gc">Explore</a>
  </div>
  
  <div class="card glass">
    <h3>Sapa Inti Empire</h3>
    <p class="muted">Land of the gaucho.</p>
    <a class="btn" href="?pg=sie">Explore</a>
  </div>
  
  <div class="card glass">
    <h3>Back to world map</h3>
    <a class="btn" href="?pg=map">Explore</a>
  </div>