<?php require_login(); ?>
<h1>Xochimex</h1>
<p>Xochival.</p>
<img src="images/harmontide-xochimex.png" alt="World map" usemap="#worldmap" class="world-map" />
<!-- Image Map Generated by http://www.image-map.net/ -->
<map name="worldmap">
</map>
  
  <div class="card glass">
    <h3>Back to Gulfbelt</h3>
    <a class="btn" href="?pg=gulfbelt">Explore</a>
  </div>