<?php require_login(); ?>
<h1>Xochival</h1>
<img src="images/harmontide-xochimex.webp" alt="World map" usemap="#worldmap" class="world-map" />
<!-- Image Map Generated by http://www.image-map.net/ -->
<map name="worldmap">
</map>
  
  <div class="card glass">
    <h3>Paint Shack</h3>
    <p class="muted">Here you can paint your Xochimex creatures.</p>
    <a class="btn" href="?pg=xm_paint_shack">Explore</a>
  </div>
  
  <div class="card glass">
    <h3>Back to Gulfbelt</h3>
    <a class="btn" href="?pg=gulfbelt">Explore</a>
  </div>

  <section id="xochival">
  <h2>Xochival - <em>"Valley of Flowers"</em></h2>

  <p><strong>Xochival</strong> sprawls across a high plateau ringed by distant volcano silhouettes, a basin city of plazas, tree-lined boulevards, modern towers, and old stone. Murals bloom across concrete, museums stack wonders behind cool courtyards, and canals in the lakeward districts still carry flat boats bright with paint and marigolds. In Xochimex, the capital is a living market and a memory palace at once.</p>

  <p>The pace is megacity fast with neighborhood hearts. Metro lines thread the ground, bike lanes share shade with jacaranda, and street vendors turn every corner into breakfast. Brass bands practice in pocket parks while office towers mirror a sky that changes its mind twice a day. Bring good shoes, small bills, and a plan that can flex.</p>

  <hr>

  <h3>Districts and Landmarks</h3>
  <ul>
    <li><strong>Great Plaza</strong> - Monumental square ringed by civic halls and colonnades. Rallies, festivals, and a flag that writes the wind. By night, music; by morning, pigeons with opinions.</li>
    <li><strong>Canal Gardens</strong> - Lake-edge borough of chinampas and canals. Flower markets, floating kitchens, and painted boats called trajineras. Hire a pilot; the canals have their own rules.</li>
    <li><strong>Museum Mile</strong> - A chain of art houses and history courts. Cool courtyards, stone serpents, and galleries that take longer than you planned. Benches are strategic assets here.</li>
    <li><strong>Old Stones Quarter</strong> - Ruins and foundations threaded through a colonial grid. Market arcades hug old walls; guides tell three versions of every layer.</li>
    <li><strong>Reforma Walk</strong> - Grand boulevard with roundabouts and monuments. Runners at dawn, marches at noon, couples and dogs at dusk.</li>
    <li><strong>Mercado Mayor</strong> - Covered market city within the city. Produce pyramids, butcher aisles, spice canyons, and lunch counters that adopt you for a plate or two.</li>
    <li><strong>Arena Lucha</strong> - Wrestling palace of masks, capes, and popcorn. Families cheer, vendors heckle, heroes fly. It is theater and you are part of the cast.</li>
    <li><strong>Skyline Lookout</strong> - Hill park with a citywide view. Vendors sell fruit cups and opinions about the weather rolling over the rim.</li>
  </ul>

  <hr>

  <h3>Food and Drink</h3>
  <p><strong>Eat the street, then sit for soup.</strong> Dawn tamales and atole, mid-morning tlacoyos and quesadillas, noon tacos al pastor, evening pozole or birria, and late-night churros. Fruit cups with lime and chile, fresh juices, and coffee strong enough to argue. Try a <strong>Canal Picnic</strong> in the boats (fresh tortillas, grilled fish, salsas), or a <strong>Market Menu del Dia</strong> at a counter inside Mercado Mayor.</p>

  <p>Tourist note: kiosks on the Great Plaza and Reforma Walk run 5 to 10 times neighborhood prices. Ask for the "vecino measure" and step one block off the main drag; most vendors will meet you halfway and point you to their cousin s stand.</p>

  <hr>

  <h3>Order and Underlane</h3>
  <p>Peace is kept by the <strong>City Guardians</strong> and the <strong>Transit Watch</strong>, visible in plazas and on platforms. Fines tilt toward community cleaning and crosswalk duty. Health booths pop up at big events with water, maps, and quiet help. Still, a city this size has shade. Couriers whisper about the <strong>Flower Line</strong>, a night network that moves documents and last-minute cargo between markets and museums for a fee of cash and silence. They call it logistics, not a racket. Once a month the Guardians audit their donation receipts to school kitchens and canal cleanup crews; in Xochival even a shadow shows a receipt.</p>

  <hr>

  <h3>Etiquette and Practicalities</h3>
  <ul>
    <li><strong>Transit:</strong> tap card, let riders off first, backpack to the front at rush hour. Keep a small bill stash for buses and tips.</li>
    <li><strong>Street sense:</strong> stay on lit routes at night, phone away near curbs, zipped bag in crowds. Use registered cabs or app zones.</li>
    <li><strong>Markets:</strong> greet the stall, try the salsa carefully, and pay the posted price unless invited to bargain. Do not photograph people without asking.</li>
    <li><strong>Canals:</strong> hire licensed pilots, agree the price before boarding, and keep hands inside on tight turns. Bring cash for boat vendors and bands.</li>
    <li><strong>Altitude and sun:</strong> drink water, take it slow the first day, and respect a sun that bites even when it is cool.</li>
    <li><strong>Plazas:</strong> Sundays are for families and wheels. Share lanes, mind skaters, and clap for the band even if they miss a note.</li>
  </ul>

  <hr>

  <h3>Calendar and Belief</h3>
  <p>Xochival keeps a crowded calendar. <strong>Flower Boats</strong> fill the canals in spring with arches of marigold and music. <strong>Night of Paper Lights</strong> sees plazas glow with cut-paper banners and candles. <strong>Masks and Heroes</strong> brings wrestling parades down Reforma. Autumn hosts <strong>Days of Remembrance</strong> when altars bloom in courtyards and good bread sells out twice. City days plant trees along boulevards and post budgets on kiosk screens in three languages.</p>

  <hr>

  <h3>Traveler s Note</h3>
  <p>Plan big, walk small. Let the metro carry you, the markets feed you, and the murals slow you down. Tip in coins, keep a napkin stash, and say gracias more than once. If you overpay on the plaza, call it a view tax and find the lane where the lunch line is longest. Xochival will repay you with a seat on a trajinera, a bowl that steams in your hands, and a sky that turns city lights into another constellation.</p>
</section>
