<?php require_login(); ?>
<h1>Yamanokubo</h1>
<img src="images/harmontide-yamanokubo.webp" alt="World map" usemap="#worldmap" class="world-map" />
<!-- Image Map Generated by http://www.image-map.net/ -->
<map name="worldmap">
</map>
  
  <div class="card glass">
    <h3>Paint Shack</h3>
    <p class="muted">Here you can paint your Yamanokubo creatures.</p>
    <a class="btn" href="?pg=ynk_paint_shack">Explore</a>
  </div>

  <div class="card glass">
    <h3>Lotus Terrace Shrine Visit</h3>
    <p class="muted">A daily shrine stop in Amatera that stacks luck when you keep your visits going.</p>
    <a class="btn" href="?pg=ynk-adventure">Begin</a>
  </div>

  <div class="card glass">
    <h3>Yumenoki Ramen</h3>
    <p class="muted">Noodle counter with simmered broths, late-night tea, and quick stools under warm cedar.</p>
    <a class="btn" href="?pg=ynk-ramen">Order</a>
  </div>

  <div class="card glass">
    <h3>Gacha Machines</h3>
    <p class="muted">A bunch of machines, giving you something strange for your Dosh.</p>
    <a class="btn" href="?pg=gacha">Gamble</a>
  </div>
  
  <div class="card glass">
    <h3>Back to Dawnmarch</h3>
    <a class="btn" href="?pg=dawnmarch">Explore</a>
  </div>

  <section id="amatera">
  <h2>Amatera - <em>"City of the Mountain and the Sun"</em></h2>

  <p><strong>Amatera</strong> unfurls along a river below green ridges, a capital of tile roofs, white plaster walls, and gates painted the color of sunrise. Castle keeps step above moat and stone, lantern-lit bridges stitch wards together, and narrow lanes carry sandal steps past noren curtains and paper screens. Think Edo-era grace: drum and bell mark the hours, guild flags hang from eaves, and pagodas rise like calm prayers over cedar.</p>

  <p>The city breathes in three beats: court, craft, and courtyard. Magistrates read petitions from veranda shade; print shops thrum with woodblocks; tea steam curls from garden pavilions while monks ring a bronze bell that makes conversation lower itself out of respect. In the Mountain Shogunate, order is a gardened thing; in Amatera it is pruned daily with broom, brush, and bow.</p>

  <hr>

  <h3>Districts and Landmarks</h3>
  <ul>
    <li><strong>Sun Keep</strong> - Castle hill with layered walls and a watchtower that sees storms a day early. The moat carp are older than some clans; feeding them is luck and a light fine if you toss anything but grain.</li>
    <li><strong>Willow Bridge Row</strong> - Long bridge lined with lanterns and drum posts. Storytellers and vendors set up at dusk; keep to the left and do not stop on the crest to pose.</li>
    <li><strong>North Magistracy</strong> - Courtyards, sliding doors, evidence gardens, and a public notice board where edicts share space with lost sandals and found umbrellas.</li>
    <li><strong>Paper Lane</strong> - Woodblock carvers, ink grinders, bookbinders. The air smells of pine soot and rice paste; printers hang fresh sheets like sails.</li>
    <li><strong>Smith Street</strong> - Bell makers, blade polishers, kettle founders. Apprentices bow with soot on their faces and pride they do not quite hide.</li>
    <li><strong>Lotus Temple Close</strong> - Shrine and zendo around a pond. One stick of incense is enough; step lightly, bow once, and mind the koi.</li>
    <li><strong>River Fish Market</strong> - Morning clatter of baskets, tubs, and quick knives. Tea sellers walk the aisles with kettles and good advice about bones.</li>
    <li><strong>Moon Theater Quarter</strong> - Kabuki stages, bunraku houses, music halls, and lantern alleys. Families come early; students stay late arguing actors by nickname.</li>
    <li><strong>Pine Garden Walk</strong> - A strolling garden of stone, water, and borrowed view. Paths curve on purpose so thoughts must follow.</li>
  </ul>

  <hr>

  <h3>Food and Tea</h3>
  <p><strong>Eat season, drink patience.</strong> Morning onigiri with pickled plum, midday soba that snaps like a good line, tempura so light it forgets it was in oil, river eel lacquered to a shine, skewers of chicken and leek over charcoal, tofu hot in clay with ginger and green. Teahouses pour sencha and matcha with a bow and a quiet lesson in cups; street stalls steam sweet buns and ladle warm amazake on cold nights.</p>

  <p>Tourist note: stalls on Willow Bridge and outside Moon Theater price 5 to 10 times lane rate. Ask for the "neighbor measure" and compliment the brushwork on the signboard; most vendors will smile and shave the number to what a stagehand pays.</p>

  <hr>

  <h3>Order and Underlane</h3>
  <p>Peace is kept by the <strong>City Watch</strong> under the magistrates: patrols with jingasa hats, ledgers, and the habit of sweeping as they walk. Fines lean toward repair and service: mending bridge rails, copying notices, raking gravel straight after a hurried foot. Amatera also keeps shade where lantern light thins. People mention the <strong>Lantern Guild</strong>, discreet go-betweens who move sealed letters and delicate parcels after curfew for a fee of tea bricks and silence. They call it courtesy, not a racket. Each season their donation chests are opened in public at the North Magistracy; in this city even a shadow shows a receipt.</p>

  <hr>

  <h3>Etiquette and Practicalities</h3>
  <ul>
    <li><strong>Greetings:</strong> small bow, hands at sides. Loud voices belong to bridges in flood, not to markets.</li>
    <li><strong>Shrines and halls:</strong> hats off, shoes clean. One clap, one bow, one wish. Do not touch carved dragons for luck; they bite in stories and splinter in truth.</li>
    <li><strong>Tea:</strong> tap two fingers to thank a pour. Do not drown leaves; let the pot breathe between cups.</li>
    <li><strong>Streets:</strong> keep to the left on bridges and busy lanes. Umbrellas tilt low at eye level, not high like banners.</li>
    <li><strong>Markets:</strong> praise the craft, then bargain a little. If a vendor ties a red cord to your parcel, it is a blessing against clumsiness; do not cut it until home.</li>
    <li><strong>Curfew:</strong> the drum at second watch. Lantern guides are licensed; hire one or stay on the main streets.</li>
  </ul>

  <hr>

  <h3>Calendar and Belief</h3>
  <p>Amatera keeps <strong>Lantern River</strong> at first full moon when candles float from Willow Bridge and children chase their reflections. <strong>Spring Viewing</strong> brings petals that fall like slow snow and merchants who measure sales by how many blossoms land on their ledgers. In high summer <strong>Boat Processions</strong> carry shrine banners along the river with drums and shouted blessings. Autumn hosts <strong>Moon Cakes and Masks</strong> in the theater quarter; winter brings <strong>Quiet Bell</strong> when the year changes with a single long note from Lotus Temple.</p>

  <hr>

  <h3>Traveler's Note</h3>
  <p>Walk as if your sleeves were wider than they are. Read the notice boards, mind the drum, and let tea slow you down. If you overpay under the theater lanterns, call it a stage tax and try Paper Lane tomorrow. The city will repay you with a steadier step, a cleaner page, and a garden path that ends exactly where your breath does.</p>
</section>

