<?php require_login(); ?>
<h1>Yara Nations</h1>
<img src="images/harmontide-yn.webp" alt="World map" usemap="#worldmap" class="world-map" />
<!-- Image Map Generated by http://www.image-map.net/ -->
<map name="worldmap">
</map>
  
  <div class="card glass">
    <h3>Paint Shack</h3>
    <p class="muted">Here you can paint your Yara Nations creatures.</p>
    <a class="btn" href="?pg=yn_paint_shack">Explore</a>
  </div>
  
  <div class="card glass">
    <h3>Back to Uluru</h3>
    <a class="btn" href="?pg=uluru">Explore</a>
  </div>

  <section id="warraluma">
  <h2>Warraluma - <em>"Where River Meets Song"</em></h2>

  <p><strong>Warraluma</strong> rests between a red-rock escarpment and a tidal river that braids into mangroves and billabongs. Heat shimmers at noon, sea breeze comes like a promise by late afternoon, and the evening sky writes old maps in bright chalk. In the Yara Nations the first law is Country. Warraluma keeps that law in how it walks, eats, paints, and greets.</p>

  <p>This is a city built around keeping places and meeting grounds rather than walls. Boardwalks skim wetlands, shade sails stitch plazas, and painted posts mark paths that follow songlines. Elders sit where wind and story move best; rangers read the seasons from flowers and tides. Visitors learn fast: ask before you enter, listen before you speak, and leave a place better than you found it.</p>

  <hr>

  <h3>Districts and Landmarks</h3>
  <ul>
    <li><strong>Meeting Ground</strong> - Open circle of red earth and shade trees. Welcomes to Country, smoking ceremonies, community decisions. Shoes off if the custodian asks; photos only with permission.</li>
    <li><strong>River Steps</strong> - Timber terraces down to the tidal water. Kids fish for mullet, aunties teach knots, rangers post the tide and croc board. When the curlew calls, go home by the lit path.</li>
    <li><strong>Keeping Place</strong> - Cultural center and archive. Carvings, bark paintings, fiber works, story rooms, and a small reading table that is always busy. Some rooms are restricted; respect the signs.</li>
    <li><strong>Stone Gallery</strong> - Rock shelters under the escarpment with ancient art. Visits are guided and on the cool side of the day. Stay on the path; stone remembers footprints.</li>
    <li><strong>Songline Walk</strong> - Wayfinding path marked by painted poles and ground symbols. Each bend teaches a plant, an animal, or a season. Walk slow; it is a class, not a shortcut.</li>
    <li><strong>Star Field</strong> - Low hill with a horizon line. Night talks about the Emu in the Sky and river tides. The wind is a better storyteller if you bring a blanket.</li>
    <li><strong>Market Shade</strong> - Long roof of beams and palm thatch. Bush foods, clapsticks, shell work, woven baskets, prints, and cool water. Prices support families and Country projects.</li>
    <li><strong>Mangrove Board</strong> - Raised walk through the mangroves to the river mouth. Mud fiddlers drum, egrets hunt, and the tide writes in mirror script.</li>
  </ul>

  <hr>

  <h3>Food and Drink</h3>
  <p><strong>Eat what the seasons bring.</strong> Barramundi grilled in paperbark, kangaroo skewers with pepperberry, damper with wattleseed and honey, yams and bush tomatoes, lemon myrtle chicken, crocodile bites with finger lime, and quandong tarts. Cool drinks run to lemon myrtle iced tea, river mint water, and coffee that forgives long nights.</p>

  <p>Tourist note: stalls right on River Steps and at Stone Gallery trailheads can be 5 to 10 times the lane rate. Ask for the "neighbor measure" and point to the Country fund box; most vendors will smile and set the price to what a ranger pays.</p>

  <hr>

  <h3>Order and Underlane</h3>
  <p>Peace is kept by the <strong>Country Rangers</strong> with radios, first aid, and more knowledge than a map. Fines tilt toward work that helps all: path repair, litter sweeps, water runs for elders, and firebreak checks. Warraluma also runs a quiet lift network, the <strong>Night Trackers</strong>, who ferry elders, medicine, and late workers after curfew for fuel money and thanks. They call it kin duty, not a racket. Each month the council posts Night Tracker donations and trips on the notice board by the Meeting Ground; in this town even a shadow shows a receipt.</p>

  <hr>

  <h3>Etiquette and Practicalities</h3>
  <ul>
    <li><strong>Welcome:</strong> listen to custodians and elders first. Acknowledge Country when you speak. "Thank you for welcome" goes a long way.</li>
    <li><strong>Access:</strong> some places are men s or women s business, some are closed. If a sign says no, it means care, not secrecy.</li>
    <li><strong>Photos and recordings:</strong> ask people before you point a lens, and do not record ceremony or rock art without explicit permission.</li>
    <li><strong>Tracks and tides:</strong> stay on marked paths, watch the croc and jellyfish boards, and give mangroves your respect. The tide keeps its own time.</li>
    <li><strong>Fires:</strong> only in set pits, only with ranger go-ahead. Seasonal cool burns are skilled work; admire from the line.</li>
    <li><strong>Gifts and trade:</strong> buy direct from makers, not from trunks. If you pick a fruit, leave two for birds and kids.</li>
    <li><strong>Heat:</strong> carry water, hat, and sense. Rest in shade at noon; the story can wait an hour.</li>
  </ul>

  <hr>

  <h3>Calendar and Belief</h3>
  <p>Warraluma follows a many-season wheel. <strong>First Rains</strong> wakes frogs and paints the sky green; <strong>Mango Time</strong> brings sticky hands and laughter; <strong>Burning Cool</strong> moves careful fire through grass to keep Country healthy; <strong>Turtle Moon</strong> watches nests and lights kept low; <strong>Dry High</strong> opens the long road to Stone Gallery at dawn and closes it at noon. Night gatherings mark <strong>Star Stories</strong> with songs and quiet feet. Welcome to Country and smoking ceremonies open big events so guests step in properly.</p>

  <hr>

  <h3>Traveler s Note</h3>
  <p>Walk soft, ask first, carry water, and leave thanks. If you overpay by the river, call it a tide tax and put a note in the Country fund. Learn the name of the hill that watched you today and say it back to the wind. Warraluma will remember your manners longer than your footprints.</p>
</section>
