<?php require_login(); ?>
<h1>Yara Nations</h1>
<p>Warraluma.</p>
<img src="images/harmontide-yn.png" alt="World map" usemap="#worldmap" class="world-map" />
<!-- Image Map Generated by http://www.image-map.net/ -->
<map name="worldmap">
</map>
  
  <div class="card glass">
    <h3>Back to Uluru</h3>
    <a class="btn" href="?pg=uluru">Explore</a>
  </div>