-- Ability catalog and one ability slot per pet instance.
CREATE TABLE IF NOT EXISTS pet_has_ability (
  ability_id INT UNSIGNED NOT NULL,
  species_id SMALLINT UNSIGNED NOT NULL,
  ability_name VARCHAR(120) NOT NULL,
  ability_desc TEXT NOT NULL,
  PRIMARY KEY (ability_id),
  KEY ix_pet_has_ability_species (species_id),
  CONSTRAINT fk_pet_has_ability_species FOREIGN KEY (species_id)
    REFERENCES pet_species(species_id) ON DELETE CASCADE
) ENGINE=InnoDB;

ALTER TABLE pet_instances
  ADD COLUMN ability_id INT UNSIGNED NULL AFTER initiative,
  ADD KEY ix_pet_instances_ability (ability_id),
  ADD CONSTRAINT fk_pet_instances_ability FOREIGN KEY (ability_id)
    REFERENCES pet_has_ability(ability_id) ON DELETE SET NULL;

INSERT INTO pet_has_ability (ability_id, species_id, ability_name, ability_desc) VALUES
(581, 58, 'Healing Venom', 'Lamia metabolizes the force of contact attacks, restoring HP equal to 15% of the damage dealt.'),
(582, 58, 'Sacred Coil', 'Lamia winds into a guarded ritual posture, raising defense by 18% when battle begins.'),
(591, 59, 'Full Gallop', 'Centaur commits its whole stride to the attack. Contact moves deal 20% more damage and gain one priority step.'),
(592, 59, 'Four-Footed Balance', 'Centaur braces across four points of contact, reducing damage from contact attacks by 20%.'),
(1121, 112, 'Many-Armed Lock', 'Kraken''s limbs turn a close strike into a hold. Contact attacks deal 15% more damage and lower each target''s attack by 10% once.'),
(1122, 112, 'Abyssal Pressure', 'Kraken weaponizes deep-water pressure, making Kuro and Vai attacks deal 20% more damage.'),
(1131, 113, 'Ratatoskr''s Native Instinct', 'Ratatoskr leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(1132, 113, 'Ratatoskr Electra Resonance', 'Ratatoskr channels its Electra affinity with unusual precision, making matching attacks deal 18% more damage.'),
(1141, 114, 'Banshee''s Veilborn Instinct', 'Banshee leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(1142, 114, 'Banshee Ethereal Resonance', 'Banshee channels its Ethereal affinity with unusual precision, making matching attacks deal 18% more damage.'),
(1151, 115, 'Dullahan''s Veilborn Instinct', 'Dullahan leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(1152, 115, 'Dullahan Ethereal Resonance', 'Dullahan channels its Ethereal affinity with unusual precision, making matching attacks deal 18% more damage.'),
(1161, 116, 'Unhanded Flame', 'Will-o-Wisp has no solid body to seize, reducing damage from contact attacks by 35%.'),
(1162, 116, 'Lurelight', 'Will-o-Wisp draws foes toward a false light. Non-contact attacks deal 20% more damage and restore 10% of damage dealt.'),
(1171, 117, 'Kelpie''s Tidewise Instinct', 'Kelpie leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(1172, 117, 'Kelpie Ethereal Resonance', 'Kelpie channels its Ethereal affinity with unusual precision, making matching attacks deal 18% more damage.'),
(1181, 118, 'Angel''s Native Instinct', 'Angel leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(1182, 118, 'Angel Aer Resonance', 'Angel channels its Aer affinity with unusual precision, making matching attacks deal 18% more damage.'),
(1641, 164, 'Demon''s Native Instinct', 'Demon leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(1642, 164, 'Demon Heat Resonance', 'Demon channels its Heat affinity with unusual precision, making matching attacks deal 18% more damage.'),
(1651, 165, 'Succubus''s Native Instinct', 'Succubus leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(1652, 165, 'Succubus Fae Resonance', 'Succubus channels its Fae affinity with unusual precision, making matching attacks deal 18% more damage.'),
(1661, 166, 'Leshy''s Native Instinct', 'Leshy leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(1662, 166, 'Leshy Ethereal Resonance', 'Leshy channels its Ethereal affinity with unusual precision, making matching attacks deal 18% more damage.'),
(1671, 167, 'Vodyanoy''s Tidewise Instinct', 'Vodyanoy leans into the strongest part of its natural build, raising defense by 12% when it enters battle.'),
(1672, 167, 'Vodyanoy Kuro Resonance', 'Vodyanoy channels its Kuro affinity with unusual precision, making matching attacks deal 18% more damage.'),
(1681, 168, 'Lich''s Veilborn Instinct', 'Lich leans into the strongest part of its natural build, raising attack by 12% when it enters battle.'),
(1682, 168, 'Lich Ethereal Resonance', 'Lich channels its Ethereal affinity with unusual precision, making matching attacks deal 18% more damage.'),
(1691, 169, 'Jack-o-Lantern''s Veilborn Instinct', 'Jack-o-Lantern leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(1692, 169, 'Jack-o-Lantern Ethereal Resonance', 'Jack-o-Lantern channels its Ethereal affinity with unusual precision, making matching attacks deal 18% more damage.'),
(1701, 170, 'Storm Conductor', 'Thunderbird gathers charge across its feathers, making Electra attacks deal 25% more damage.'),
(1702, 170, 'Ground the Bolt', 'Thunderbird safely grounds hostile electricity, reducing incoming Electra damage by 50%.'),
(1711, 171, 'Horned Serpent Uktena''s Coiled Instinct', 'Horned Serpent Uktena leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(1712, 171, 'Horned Serpent Uktena Malus Resonance', 'Horned Serpent Uktena channels its Malus affinity with unusual precision, making matching attacks deal 18% more damage.'),
(1721, 172, 'Jiang-Shi''s Veilborn Instinct', 'Jiang-Shi leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(1722, 172, 'Jiang-Shi Ethereal Resonance', 'Jiang-Shi channels its Ethereal affinity with unusual precision, making matching attacks deal 18% more damage.'),
(1731, 173, 'Vermillion Bird''s Highwind Instinct', 'Vermillion Bird leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(1732, 173, 'Vermillion Bird Aer Resonance', 'Vermillion Bird channels its Aer affinity with unusual precision, making matching attacks deal 18% more damage.'),
(1741, 174, 'Gandharva''s Native Instinct', 'Gandharva leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(1742, 174, 'Gandharva Aer Resonance', 'Gandharva channels its Aer affinity with unusual precision, making matching attacks deal 18% more damage.'),
(1751, 175, 'Naga''s Coiled Instinct', 'Naga leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(1752, 175, 'Naga Malus Resonance', 'Naga channels its Malus affinity with unusual precision, making matching attacks deal 18% more damage.'),
(1761, 176, 'Spider-Crab''s Tidewise Instinct', 'Spider-Crab leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(1762, 176, 'Spider-Crab Arthropoda Resonance', 'Spider-Crab channels its Arthropoda affinity with unusual precision, making matching attacks deal 18% more damage.'),
(1771, 177, 'Kitsune''s Native Instinct', 'Kitsune leans into the strongest part of its natural build, raising attack by 12% when it enters battle.'),
(1772, 177, 'Kitsune Fae Resonance', 'Kitsune channels its Fae affinity with unusual precision, making matching attacks deal 18% more damage.'),
(1781, 178, 'Yuki-Onna''s Veilborn Instinct', 'Yuki-Onna leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(1782, 178, 'Yuki-Onna Cold Resonance', 'Yuki-Onna channels its Cold affinity with unusual precision, making matching attacks deal 18% more damage.'),
(1791, 179, 'La Llorona''s Veilborn Instinct', 'La Llorona leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(1792, 179, 'La Llorona Ethereal Resonance', 'La Llorona channels its Ethereal affinity with unusual precision, making matching attacks deal 18% more damage.'),
(1801, 180, 'Chupacabra''s Native Instinct', 'Chupacabra leans into the strongest part of its natural build, raising attack by 12% when it enters battle.'),
(1802, 180, 'Chupacabra Kuro Resonance', 'Chupacabra channels its Kuro affinity with unusual precision, making matching attacks deal 18% more damage.'),
(1811, 181, 'Charro Negro''s Native Instinct', 'Charro Negro leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(1812, 181, 'Charro Negro Ethereal Resonance', 'Charro Negro channels its Ethereal affinity with unusual precision, making matching attacks deal 18% more damage.'),
(1821, 182, 'Quetzalcoatl''s Coiled Instinct', 'Quetzalcoatl leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(1822, 182, 'Quetzalcoatl Aer Resonance', 'Quetzalcoatl channels its Aer affinity with unusual precision, making matching attacks deal 18% more damage.'),
(1831, 183, 'Ahuizotl''s Native Instinct', 'Ahuizotl leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(1832, 183, 'Ahuizotl Kuro Resonance', 'Ahuizotl channels its Kuro affinity with unusual precision, making matching attacks deal 18% more damage.'),
(1841, 184, 'Cipactli''s Coiled Instinct', 'Cipactli leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(1842, 184, 'Cipactli Floor Resonance', 'Cipactli channels its Floor affinity with unusual precision, making matching attacks deal 18% more damage.'),
(1851, 185, 'Ocelot''s Trailwise Instinct', 'Ocelot leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(1852, 185, 'Ocelot Kuro Resonance', 'Ocelot channels its Kuro affinity with unusual precision, making matching attacks deal 18% more damage.'),
(1861, 186, 'Azureus''s Native Instinct', 'Azureus leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(1862, 186, 'Azureus Vai Resonance', 'Azureus channels its Vai affinity with unusual precision, making matching attacks deal 18% more damage.'),
(1871, 187, 'Tapir''s Trailwise Instinct', 'Tapir leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(1872, 187, 'Tapir Flora Resonance', 'Tapir channels its Flora affinity with unusual precision, making matching attacks deal 18% more damage.'),
(1881, 188, 'Crab man''s Tidewise Instinct', 'Crab man leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(1882, 188, 'Crab man Kampf Resonance', 'Crab man channels its Kampf affinity with unusual precision, making matching attacks deal 18% more damage.'),
(1891, 189, 'Taniwha''s Tidewise Instinct', 'Taniwha leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(1892, 189, 'Taniwha Vai Resonance', 'Taniwha channels its Vai affinity with unusual precision, making matching attacks deal 18% more damage.'),
(1901, 190, 'Genie''s Native Instinct', 'Genie leans into the strongest part of its natural build, raising attack by 12% when it enters battle.'),
(1902, 190, 'Genie Aer Resonance', 'Genie channels its Aer affinity with unusual precision, making matching attacks deal 18% more damage.'),
(1911, 191, 'Bahamut''s Coiled Instinct', 'Bahamut leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(1912, 191, 'Bahamut Vai Resonance', 'Bahamut channels its Vai affinity with unusual precision, making matching attacks deal 18% more damage.'),
(1921, 192, 'Girtablilu''s Native Instinct', 'Girtablilu leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(1922, 192, 'Girtablilu Arthropoda Resonance', 'Girtablilu channels its Arthropoda affinity with unusual precision, making matching attacks deal 18% more damage.'),
(1931, 193, 'Lamassu''s Native Instinct', 'Lamassu leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(1932, 193, 'Lamassu Aer Resonance', 'Lamassu channels its Aer affinity with unusual precision, making matching attacks deal 18% more damage.'),
(1941, 194, 'Golem''s Native Instinct', 'Golem leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(1942, 194, 'Golem Mental Resonance', 'Golem channels its Mental affinity with unusual precision, making matching attacks deal 18% more damage.'),
(1951, 195, 'Dolphin''s Tidewise Instinct', 'Dolphin leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(1952, 195, 'Dolphin Mental Resonance', 'Dolphin channels its Mental affinity with unusual precision, making matching attacks deal 18% more damage.'),
(1961, 196, 'Anubis''s Native Instinct', 'Anubis leans into the strongest part of its natural build, raising attack by 12% when it enters battle.'),
(1962, 196, 'Anubis Floor Resonance', 'Anubis channels its Floor affinity with unusual precision, making matching attacks deal 18% more damage.'),
(1971, 197, 'Wadjet''s Coiled Instinct', 'Wadjet leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(1972, 197, 'Wadjet Aer Resonance', 'Wadjet channels its Aer affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2281, 228, 'Amarok''s Native Instinct', 'Amarok leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(2282, 228, 'Amarok Cold Resonance', 'Amarok channels its Cold affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2291, 229, 'Polar Bear''s Trailwise Instinct', 'Polar Bear leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(2292, 229, 'Polar Bear Cold Resonance', 'Polar Bear channels its Cold affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2301, 230, 'Drop Bear''s Trailwise Instinct', 'Drop Bear leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(2302, 230, 'Drop Bear Kuro Resonance', 'Drop Bear channels its Kuro affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2311, 231, 'Min-Min Lights''s Native Instinct', 'Min-Min Lights leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(2312, 231, 'Min-Min Lights Electra Resonance', 'Min-Min Lights channels its Electra affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2321, 232, 'Bunyip''s Tidewise Instinct', 'Bunyip leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(2322, 232, 'Bunyip Kuro Resonance', 'Bunyip channels its Kuro affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2331, 233, 'Rainbow Serpent''s Coiled Instinct', 'Rainbow Serpent leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(2332, 233, 'Rainbow Serpent Fae Resonance', 'Rainbow Serpent channels its Fae affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2341, 234, 'Curupira''s Native Instinct', 'Curupira leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(2342, 234, 'Curupira Fae Resonance', 'Curupira channels its Fae affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2351, 235, 'Capybara''s Trailwise Instinct', 'Capybara leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(2352, 235, 'Capybara Vai Resonance', 'Capybara channels its Vai affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2361, 236, 'Fishman''s Tidewise Instinct', 'Fishman leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(2362, 236, 'Fishman Kampf Resonance', 'Fishman channels its Kampf affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2371, 237, 'Argentinosaurus''s Native Instinct', 'Argentinosaurus leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(2372, 237, 'Argentinosaurus Flora Resonance', 'Argentinosaurus channels its Flora affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2381, 238, 'Amaru''s Coiled Instinct', 'Amaru leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(2382, 238, 'Amaru Aer Resonance', 'Amaru channels its Aer affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2391, 239, 'Wayob''s Native Instinct', 'Wayob leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(2392, 239, 'Wayob Ethereal Resonance', 'Wayob channels its Ethereal affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2401, 240, 'Black Turtle''s Tidewise Instinct', 'Black Turtle leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(2402, 240, 'Black Turtle Ferrum Resonance', 'Black Turtle channels its Ferrum affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2411, 241, 'Lilith''s Native Instinct', 'Lilith leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(2412, 241, 'Lilith Kuro Resonance', 'Lilith channels its Kuro affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2421, 242, 'Kappa''s Native Instinct', 'Kappa leans into the strongest part of its natural build, raising defense by 12% when it enters battle.'),
(2422, 242, 'Kappa Flora Resonance', 'Kappa channels its Flora affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2431, 243, 'Kangaroo''s Trailwise Instinct', 'Kangaroo leans into the strongest part of its natural build, raising attack by 12% when it enters battle.'),
(2432, 243, 'Kangaroo Kampf Resonance', 'Kangaroo channels its Kampf affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2441, 244, 'Keelut''s Native Instinct', 'Keelut leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(2442, 244, 'Keelut Cold Resonance', 'Keelut channels its Cold affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2451, 245, 'Mimic''s Veilborn Instinct', 'Mimic leans into the strongest part of its natural build, raising attack by 12% when it enters battle.'),
(2452, 245, 'Mimic Ethereal Resonance', 'Mimic channels its Ethereal affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2461, 246, 'Jackalope''s Native Instinct', 'Jackalope leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(2462, 246, 'Jackalope Fae Resonance', 'Jackalope channels its Fae affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2471, 247, 'Mad Hatter''s Native Instinct', 'Mad Hatter leans into the strongest part of its natural build, raising attack by 12% when it enters battle.'),
(2472, 247, 'Mad Hatter Fae Resonance', 'Mad Hatter channels its Fae affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2481, 248, 'Final Appointment', 'Death becomes inexorable when an opponent nears its end, dealing 40% more damage to targets at 35% HP or lower.'),
(2482, 248, 'Death''s Door', 'Once per battle, Death refuses a lethal blow and remains at 1 HP. The reprieve is brief, but absolute.'),
(2491, 249, 'War''s Veilborn Instinct', 'War leans into the strongest part of its natural build, raising attack by 12% when it enters battle.'),
(2492, 249, 'War Kampf Resonance', 'War channels its Kampf affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2501, 250, 'Lingering Malaise', 'Pestilence leaves weakness behind after a damaging hit, lowering each target''s attack by 12% once.'),
(2502, 250, 'Plague Wind', 'Pestilence spreads harm without touching its foe, making non-contact attacks deal 25% more damage.'),
(2511, 251, 'Fury''s Veilborn Instinct', 'Fury leans into the strongest part of its natural build, raising attack by 12% when it enters battle.'),
(2512, 251, 'Fury Heat Resonance', 'Fury channels its Heat affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2521, 252, 'Famine''s Veilborn Instinct', 'Famine leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(2522, 252, 'Famine Floor Resonance', 'Famine channels its Floor affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2531, 253, 'Elf''s Native Instinct', 'Elf leans into the strongest part of its natural build, raising attack by 12% when it enters battle.'),
(2532, 253, 'Elf Fae Resonance', 'Elf channels its Fae affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2541, 254, 'Blaze Cat''s Trailwise Instinct', 'Blaze Cat leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(2542, 254, 'Blaze Cat Heat Resonance', 'Blaze Cat channels its Heat affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2551, 255, 'Waterlil''s Tidewise Instinct', 'Waterlil leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(2552, 255, 'Waterlil Flora Resonance', 'Waterlil channels its Flora affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2561, 256, 'Slidred''s Veilborn Instinct', 'Slidred leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(2562, 256, 'Slidred Cold Resonance', 'Slidred channels its Cold affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2571, 257, 'Alisnapor''s Native Instinct', 'Alisnapor leans into the strongest part of its natural build, raising attack by 12% when it enters battle.'),
(2572, 257, 'Alisnapor Kampf Resonance', 'Alisnapor channels its Kampf affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2581, 258, 'Daeodon''s Deep-Time Instinct', 'Daeodon leans into the strongest part of its natural build, raising attack by 12% when it enters battle.'),
(2582, 258, 'Daeodon Floor Resonance', 'Daeodon channels its Floor affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2591, 259, 'Anomalocaris''s Deep-Time Instinct', 'Anomalocaris leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(2592, 259, 'Anomalocaris Arthropoda Resonance', 'Anomalocaris channels its Arthropoda affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2601, 260, 'Adaro''s Tidewise Instinct', 'Adaro leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(2602, 260, 'Adaro Ethereal Resonance', 'Adaro channels its Ethereal affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2611, 261, 'Akaname''s Native Instinct', 'Akaname leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(2612, 261, 'Akaname Ethereal Resonance', 'Akaname channels its Ethereal affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2621, 262, 'Bee''s Native Instinct', 'Bee leans into the strongest part of its natural build, raising attack by 12% when it enters battle.'),
(2622, 262, 'Bee Arthropoda Resonance', 'Bee channels its Arthropoda affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2631, 263, 'Spring-Loaded Legs', 'Bullywug coils like a frog before the bell. Its speed rises by 20%, and its contact attacks gain one priority step.'),
(2632, 263, 'Tongue Snare', 'Bullywug lashes out with a sticky tongue. Contact attacks deal 20% more damage and slow each target by 10% the first time they connect.'),
(2641, 264, 'Landharpy''s Highwind Instinct', 'Landharpy leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(2642, 264, 'Landharpy Aer Resonance', 'Landharpy channels its Aer affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2651, 265, 'Yatagarasu''s Highwind Instinct', 'Yatagarasu leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(2652, 265, 'Yatagarasu Aer Resonance', 'Yatagarasu channels its Aer affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2661, 266, 'Mountain Gust', 'Tengu catches the mountain wind in its wings. Aer attacks deal 22% more damage and gain one priority step.'),
(2662, 266, 'Fan Parry', 'Tengu turns projectiles and sorcery aside with a war fan, reducing non-contact damage by 22%.'),
(2671, 267, 'Klabuster''s Native Instinct', 'Klabuster leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(2672, 267, 'Klabuster Fae Resonance', 'Klabuster channels its Fae affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2681, 268, 'Frost Giant''s Deep-Time Instinct', 'Frost Giant leans into the strongest part of its natural build, raising attack by 12% when it enters battle.'),
(2682, 268, 'Frost Giant Cold Resonance', 'Frost Giant channels its Cold affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2691, 269, 'Fire Giant''s Deep-Time Instinct', 'Fire Giant leans into the strongest part of its natural build, raising attack by 12% when it enters battle.'),
(2692, 269, 'Fire Giant Heat Resonance', 'Fire Giant channels its Heat affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2701, 270, 'Spoodr''s Native Instinct', 'Spoodr leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(2702, 270, 'Spoodr Arthropoda Resonance', 'Spoodr channels its Arthropoda affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2711, 271, 'Ziz''s Highwind Instinct', 'Ziz leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(2712, 271, 'Ziz Aer Resonance', 'Ziz channels its Aer affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2721, 272, 'Toucan''s Highwind Instinct', 'Toucan leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(2722, 272, 'Toucan Aer Resonance', 'Toucan channels its Aer affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2731, 273, 'Tiddalik''s Native Instinct', 'Tiddalik leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(2732, 273, 'Tiddalik Vai Resonance', 'Tiddalik channels its Vai affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2741, 274, 'Spinosaur''s Deep-Time Instinct', 'Spinosaur leans into the strongest part of its natural build, raising attack by 12% when it enters battle.'),
(2742, 274, 'Spinosaur Vai Resonance', 'Spinosaur channels its Vai affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2751, 275, 'Ancient Carapace', 'Sea Turtle''s weathered shell raises defense by 25% when battle begins.'),
(2752, 275, 'Shell Turn', 'Sea Turtle rolls with direct impacts, reducing contact damage by 25%.'),
(2761, 276, 'Pishtaco''s Native Instinct', 'Pishtaco leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(2762, 276, 'Pishtaco Ethereal Resonance', 'Pishtaco channels its Ethereal affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2771, 277, 'Penguin''s Highwind Instinct', 'Penguin leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(2772, 277, 'Penguin Cold Resonance', 'Penguin channels its Cold affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2781, 278, 'Pegasus''s Native Instinct', 'Pegasus leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(2782, 278, 'Pegasus Aer Resonance', 'Pegasus channels its Aer affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2791, 279, 'Oryx''s Trailwise Instinct', 'Oryx leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(2792, 279, 'Oryx Floor Resonance', 'Oryx channels its Floor affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2801, 280, 'Nightmarcher''s Veilborn Instinct', 'Nightmarcher leans into the strongest part of its natural build, raising attack by 12% when it enters battle.'),
(2802, 280, 'Nightmarcher Ethereal Resonance', 'Nightmarcher channels its Ethereal affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2811, 281, 'Moo''s Native Instinct', 'Moo leans into the strongest part of its natural build, raising defense by 12% when it enters battle.'),
(2812, 281, 'Moo Vulgaris Resonance', 'Moo channels its Vulgaris affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2821, 282, 'Manticore''s Native Instinct', 'Manticore leans into the strongest part of its natural build, raising attack by 12% when it enters battle.'),
(2822, 282, 'Manticore Kuro Resonance', 'Manticore channels its Kuro affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2831, 283, 'La Mano Peluda''s Native Instinct', 'La Mano Peluda leans into the strongest part of its natural build, raising attack by 12% when it enters battle.'),
(2832, 283, 'La Mano Peluda Ethereal Resonance', 'La Mano Peluda channels its Ethereal affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2841, 284, 'Harpy''s Highwind Instinct', 'Harpy leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(2842, 284, 'Harpy Aer Resonance', 'Harpy channels its Aer affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2851, 285, 'Dugong''s Tidewise Instinct', 'Dugong leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(2852, 285, 'Dugong Vai Resonance', 'Dugong channels its Vai affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2861, 286, 'Camel''s Trailwise Instinct', 'Camel leans into the strongest part of its natural build, raising attack by 12% when it enters battle.'),
(2862, 286, 'Camel Floor Resonance', 'Camel channels its Floor affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2871, 287, 'Apsara''s Native Instinct', 'Apsara leans into the strongest part of its natural build, raising attack by 12% when it enters battle.'),
(2872, 287, 'Apsara Fae Resonance', 'Apsara channels its Fae affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2881, 288, 'Armadillo''s Tidewise Instinct', 'Armadillo leans into the strongest part of its natural build, raising defense by 12% when it enters battle.'),
(2882, 288, 'Armadillo Ferrum Resonance', 'Armadillo channels its Ferrum affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2891, 289, 'Kachina''s Native Instinct', 'Kachina leans into the strongest part of its natural build, raising attack by 12% when it enters battle.'),
(2892, 289, 'Kachina Fae Resonance', 'Kachina channels its Fae affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2901, 290, 'Papillon''s Highwind Instinct', 'Papillon leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(2902, 290, 'Papillon Arthropoda Resonance', 'Papillon channels its Arthropoda affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2911, 291, 'Brownie''s Native Instinct', 'Brownie leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(2912, 291, 'Brownie Fae Resonance', 'Brownie channels its Fae affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2921, 292, 'Sunwukong''s Native Instinct', 'Sunwukong leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(2922, 292, 'Sunwukong Kampf Resonance', 'Sunwukong channels its Kampf affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2931, 293, 'Tuskin''s Deep-Time Instinct', 'Tuskin leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(2932, 293, 'Tuskin Cold Resonance', 'Tuskin channels its Cold affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2941, 294, 'Rhiwool''s Deep-Time Instinct', 'Rhiwool leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(2942, 294, 'Rhiwool Cold Resonance', 'Rhiwool channels its Cold affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2951, 295, 'Rheintalensis''s Deep-Time Instinct', 'Rheintalensis leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(2952, 295, 'Rheintalensis Stone Resonance', 'Rheintalensis channels its Stone affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2961, 296, 'Argentowlis''s Highwind Instinct', 'Argentowlis leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(2962, 296, 'Argentowlis Aer Resonance', 'Argentowlis channels its Aer affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2971, 297, 'Hairypterix''s Deep-Time Instinct', 'Hairypterix leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(2972, 297, 'Hairypterix Aer Resonance', 'Hairypterix channels its Aer affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2981, 298, 'Turtworld''s Native Instinct', 'Turtworld leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(2982, 298, 'Turtworld Flora Resonance', 'Turtworld channels its Flora affinity with unusual precision, making matching attacks deal 18% more damage.'),
(2991, 299, 'Gigantopithecus''s Deep-Time Instinct', 'Gigantopithecus leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(2992, 299, 'Gigantopithecus Flora Resonance', 'Gigantopithecus channels its Flora affinity with unusual precision, making matching attacks deal 18% more damage.'),
(3011, 301, 'Moopie''s Native Instinct', 'Moopie leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(3012, 301, 'Moopie Fae Resonance', 'Moopie channels its Fae affinity with unusual precision, making matching attacks deal 18% more damage.'),
(3021, 302, 'Archelon''s Tidewise Instinct', 'Archelon leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(3022, 302, 'Archelon Stone Resonance', 'Archelon channels its Stone affinity with unusual precision, making matching attacks deal 18% more damage.'),
(3031, 303, 'Doggo''s Trailwise Instinct', 'Doggo leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(3032, 303, 'Doggo Vulgaris Resonance', 'Doggo channels its Vulgaris affinity with unusual precision, making matching attacks deal 18% more damage.'),
(3041, 304, 'Fernstalker''s Native Instinct', 'Fernstalker leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(3042, 304, 'Fernstalker Flora Resonance', 'Fernstalker channels its Flora affinity with unusual precision, making matching attacks deal 18% more damage.'),
(3051, 305, 'Sabre''s Deep-Time Instinct', 'Sabre leans into the strongest part of its natural build, raising attack by 12% when it enters battle.'),
(3052, 305, 'Sabre Cold Resonance', 'Sabre channels its Cold affinity with unusual precision, making matching attacks deal 18% more damage.'),
(3061, 306, 'Smilodon''s Deep-Time Instinct', 'Smilodon leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(3062, 306, 'Smilodon Kuro Resonance', 'Smilodon channels its Kuro affinity with unusual precision, making matching attacks deal 18% more damage.'),
(3071, 307, 'Turtfolk''s Native Instinct', 'Turtfolk leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(3072, 307, 'Turtfolk Flora Resonance', 'Turtfolk channels its Flora affinity with unusual precision, making matching attacks deal 18% more damage.'),
(3081, 308, 'Tusktaur''s Deep-Time Instinct', 'Tusktaur leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(3082, 308, 'Tusktaur Floor Resonance', 'Tusktaur channels its Floor affinity with unusual precision, making matching attacks deal 18% more damage.'),
(3091, 309, 'Urchskin''s Tidewise Instinct', 'Urchskin leans into the strongest part of its natural build, raising defense by 12% when it enters battle.'),
(3092, 309, 'Urchskin Malus Resonance', 'Urchskin channels its Malus affinity with unusual precision, making matching attacks deal 18% more damage.'),
(3101, 310, 'Gaitress''s Veilborn Instinct', 'Gaitress leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(3102, 310, 'Gaitress Kampf Resonance', 'Gaitress channels its Kampf affinity with unusual precision, making matching attacks deal 18% more damage.'),
(3111, 311, 'Kasurenijimi''s Native Instinct', 'Kasurenijimi leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(3112, 311, 'Kasurenijimi Ethereal Resonance', 'Kasurenijimi channels its Ethereal affinity with unusual precision, making matching attacks deal 18% more damage.'),
(3121, 312, 'Meloncollie''s Native Instinct', 'Meloncollie leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(3122, 312, 'Meloncollie Fae Resonance', 'Meloncollie channels its Fae affinity with unusual precision, making matching attacks deal 18% more damage.'),
(3131, 313, 'Marmotaur''s Trailwise Instinct', 'Marmotaur leans into the strongest part of its natural build, raising attack by 12% when it enters battle.'),
(3132, 313, 'Marmotaur Fieldcraft', 'Marmotaur turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3141, 314, 'Strigowl''s Highwind Instinct', 'Strigowl leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(3142, 314, 'Strigowl Fieldcraft', 'Strigowl turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3151, 315, 'Skjoldram''s Trailwise Instinct', 'Skjoldram leans into the strongest part of its natural build, raising attack by 12% when it enters battle.'),
(3152, 315, 'Skjoldram Fieldcraft', 'Skjoldram turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3161, 316, 'Pineskrell''s Native Instinct', 'Pineskrell leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(3162, 316, 'Pineskrell Fieldcraft', 'Pineskrell turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3171, 317, 'Boghare''s Trailwise Instinct', 'Boghare leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(3172, 317, 'Boghare Fieldcraft', 'Boghare turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3181, 318, 'Rookmourn''s Native Instinct', 'Rookmourn leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(3182, 318, 'Rookmourn Fieldcraft', 'Rookmourn turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3191, 319, 'Clockhare''s Trailwise Instinct', 'Clockhare leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(3192, 319, 'Clockhare Fieldcraft', 'Clockhare turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3201, 320, 'Stagel''s Native Instinct', 'Stagel leans into the strongest part of its natural build, raising defense by 12% when it enters battle.'),
(3202, 320, 'Stagel Fieldcraft', 'Stagel turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3211, 321, 'Sobolnik''s Native Instinct', 'Sobolnik leans into the strongest part of its natural build, raising attack by 12% when it enters battle.'),
(3212, 321, 'Sobolnik Fieldcraft', 'Sobolnik turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3221, 322, 'Gribboar''s Native Instinct', 'Gribboar leans into the strongest part of its natural build, raising defense by 12% when it enters battle.'),
(3222, 322, 'Gribboar Fieldcraft', 'Gribboar turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3231, 323, 'Pumpkingull''s Highwind Instinct', 'Pumpkingull leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(3232, 323, 'Pumpkingull Fieldcraft', 'Pumpkingull turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3241, 324, 'Snowloper''s Highwind Instinct', 'Snowloper leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(3242, 324, 'Snowloper Fieldcraft', 'Snowloper turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3251, 325, 'Prairhorn''s Native Instinct', 'Prairhorn leans into the strongest part of its natural build, raising attack by 12% when it enters battle.'),
(3252, 325, 'Prairhorn Fieldcraft', 'Prairhorn turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3261, 326, 'Dustbison''s Trailwise Instinct', 'Dustbison leans into the strongest part of its natural build, raising defense by 12% when it enters battle.'),
(3262, 326, 'Dustbison Fieldcraft', 'Dustbison turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3271, 327, 'Silkcoon''s Native Instinct', 'Silkcoon leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(3272, 327, 'Silkcoon Fieldcraft', 'Silkcoon turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3281, 328, 'Bambadger''s Trailwise Instinct', 'Bambadger leans into the strongest part of its natural build, raising defense by 12% when it enters battle.'),
(3282, 328, 'Bambadger Fieldcraft', 'Bambadger turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3291, 329, 'Peaflare''s Highwind Instinct', 'Peaflare leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(3292, 329, 'Peaflare Fieldcraft', 'Peaflare turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3301, 330, 'Palmyr''s Native Instinct', 'Palmyr leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(3302, 330, 'Palmyr Fieldcraft', 'Palmyr turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3311, 331, 'Shibari''s Native Instinct', 'Shibari leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(3312, 331, 'Shibari Fieldcraft', 'Shibari turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3321, 332, 'Momoshika''s Native Instinct', 'Momoshika leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(3322, 332, 'Momoshika Fieldcraft', 'Momoshika turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3331, 333, 'Coatimano''s Native Instinct', 'Coatimano leans into the strongest part of its natural build, raising attack by 12% when it enters battle.'),
(3332, 333, 'Coatimano Fieldcraft', 'Coatimano turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3341, 334, 'Axolume''s Tidewise Instinct', 'Axolume leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(3342, 334, 'Axolume Fieldcraft', 'Axolume turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3351, 335, 'Jaglare''s Native Instinct', 'Jaglare leans into the strongest part of its natural build, raising attack by 12% when it enters battle.'),
(3352, 335, 'Jaglare Fieldcraft', 'Jaglare turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3361, 336, 'Macawtl''s Native Instinct', 'Macawtl leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(3362, 336, 'Macawtl Fieldcraft', 'Macawtl turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3371, 337, 'Ceibler''s Native Instinct', 'Ceibler leans into the strongest part of its natural build, raising attack by 12% when it enters battle.'),
(3372, 337, 'Ceibler Fieldcraft', 'Ceibler turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3381, 338, 'Motmora''s Native Instinct', 'Motmora leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(3382, 338, 'Motmora Fieldcraft', 'Motmora turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3391, 339, 'Dunefennec''s Native Instinct', 'Dunefennec leans into the strongest part of its natural build, raising attack by 12% when it enters battle.'),
(3392, 339, 'Dunefennec Fieldcraft', 'Dunefennec turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3401, 340, 'Caraviper''s Coiled Instinct', 'Caraviper leans into the strongest part of its natural build, raising attack by 12% when it enters battle.'),
(3402, 340, 'Caraviper Fieldcraft', 'Caraviper turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3411, 341, 'Reedbull''s Trailwise Instinct', 'Reedbull leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(3412, 341, 'Reedbull Fieldcraft', 'Reedbull turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3421, 342, 'Ibisking''s Highwind Instinct', 'Ibisking leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(3422, 342, 'Ibisking Fieldcraft', 'Ibisking turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3431, 343, 'Rockhyrax''s Trailwise Instinct', 'Rockhyrax leans into the strongest part of its natural build, raising defense by 12% when it enters battle.'),
(3432, 343, 'Rockhyrax Fieldcraft', 'Rockhyrax turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3441, 344, 'Datebat''s Native Instinct', 'Datebat leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(3442, 344, 'Datebat Fieldcraft', 'Datebat turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3451, 345, 'Ibiset''s Highwind Instinct', 'Ibiset leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(3452, 345, 'Ibiset Fieldcraft', 'Ibiset turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3461, 346, 'Crocora''s Native Instinct', 'Crocora leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(3462, 346, 'Crocora Fieldcraft', 'Crocora turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3471, 347, 'Moonseal''s Trailwise Instinct', 'Moonseal leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(3472, 347, 'Moonseal Fieldcraft', 'Moonseal turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3481, 348, 'Terniq''s Native Instinct', 'Terniq leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(3482, 348, 'Terniq Fieldcraft', 'Terniq turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3491, 349, 'Emberu''s Native Instinct', 'Emberu leans into the strongest part of its natural build, raising attack by 12% when it enters battle.'),
(3492, 349, 'Emberu Fieldcraft', 'Emberu turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3501, 350, 'Wattlefox''s Trailwise Instinct', 'Wattlefox leans into the strongest part of its natural build, raising attack by 12% when it enters battle.'),
(3502, 350, 'Wattlefox Fieldcraft', 'Wattlefox turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3511, 351, 'Cassowrath''s Native Instinct', 'Cassowrath leans into the strongest part of its natural build, raising attack by 12% when it enters battle.'),
(3512, 351, 'Cassowrath Fieldcraft', 'Cassowrath turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3521, 352, 'Gliderune''s Native Instinct', 'Gliderune leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(3522, 352, 'Gliderune Fieldcraft', 'Gliderune turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3531, 353, 'Slothren''s Trailwise Instinct', 'Slothren leans into the strongest part of its natural build, raising defense by 12% when it enters battle.'),
(3532, 353, 'Slothren Fieldcraft', 'Slothren turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3541, 354, 'Riverdillo''s Tidewise Instinct', 'Riverdillo leans into the strongest part of its natural build, raising attack by 12% when it enters battle.'),
(3542, 354, 'Riverdillo Fieldcraft', 'Riverdillo turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3551, 355, 'Vicuñero''s Native Instinct', 'Vicuñero leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(3552, 355, 'Vicuñero Fieldcraft', 'Vicuñero turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3561, 356, 'Condorune''s Highwind Instinct', 'Condorune leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(3562, 356, 'Condorune Fieldcraft', 'Condorune turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3571, 357, 'Dodobold''s Deep-Time Instinct', 'Dodobold leans into the strongest part of its natural build, raising defense by 12% when it enters battle.'),
(3572, 357, 'Dodobold Fieldcraft', 'Dodobold turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3581, 358, 'Squirricerat''s Deep-Time Instinct', 'Squirricerat leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(3582, 358, 'Squirricerat Fieldcraft', 'Squirricerat turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3591, 359, 'Reeffin''s Tidewise Instinct', 'Reeffin leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(3592, 359, 'Reeffin Fieldcraft', 'Reeffin turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3601, 360, 'Mantarrow''s Tidewise Instinct', 'Mantarrow leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(3602, 360, 'Mantarrow Fieldcraft', 'Mantarrow turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3611, 361, 'Nenekea''s Native Instinct', 'Nenekea leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(3612, 361, 'Nenekea Fieldcraft', 'Nenekea turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3621, 362, 'Cocoskink''s Native Instinct', 'Cocoskink leans into the strongest part of its natural build, raising defense by 12% when it enters battle.'),
(3622, 362, 'Cocoskink Fieldcraft', 'Cocoskink turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3631, 363, 'Frondbat''s Native Instinct', 'Frondbat leans into the strongest part of its natural build, raising speed by 12% when it enters battle.'),
(3632, 363, 'Frondbat Fieldcraft', 'Frondbat turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3641, 364, 'Talosling''s Native Instinct', 'Talosling leans into the strongest part of its natural build, raising attack by 12% when it enters battle.'),
(3642, 364, 'Talosling Fieldcraft', 'Talosling turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3651, 365, 'Aegis Boar''s Native Instinct', 'Aegis Boar leans into the strongest part of its natural build, raising defense by 12% when it enters battle.'),
(3652, 365, 'Aegis Boar Fieldcraft', 'Aegis Boar turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3661, 366, 'Tarnhelm''s Native Instinct', 'Tarnhelm leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(3662, 366, 'Tarnhelm Fieldcraft', 'Tarnhelm turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3671, 367, 'Bellmare''s Native Instinct', 'Bellmare leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(3672, 367, 'Bellmare Fieldcraft', 'Bellmare turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3681, 368, 'Reliquary Dove''s Highwind Instinct', 'Reliquary Dove leans into the strongest part of its natural build, raising defense by 12% when it enters battle.'),
(3682, 368, 'Reliquary Dove Fieldcraft', 'Reliquary Dove turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3691, 369, 'Iron Kobold''s Native Instinct', 'Iron Kobold leans into the strongest part of its natural build, raising attack by 12% when it enters battle.'),
(3692, 369, 'Iron Kobold Fieldcraft', 'Iron Kobold turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3701, 370, 'Koschei Chain''s Native Instinct', 'Koschei Chain leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(3702, 370, 'Koschei Chain Fieldcraft', 'Koschei Chain turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3711, 371, 'Tin Jack''s Native Instinct', 'Tin Jack leans into the strongest part of its natural build, raising maximum HP by 12% when it enters battle.'),
(3712, 371, 'Tin Jack Fieldcraft', 'Tin Jack turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3721, 372, 'Peacepipe Bison''s Trailwise Instinct', 'Peacepipe Bison leans into the strongest part of its natural build, raising defense by 12% when it enters battle.'),
(3722, 372, 'Peacepipe Bison Fieldcraft', 'Peacepipe Bison turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3731, 373, 'Bronzejaw Ox''s Native Instinct', 'Bronzejaw Ox leans into the strongest part of its natural build, raising defense by 12% when it enters battle.'),
(3732, 373, 'Bronzejaw Ox Fieldcraft', 'Bronzejaw Ox turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3741, 374, 'Ark Seraph''s Native Instinct', 'Ark Seraph leans into the strongest part of its natural build, raising defense by 12% when it enters battle.'),
(3742, 374, 'Ark Seraph Fieldcraft', 'Ark Seraph turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3751, 375, 'Scarabronze''s Native Instinct', 'Scarabronze leans into the strongest part of its natural build, raising defense by 12% when it enters battle.'),
(3752, 375, 'Scarabronze Fieldcraft', 'Scarabronze turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3761, 376, 'Aurorantler''s Trailwise Instinct', 'Aurorantler leans into the strongest part of its natural build, raising defense by 12% when it enters battle.'),
(3762, 376, 'Aurorantler Fieldcraft', 'Aurorantler turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3771, 377, 'Mirror Crane''s Highwind Instinct', 'Mirror Crane leans into the strongest part of its natural build, raising defense by 12% when it enters battle.'),
(3772, 377, 'Mirror Crane Fieldcraft', 'Mirror Crane turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3781, 378, 'Sword Koi''s Tidewise Instinct', 'Sword Koi leans into the strongest part of its natural build, raising defense by 12% when it enters battle.'),
(3782, 378, 'Sword Koi Fieldcraft', 'Sword Koi turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3791, 379, 'Temple Mantis''s Native Instinct', 'Temple Mantis leans into the strongest part of its natural build, raising defense by 12% when it enters battle.'),
(3792, 379, 'Temple Mantis Fieldcraft', 'Temple Mantis turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3801, 380, 'Obsidian Macuahuitl Hound''s Native Instinct', 'Obsidian Macuahuitl Hound leans into the strongest part of its natural build, raising attack by 12% when it enters battle.'),
(3802, 380, 'Obsidian Macuahuitl Hound Fieldcraft', 'Obsidian Macuahuitl Hound turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3811, 381, 'Turquoise Scale Serpent''s Coiled Instinct', 'Turquoise Scale Serpent leans into the strongest part of its natural build, raising defense by 12% when it enters battle.'),
(3812, 381, 'Turquoise Scale Serpent Fieldcraft', 'Turquoise Scale Serpent turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3821, 382, 'Censer Lion''s Native Instinct', 'Censer Lion leans into the strongest part of its natural build, raising attack by 12% when it enters battle.'),
(3822, 382, 'Censer Lion Fieldcraft', 'Censer Lion turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3831, 383, 'Date Palm Beetle''s Native Instinct', 'Date Palm Beetle leans into the strongest part of its natural build, raising defense by 12% when it enters battle.'),
(3832, 383, 'Date Palm Beetle Fieldcraft', 'Date Palm Beetle turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3841, 384, 'Conch Mail Turtle''s Tidewise Instinct', 'Conch Mail Turtle leans into the strongest part of its natural build, raising defense by 12% when it enters battle.'),
(3842, 384, 'Conch Mail Turtle Fieldcraft', 'Conch Mail Turtle turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3851, 385, 'Ironbeak''s Highwind Instinct', 'Ironbeak leans into the strongest part of its natural build, raising attack by 12% when it enters battle.'),
(3852, 385, 'Ironbeak Fieldcraft', 'Ironbeak turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3861, 386, 'Tin Squirrel''s Native Instinct', 'Tin Squirrel leans into the strongest part of its natural build, raising attack by 12% when it enters battle.'),
(3862, 386, 'Tin Squirrel Fieldcraft', 'Tin Squirrel turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3871, 387, 'Anvil Tortoise''s Native Instinct', 'Anvil Tortoise leans into the strongest part of its natural build, raising defense by 12% when it enters battle.'),
(3872, 387, 'Anvil Tortoise Fieldcraft', 'Anvil Tortoise turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3881, 388, 'Needlehog''s Native Instinct', 'Needlehog leans into the strongest part of its natural build, raising defense by 12% when it enters battle.'),
(3882, 388, 'Needlehog Fieldcraft', 'Needlehog turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3891, 389, 'Mailtoad''s Tidewise Instinct', 'Mailtoad leans into the strongest part of its natural build, raising defense by 12% when it enters battle.'),
(3892, 389, 'Mailtoad Fieldcraft', 'Mailtoad turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3901, 390, 'Sawfin''s Tidewise Instinct', 'Sawfin leans into the strongest part of its natural build, raising defense by 12% when it enters battle.'),
(3902, 390, 'Sawfin Fieldcraft', 'Sawfin turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3911, 391, 'Brasshorn Ram''s Native Instinct', 'Brasshorn Ram leans into the strongest part of its natural build, raising defense by 12% when it enters battle.'),
(3912, 391, 'Brasshorn Ram Fieldcraft', 'Brasshorn Ram turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3921, 392, 'Coin Magpie''s Highwind Instinct', 'Coin Magpie leans into the strongest part of its natural build, raising defense by 12% when it enters battle.'),
(3922, 392, 'Coin Magpie Fieldcraft', 'Coin Magpie turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3931, 393, 'Rust Otter''s Trailwise Instinct', 'Rust Otter leans into the strongest part of its natural build, raising defense by 12% when it enters battle.'),
(3932, 393, 'Rust Otter Fieldcraft', 'Rust Otter turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3941, 394, 'Halberelk''s Trailwise Instinct', 'Halberelk leans into the strongest part of its natural build, raising defense by 12% when it enters battle.'),
(3942, 394, 'Halberelk Fieldcraft', 'Halberelk turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.'),
(3951, 395, 'Mooskuh''s Trailwise Instinct', 'Mooskuh leans into the strongest part of its natural build, raising attack by 12% when it enters battle.'),
(3952, 395, 'Mooskuh Fieldcraft', 'Mooskuh turns practical survival habits into close-quarters technique, making contact attacks deal 15% more damage.')
ON DUPLICATE KEY UPDATE
  species_id = VALUES(species_id),
  ability_name = VALUES(ability_name),
  ability_desc = VALUES(ability_desc);

-- Give existing pets the first template for their species.
UPDATE pet_instances pi
JOIN (
  SELECT species_id, MIN(ability_id) AS ability_id
    FROM pet_has_ability
   GROUP BY species_id
) defaults ON defaults.species_id = pi.species_id
   SET pi.ability_id = defaults.ability_id
 WHERE pi.ability_id IS NULL;
