-- Regional concept item catalog seed.
-- Inserts only into `items`; no explicit item IDs are used.
-- Rarity and category IDs are resolved by name for dump compatibility.

INSERT INTO `items`
  (`item_name`, `item_description`, `base_price`, `rarity_id`, `category_id`, `max_stack`, `tradable`, `replenish`)
SELECT seed.`item_name`, seed.`item_description`, seed.`base_price`, rar.`rarity_id`, cat.`category_id`, seed.`max_stack`, seed.`tradable`, seed.`replenish`
FROM (
  SELECT 'Lotus Sweet' AS `item_name`, 'A soft rose-and-cardamom sweet wrapped in lotus leaf from Padmanagara festival trays.' AS `item_description`, 18.00 AS `base_price`, 'Uncommon' AS `rarity_name`, 'Food' AS `category_name`, 99 AS `max_stack`, 1 AS `tradable`, 45 AS `replenish`
  UNION ALL SELECT 'Sandalwood Charm' AS `item_name`, 'A small carved charm scented with sandalwood and tied with saffron thread.' AS `item_description`, 42.00 AS `base_price`, 'Uncommon' AS `rarity_name`, 'Misc' AS `category_name`, 50 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'River Dye Phial' AS `item_name`, 'A tiny phial of bright river dye used for cloth marks, lamp rites, and market ribbons.' AS `item_description`, 32.00 AS `base_price`, 'Uncommon' AS `rarity_name`, 'Misc' AS `category_name`, 50 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Brass Luck Lamp' AS `item_name`, 'A palm-sized brass lamp polished for shrine corners and lucky counters.' AS `item_description`, 55.00 AS `base_price`, 'Rare' AS `rarity_name`, 'Misc' AS `category_name`, 20 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Caravan Supply Bundle' AS `item_name`, 'A wrapped bundle of travel twine, dried cloth, and spare road tokens for long caravan days.' AS `item_description`, 35.00 AS `base_price`, 'Uncommon' AS `rarity_name`, 'Misc' AS `category_name`, 50 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Brass Moon Lantern' AS `item_name`, 'A crescent-cut brass lantern with blue glass and a steady desert-wind latch.' AS `item_description`, 68.00 AS `base_price`, 'Rare' AS `rarity_name`, 'Misc' AS `category_name`, 20 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Date Honey Cakes' AS `item_name`, 'Dense date cakes glazed with honey and packed for shade tents and river roads.' AS `item_description`, 16.00 AS `base_price`, 'Worth dirt' AS `rarity_name`, 'Food' AS `category_name`, 99 AS `max_stack`, 1 AS `tradable`, 38 AS `replenish`
  UNION ALL SELECT 'Rosemint Cooling Sherbet' AS `item_name`, 'A cold rose-and-mint sherbet that makes hot market stone feel briefly merciful.' AS `item_description`, 22.00 AS `base_price`, 'Uncommon' AS `rarity_name`, 'Food' AS `category_name`, 99 AS `max_stack`, 1 AS `tradable`, 42 AS `replenish`
  UNION ALL SELECT 'Desert Travel Cloak' AS `item_name`, 'A light travel cloak woven to shade shoulders while letting wind pass through.' AS `item_description`, 95.00 AS `base_price`, 'Rare' AS `rarity_name`, 'Wearable' AS `category_name`, 10 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Blue Moon-Tile Trinket' AS `item_name`, 'A glossy tile charm from the moonlit bazaar, usually tied to satchels for safe return.' AS `item_description`, 44.00 AS `base_price`, 'Uncommon' AS `rarity_name`, 'Misc' AS `category_name`, 50 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Obsidian Edge Tool' AS `item_name`, 'A sharp obsidian utility tool wrapped in reed fiber and traded near the causeway gates.' AS `item_description`, 48.00 AS `base_price`, 'Uncommon' AS `rarity_name`, 'Misc' AS `category_name`, 20 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Spiced Cacao Gourd' AS `item_name`, 'A bitter cacao drink spiced with chile and served in a painted gourd.' AS `item_description`, 24.00 AS `base_price`, 'Uncommon' AS `rarity_name`, 'Food' AS `category_name`, 99 AS `max_stack`, 1 AS `tradable`, 45 AS `replenish`
  UNION ALL SELECT 'Quetzal Feather Charm' AS `item_name`, 'A bright feather charm knotted for festival luck and careful steps.' AS `item_description`, 70.00 AS `base_price`, 'Rare' AS `rarity_name`, 'Misc' AS `category_name`, 20 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Maize Festival Cakes' AS `item_name`, 'Warm maize cakes wrapped for plaza days and ballcourt crowds.' AS `item_description`, 15.00 AS `base_price`, 'Worth dirt' AS `rarity_name`, 'Food' AS `category_name`, 99 AS `max_stack`, 1 AS `tradable`, 36 AS `replenish`
  UNION ALL SELECT 'Sunstone Ceremony Token' AS `item_name`, 'A carved sunstone token used as a keepsake after high plaza ceremonies.' AS `item_description`, 120.00 AS `base_price`, 'SR' AS `rarity_name`, 'Misc' AS `category_name`, 10 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Pressed Olive Oil Flask' AS `item_name`, 'A small flask of peppery olive oil from the ridge groves around Shalemdor.' AS `item_description`, 20.00 AS `base_price`, 'Worth dirt' AS `rarity_name`, 'Food' AS `category_name`, 99 AS `max_stack`, 1 AS `tradable`, 20 AS `replenish`
  UNION ALL SELECT 'Cedar Scroll Case' AS `item_name`, 'A smooth cedar case for letters, prayers, and market notes that should stay clean.' AS `item_description`, 40.00 AS `base_price`, 'Uncommon' AS `rarity_name`, 'Misc' AS `category_name`, 20 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Sesame Ring Bread' AS `item_name`, 'A crisp sesame bread ring sold warm near the study-house lanes.' AS `item_description`, 12.00 AS `base_price`, 'Worth dirt' AS `rarity_name`, 'Food' AS `category_name`, 99 AS `max_stack`, 1 AS `tradable`, 30 AS `replenish`
  UNION ALL SELECT 'Little Brass Sabbath Lamp' AS `item_name`, 'A little brass lamp with a careful wick and a polished base.' AS `item_description`, 58.00 AS `base_price`, 'Rare' AS `rarity_name`, 'Misc' AS `category_name`, 20 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Mountain Herb Tea Blend' AS `item_name`, 'A ridge-grown herb tea blend with mint, sage, and a soft honey finish.' AS `item_description`, 16.00 AS `base_price`, 'Worth dirt' AS `rarity_name`, 'Food' AS `category_name`, 99 AS `max_stack`, 1 AS `tradable`, 35 AS `replenish`
  UNION ALL SELECT 'Covenant Knot Charm' AS `item_name`, 'A cord charm tied in a patient knot and given before long journeys.' AS `item_description`, 52.00 AS `base_price`, 'Uncommon' AS `rarity_name`, 'Misc' AS `category_name`, 50 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Canal Crisp Snack Cone' AS `item_name`, 'A paper cone of tiny fried canal crisps with lemon salt.' AS `item_description`, 14.00 AS `base_price`, 'Worth dirt' AS `rarity_name`, 'Food' AS `category_name`, 99 AS `max_stack`, 1 AS `tradable`, 32 AS `replenish`
  UNION ALL SELECT 'Waterproof Reed Satchel' AS `item_name`, 'A waxed reed satchel that keeps ledgers, bait, and snacks out of the canal splash.' AS `item_description`, 65.00 AS `base_price`, 'Uncommon' AS `rarity_name`, 'Wearable' AS `category_name`, 10 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Lockkeeper Fishing Bait' AS `item_name`, 'A pungent bait mix approved by lockkeepers and disliked by everyone else.' AS `item_description`, 9.00 AS `base_price`, 'Worth dirt' AS `rarity_name`, 'Misc' AS `category_name`, 99 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Dike-Warden Charm' AS `item_name`, 'A little blue charm tied to packs before foggy dike walks.' AS `item_description`, 45.00 AS `base_price`, 'Uncommon' AS `rarity_name`, 'Misc' AS `category_name`, 50 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Smoked Canal Fish' AS `item_name`, 'A smoky fish snack packed in paper and best eaten while watching lock gates turn.' AS `item_description`, 28.00 AS `base_price`, 'Uncommon' AS `rarity_name`, 'Food' AS `category_name`, 99 AS `max_stack`, 1 AS `tradable`, 60 AS `replenish`
  UNION ALL SELECT 'Waxed Rain Cape' AS `item_name`, 'A short waxed cape for wet towpaths and sudden lowland rain.' AS `item_description`, 90.00 AS `base_price`, 'Rare' AS `rarity_name`, 'Wearable' AS `category_name`, 10 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Guava River Juice' AS `item_name`, 'A sweet guava juice chilled for Solvine riverwalk afternoons.' AS `item_description`, 12.00 AS `base_price`, 'Worth dirt' AS `rarity_name`, 'Food' AS `category_name`, 99 AS `max_stack`, 1 AS `tradable`, 28 AS `replenish`
  UNION ALL SELECT 'Woven Plaza Bracelet' AS `item_name`, 'A bright woven bracelet from the plaza stalls near the tram line.' AS `item_description`, 32.00 AS `base_price`, 'Uncommon' AS `rarity_name`, 'Wearable' AS `category_name`, 20 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Arepa Plaza Snack' AS `item_name`, 'A warm stuffed arepa wrapped for quick lunches between murals and streetcars.' AS `item_description`, 18.00 AS `base_price`, 'Worth dirt' AS `rarity_name`, 'Food' AS `category_name`, 99 AS `max_stack`, 1 AS `tradable`, 42 AS `replenish`
  UNION ALL SELECT 'River-Map Postcard Set' AS `item_name`, 'A set of glossy postcards showing Solvine bridges, plazas, and river turns.' AS `item_description`, 20.00 AS `base_price`, 'Worth dirt' AS `rarity_name`, 'Misc' AS `category_name`, 50 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Jungle-Flower Perfume' AS `item_name`, 'A tiny bottle of bright floral perfume blended from jungle-edge blossoms.' AS `item_description`, 72.00 AS `base_price`, 'Rare' AS `rarity_name`, 'Misc' AS `category_name`, 20 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Clay Ledger Tablet' AS `item_name`, 'A fired clay tablet ruled for counts, promises, and very serious shopping lists.' AS `item_description`, 38.00 AS `base_price`, 'Uncommon' AS `rarity_name`, 'Book' AS `category_name`, 10 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Reed Scribe Pens' AS `item_name`, 'A bundle of trimmed reed pens ready for ink, dust, and stern accounting.' AS `item_description`, 18.00 AS `base_price`, 'Worth dirt' AS `rarity_name`, 'Misc' AS `category_name`, 99 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Bronze Seal Stamp' AS `item_name`, 'A little bronze seal for stamping clay tags and official-looking notes.' AS `item_description`, 85.00 AS `base_price`, 'Rare' AS `rarity_name`, 'Misc' AS `category_name`, 20 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Date Wine Cup' AS `item_name`, 'A cup of sweet date wine from Ziggurab evening stalls.' AS `item_description`, 24.00 AS `base_price`, 'Uncommon' AS `rarity_name`, 'Food' AS `category_name`, 99 AS `max_stack`, 1 AS `tradable`, 35 AS `replenish`
  UNION ALL SELECT 'Lapis Market Beads' AS `item_name`, 'Small lapis beads strung for market luck and tasteful bribery.' AS `item_description`, 66.00 AS `base_price`, 'Rare' AS `rarity_name`, 'Misc' AS `category_name`, 20 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Lawgiver Token Set' AS `item_name`, 'A set of stamped tokens commemorating famous rulings from the bronze courts.' AS `item_description`, 110.00 AS `base_price`, 'SR' AS `rarity_name`, 'Misc' AS `category_name`, 10 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Rainforest Bitter Herbs' AS `item_name`, 'A packet of bitter canopy herbs used in stews, teas, and stubborn jungle mornings.' AS `item_description`, 14.00 AS `base_price`, 'Worth dirt' AS `rarity_name`, 'Food' AS `category_name`, 99 AS `max_stack`, 1 AS `tradable`, 26 AS `replenish`
  UNION ALL SELECT 'Carved Jade Bead' AS `item_name`, 'A cool green bead carved with stepped temple marks.' AS `item_description`, 64.00 AS `base_price`, 'Rare' AS `rarity_name`, 'Misc' AS `category_name`, 20 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Temple Map Scrap' AS `item_name`, 'A bark-paper scrap showing one staircase, three warnings, and no obvious entrance.' AS `item_description`, 35.00 AS `base_price`, 'Uncommon' AS `rarity_name`, 'Book' AS `category_name`, 10 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Spiced Jungle Cacao' AS `item_name`, 'A thick cacao drink spiced with rainforest pepper and roasted seed.' AS `item_description`, 24.00 AS `base_price`, 'Uncommon' AS `rarity_name`, 'Food' AS `category_name`, 99 AS `max_stack`, 1 AS `tradable`, 44 AS `replenish`
  UNION ALL SELECT 'Braided Vine Rope' AS `item_name`, 'A flexible length of treated vine rope, useful in rain and ruin alike.' AS `item_description`, 28.00 AS `base_price`, 'Worth dirt' AS `rarity_name`, 'Misc' AS `category_name`, 50 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Canopy Survival Kit' AS `item_name`, 'A compact kit with dry tinder, leaf wrap, cord, and a whistle no bird respects.' AS `item_description`, 95.00 AS `base_price`, 'Rare' AS `rarity_name`, 'Misc' AS `category_name`, 10 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Scarab Luck Charm' AS `item_name`, 'A glazed scarab charm pressed into the palm by smiling bazaar sellers.' AS `item_description`, 50.00 AS `base_price`, 'Uncommon' AS `rarity_name`, 'Misc' AS `category_name`, 50 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Linen Sun Wrap' AS `item_name`, 'A light linen wrap for desert glare and riverboat wind.' AS `item_description`, 46.00 AS `base_price`, 'Uncommon' AS `rarity_name`, 'Wearable' AS `category_name`, 10 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Honeyed Fig Cake' AS `item_name`, 'A sticky fig cake glazed with honey and dusted with sesame.' AS `item_description`, 18.00 AS `base_price`, 'Worth dirt' AS `rarity_name`, 'Food' AS `category_name`, 99 AS `max_stack`, 1 AS `tradable`, 40 AS `replenish`
  UNION ALL SELECT 'River Reed Bundle' AS `item_name`, 'A tied bundle of river reeds for baskets, pens, and quick repairs.' AS `item_description`, 12.00 AS `base_price`, 'Worth dirt' AS `rarity_name`, 'Misc' AS `category_name`, 99 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Desert Glass Shard' AS `item_name`, 'A smooth shard of desert glass that catches sunlight like trapped water.' AS `item_description`, 78.00 AS `base_price`, 'Rare' AS `rarity_name`, 'Misc' AS `category_name`, 20 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Painted Canopic Miniature' AS `item_name`, 'A tiny painted jar made for shelves, shrines, and collectors with dramatic taste.' AS `item_description`, 120.00 AS `base_price`, 'SR' AS `rarity_name`, 'Misc' AS `category_name`, 10 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Steamed Peach Bun' AS `item_name`, 'A soft peach-filled bun from a bamboo steamer near Shenhedu tea lanes.' AS `item_description`, 16.00 AS `base_price`, 'Worth dirt' AS `rarity_name`, 'Food' AS `category_name`, 99 AS `max_stack`, 1 AS `tradable`, 38 AS `replenish`
  UNION ALL SELECT 'Jade Comb' AS `item_name`, 'A small jade comb carved with cloud teeth and river polish.' AS `item_description`, 52.00 AS `base_price`, 'Uncommon' AS `rarity_name`, 'Wearable' AS `category_name`, 10 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Dragon-Knot Charm' AS `item_name`, 'A red cord charm knotted into a dragon loop for fortune and stubbornness.' AS `item_description`, 68.00 AS `base_price`, 'Rare' AS `rarity_name`, 'Misc' AS `category_name`, 20 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Calligrapher Ink Brush' AS `item_name`, 'A neat ink brush with a bamboo handle and a tidy temper.' AS `item_description`, 34.00 AS `base_price`, 'Uncommon' AS `rarity_name`, 'Misc' AS `category_name`, 50 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Red Paper Lantern' AS `item_name`, 'A folded red lantern that makes even cramped rooms feel festive.' AS `item_description`, 28.00 AS `base_price`, 'Worth dirt' AS `rarity_name`, 'Misc' AS `category_name`, 50 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Lucky Tea Tin' AS `item_name`, 'A sealed tea tin painted with lotus clouds and a tiny dragon seal.' AS `item_description`, 30.00 AS `base_price`, 'Uncommon' AS `rarity_name`, 'Food' AS `category_name`, 99 AS `max_stack`, 1 AS `tradable`, 30 AS `replenish`
  UNION ALL SELECT 'Smoked Fjord Fish' AS `item_name`, 'A strip of smoky fjord fish packed for cold walks and louder songs.' AS `item_description`, 26.00 AS `base_price`, 'Uncommon' AS `rarity_name`, 'Food' AS `category_name`, 99 AS `max_stack`, 1 AS `tradable`, 58 AS `replenish`
  UNION ALL SELECT 'Wool Snowcloak' AS `item_name`, 'A heavy wool cloak brushed soft enough for snowfall and longhouse benches.' AS `item_description`, 88.00 AS `base_price`, 'Rare' AS `rarity_name`, 'Wearable' AS `category_name`, 10 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Carved Rune Stone' AS `item_name`, 'A small rune stone carved by firelight and sold with a serious nod.' AS `item_description`, 64.00 AS `base_price`, 'Rare' AS `rarity_name`, 'Misc' AS `category_name`, 20 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Aurora Glass Shard' AS `item_name`, 'A green-blue glass shard said to look brighter under northern lights.' AS `item_description`, 96.00 AS `base_price`, 'SR' AS `rarity_name`, 'Misc' AS `category_name`, 10 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Bone Button Set' AS `item_name`, 'A set of pale bone buttons polished smooth for cloaks and packs.' AS `item_description`, 18.00 AS `base_price`, 'Worth dirt' AS `rarity_name`, 'Misc' AS `category_name`, 99 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Hot Berry Mead' AS `item_name`, 'A hot berry mead poured sweet, sharp, and brave against the snow.' AS `item_description`, 24.00 AS `base_price`, 'Uncommon' AS `rarity_name`, 'Food' AS `category_name`, 99 AS `max_stack`, 1 AS `tradable`, 42 AS `replenish`
  UNION ALL SELECT 'Redwind Meat Pie' AS `item_name`, 'A hot meat pie wrapped for road dust, harbor benches, and late carnival queues.' AS `item_description`, 20.00 AS `base_price`, 'Uncommon' AS `rarity_name`, 'Food' AS `category_name`, 99 AS `max_stack`, 1 AS `tradable`, 50 AS `replenish`
  UNION ALL SELECT 'Sun-Bleached Hat' AS `item_name`, 'A practical hat faded by too many red-road afternoons.' AS `item_description`, 45.00 AS `base_price`, 'Uncommon' AS `rarity_name`, 'Wearable' AS `category_name`, 10 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Enamel Road Mug' AS `item_name`, 'A chipped enamel mug that somehow makes every drink taste like travel.' AS `item_description`, 24.00 AS `base_price`, 'Worth dirt' AS `rarity_name`, 'Misc' AS `category_name`, 50 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Outback Trail Map' AS `item_name`, 'A folded trail map with fuel stops, water marks, and one bad joke in the margin.' AS `item_description`, 35.00 AS `base_price`, 'Uncommon' AS `rarity_name`, 'Book' AS `category_name`, 10 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Carnival Ticket Roll' AS `item_name`, 'A roll of bright tickets from the Redwind carnival district.' AS `item_description`, 18.00 AS `base_price`, 'Worth dirt' AS `rarity_name`, 'Misc' AS `category_name`, 99 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Dusty Road Survival Kit' AS `item_name`, 'A compact road kit with bandage cloth, tin cup, salt tabs, and spare courage.' AS `item_description`, 82.00 AS `base_price`, 'Rare' AS `rarity_name`, 'Misc' AS `category_name`, 10 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Black Rye Bread' AS `item_name`, 'A dense black rye loaf that keeps well through cold cart rides.' AS `item_description`, 12.00 AS `base_price`, 'Worth dirt' AS `rarity_name`, 'Food' AS `category_name`, 99 AS `max_stack`, 1 AS `tradable`, 32 AS `replenish`
  UNION ALL SELECT 'Snowberry Preserves' AS `item_name`, 'A jar of tart snowberry preserves thick enough to stand a spoon in.' AS `item_description`, 18.00 AS `base_price`, 'Uncommon' AS `rarity_name`, 'Food' AS `category_name`, 99 AS `max_stack`, 1 AS `tradable`, 38 AS `replenish`
  UNION ALL SELECT 'Lacquer Keepsake Box' AS `item_name`, 'A red lacquer box painted with winter vines and a watchful little gate.' AS `item_description`, 70.00 AS `base_price`, 'Rare' AS `rarity_name`, 'Misc' AS `category_name`, 20 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Fur-Lined Mitts' AS `item_name`, 'Warm mitts lined for frozen mornings and polite tea visits.' AS `item_description`, 78.00 AS `base_price`, 'Rare' AS `rarity_name`, 'Wearable' AS `category_name`, 10 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Painted Winter Egg' AS `item_name`, 'A painted winter egg with tiny gold marks and a very careful shell.' AS `item_description`, 46.00 AS `base_price`, 'Uncommon' AS `rarity_name`, 'Misc' AS `category_name`, 20 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Samovar Tea Brick' AS `item_name`, 'A pressed tea brick for samovars, long tables, and thawing fingers.' AS `item_description`, 24.00 AS `base_price`, 'Uncommon' AS `rarity_name`, 'Food' AS `category_name`, 99 AS `max_stack`, 1 AS `tradable`, 45 AS `replenish`
  UNION ALL SELECT 'Woven Sun Sash' AS `item_name`, 'A bright woven sash patterned after terrace light and mountain paths.' AS `item_description`, 55.00 AS `base_price`, 'Uncommon' AS `rarity_name`, 'Wearable' AS `category_name`, 10 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Quinoa Honey Cake' AS `item_name`, 'A chewy quinoa cake sweetened with honey and wrapped for high-road travel.' AS `item_description`, 18.00 AS `base_price`, 'Worth dirt' AS `rarity_name`, 'Food' AS `category_name`, 99 AS `max_stack`, 1 AS `tradable`, 42 AS `replenish`
  UNION ALL SELECT 'Alpaca Wool Charm' AS `item_name`, 'A soft alpaca-wool charm tied in sun colors.' AS `item_description`, 44.00 AS `base_price`, 'Uncommon' AS `rarity_name`, 'Misc' AS `category_name`, 50 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Gold-Thread Sun Token' AS `item_name`, 'A token stitched with gold thread and carried for bright mountain luck.' AS `item_description`, 118.00 AS `base_price`, 'SR' AS `rarity_name`, 'Misc' AS `category_name`, 10 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Mountain Mint Bundle' AS `item_name`, 'A cool bundle of mountain mint used in tea, stew, and breath-saving altitude tricks.' AS `item_description`, 14.00 AS `base_price`, 'Worth dirt' AS `rarity_name`, 'Food' AS `category_name`, 99 AS `max_stack`, 1 AS `tradable`, 28 AS `replenish`
  UNION ALL SELECT 'Seal-Oil Lamp' AS `item_name`, 'A compact lamp made for cold rooms, careful hands, and steady blue flame.' AS `item_description`, 54.00 AS `base_price`, 'Uncommon' AS `rarity_name`, 'Misc' AS `category_name`, 20 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Carved Bone Charm' AS `item_name`, 'A small bone charm carved with tide marks and quiet patience.' AS `item_description`, 42.00 AS `base_price`, 'Uncommon' AS `rarity_name`, 'Misc' AS `category_name`, 50 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Snow Goggles' AS `item_name`, 'Slit snow goggles for white glare and long ice roads.' AS `item_description`, 80.00 AS `base_price`, 'Rare' AS `rarity_name`, 'Wearable' AS `category_name`, 10 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Dried Arctic Fish' AS `item_name`, 'A dry, salty fish strip that lasts longer than most plans.' AS `item_description`, 26.00 AS `base_price`, 'Uncommon' AS `rarity_name`, 'Food' AS `category_name`, 99 AS `max_stack`, 1 AS `tradable`, 56 AS `replenish`
  UNION ALL SELECT 'Fur Warm Boots' AS `item_name`, 'Warm boots stitched for snow crust, dock boards, and serious cold.' AS `item_description`, 105.00 AS `base_price`, 'Rare' AS `rarity_name`, 'Wearable' AS `category_name`, 10 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Aurora Bead String' AS `item_name`, 'A string of beads in pale green, blue, and violet like winter sky fire.' AS `item_description`, 68.00 AS `base_price`, 'Rare' AS `rarity_name`, 'Misc' AS `category_name`, 20 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Prairie Beadwork Strip' AS `item_name`, 'A careful strip of beadwork made for belts, bags, and gifted keepsakes.' AS `item_description`, 48.00 AS `base_price`, 'Uncommon' AS `rarity_name`, 'Wearable' AS `category_name`, 20 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Blue Corn Cake' AS `item_name`, 'A soft blue-corn cake cooked for council days and trail mornings.' AS `item_description`, 15.00 AS `base_price`, 'Worth dirt' AS `rarity_name`, 'Food' AS `category_name`, 99 AS `max_stack`, 1 AS `tradable`, 36 AS `replenish`
  UNION ALL SELECT 'Woven Seed Pouch' AS `item_name`, 'A woven pouch for seed, beads, and small things that should not spill.' AS `item_description`, 28.00 AS `base_price`, 'Worth dirt' AS `rarity_name`, 'Misc' AS `category_name`, 50 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Prairie Sage Bundle' AS `item_name`, 'A fragrant sage bundle kept dry for cooking smoke and clean-room rituals.' AS `item_description`, 16.00 AS `base_price`, 'Worth dirt' AS `rarity_name`, 'Food' AS `category_name`, 99 AS `max_stack`, 1 AS `tradable`, 18 AS `replenish`
  UNION ALL SELECT 'Story Circle Token' AS `item_name`, 'A carved token passed around when a story needs a careful listener.' AS `item_description`, 60.00 AS `base_price`, 'Rare' AS `rarity_name`, 'Misc' AS `category_name`, 20 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Trail Blessing Charm' AS `item_name`, 'A little charm knotted for safe paths, shared fires, and steady weather.' AS `item_description`, 44.00 AS `base_price`, 'Uncommon' AS `rarity_name`, 'Misc' AS `category_name`, 50 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Mixed Spice Packet' AS `item_name`, 'A small packet of bright dock spices for rice, fish, and almost anything else.' AS `item_description`, 13.00 AS `base_price`, 'Worth dirt' AS `rarity_name`, 'Food' AS `category_name`, 99 AS `max_stack`, 1 AS `tradable`, 18 AS `replenish`
  UNION ALL SELECT 'Reef Pearl' AS `item_name`, 'A small reef pearl with a warm sheen and a suspiciously persuasive seller.' AS `item_description`, 85.00 AS `base_price`, 'Rare' AS `rarity_name`, 'Misc' AS `category_name`, 20 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Banana Leaf Boat Snack' AS `item_name`, 'A warm snack wrapped in banana leaf and tied for eating near the quay.' AS `item_description`, 20.00 AS `base_price`, 'Worth dirt' AS `rarity_name`, 'Food' AS `category_name`, 99 AS `max_stack`, 1 AS `tradable`, 45 AS `replenish`
  UNION ALL SELECT 'Shell Bracelet' AS `item_name`, 'A bracelet of small shells polished by reef sand and market fingers.' AS `item_description`, 38.00 AS `base_price`, 'Uncommon' AS `rarity_name`, 'Wearable' AS `category_name`, 20 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Trade Flag Pennant' AS `item_name`, 'A little trade flag pennant in harbor colors.' AS `item_description`, 30.00 AS `base_price`, 'Worth dirt' AS `rarity_name`, 'Misc' AS `category_name`, 50 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Tropical Tonic Bottle' AS `item_name`, 'A bright tonic of citrus, ginger, and spice-route herbs.' AS `item_description`, 34.00 AS `base_price`, 'Uncommon' AS `rarity_name`, 'Potion' AS `category_name`, 20 AS `max_stack`, 1 AS `tradable`, 45 AS `replenish`
  UNION ALL SELECT 'Corner Mart Coffee' AS `item_name`, 'A hot coffee in a paper cup, brewed fast enough for commuter timing.' AS `item_description`, 9.00 AS `base_price`, 'Worth dirt' AS `rarity_name`, 'Food' AS `category_name`, 99 AS `max_stack`, 1 AS `tradable`, 25 AS `replenish`
  UNION ALL SELECT 'Commuter Snack Pack' AS `item_name`, 'A crinkly pack of salty, sweet, and questionably nutritious snacks.' AS `item_description`, 14.00 AS `base_price`, 'Worth dirt' AS `rarity_name`, 'Food' AS `category_name`, 99 AS `max_stack`, 1 AS `tradable`, 34 AS `replenish`
  UNION ALL SELECT 'Neon Keychain' AS `item_name`, 'A cheap neon keychain shaped like the Meridian Arc skyline.' AS `item_description`, 18.00 AS `base_price`, 'Worth dirt' AS `rarity_name`, 'Misc' AS `category_name`, 99 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'City Sticker Sheet' AS `item_name`, 'A sticker sheet of bridges, trains, diner signs, and tiny skyline stars.' AS `item_description`, 10.00 AS `base_price`, 'Worth dirt' AS `rarity_name`, 'Misc' AS `category_name`, 99 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Transit Day Card' AS `item_name`, 'A disposable day card for buses, trains, ferries, and one wrong transfer.' AS `item_description`, 28.00 AS `base_price`, 'Uncommon' AS `rarity_name`, 'Misc' AS `category_name`, 50 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Cheap Sunglasses' AS `item_name`, 'Plastic sunglasses that beat squinting and look better than their price.' AS `item_description`, 22.00 AS `base_price`, 'Worth dirt' AS `rarity_name`, 'Wearable' AS `category_name`, 20 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Marigold Garland' AS `item_name`, 'A bright marigold garland from the canal market, fresh enough to perfume a whole bag.' AS `item_description`, 24.00 AS `base_price`, 'Worth dirt' AS `rarity_name`, 'Wearable' AS `category_name`, 20 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Lucha Mask' AS `item_name`, 'A colorful wrestling mask from the arena stalls, sold with a dramatic stare.' AS `item_description`, 64.00 AS `base_price`, 'Rare' AS `rarity_name`, 'Wearable' AS `category_name`, 10 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Canal Corn Snack' AS `item_name`, 'A canal-side corn snack with lime, chile, and enough cheese to start a debate.' AS `item_description`, 16.00 AS `base_price`, 'Worth dirt' AS `rarity_name`, 'Food' AS `category_name`, 99 AS `max_stack`, 1 AS `tradable`, 38 AS `replenish`
  UNION ALL SELECT 'Spiced Hot Chocolate' AS `item_name`, 'A rich hot chocolate with cinnamon, chile, and plaza-night warmth.' AS `item_description`, 20.00 AS `base_price`, 'Uncommon' AS `rarity_name`, 'Food' AS `category_name`, 99 AS `max_stack`, 1 AS `tradable`, 40 AS `replenish`
  UNION ALL SELECT 'Painted Clay Cup' AS `item_name`, 'A painted clay cup from the covered market, slightly uneven and very charming.' AS `item_description`, 30.00 AS `base_price`, 'Uncommon' AS `rarity_name`, 'Misc' AS `category_name`, 50 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'City Luck Charm' AS `item_name`, 'A tiny city charm painted with flowers, canal waves, and a watchful sun.' AS `item_description`, 40.00 AS `base_price`, 'Uncommon' AS `rarity_name`, 'Misc' AS `category_name`, 50 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Lemon Myrtle Bush Tea' AS `item_name`, 'A bright bush tea with lemon myrtle and a clean, cooling finish.' AS `item_description`, 16.00 AS `base_price`, 'Worth dirt' AS `rarity_name`, 'Food' AS `category_name`, 99 AS `max_stack`, 1 AS `tradable`, 34 AS `replenish`
  UNION ALL SELECT 'Handwoven Reed Basket' AS `item_name`, 'A handwoven basket made for carrying small goods without rushing the maker.' AS `item_description`, 55.00 AS `base_price`, 'Uncommon' AS `rarity_name`, 'Misc' AS `category_name`, 20 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'River-Safe Gear Kit' AS `item_name`, 'A practical kit with water notes, cord, and a reminder to listen to rangers first.' AS `item_description`, 90.00 AS `base_price`, 'Rare' AS `rarity_name`, 'Misc' AS `category_name`, 10 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Painted Meeting Token' AS `item_name`, 'A painted token from the meeting ground, made as a keepsake rather than a shortcut.' AS `item_description`, 48.00 AS `base_price`, 'Uncommon' AS `rarity_name`, 'Misc' AS `category_name`, 50 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Ranger Track Map' AS `item_name`, 'A respectful track map with tide notes, closures, and marked paths.' AS `item_description`, 36.00 AS `base_price`, 'Uncommon' AS `rarity_name`, 'Book' AS `category_name`, 10 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
  UNION ALL SELECT 'Maker Goods Bundle' AS `item_name`, 'A small bundle of maker goods bought direct: fair, useful, and clearly labeled.' AS `item_description`, 75.00 AS `base_price`, 'Rare' AS `rarity_name`, 'Misc' AS `category_name`, 10 AS `max_stack`, 1 AS `tradable`, 1 AS `replenish`
) seed
JOIN `item_rarities` rar ON rar.`rarity_name` = seed.`rarity_name`
JOIN `item_categories` cat ON cat.`category_name` = seed.`category_name`
WHERE NOT EXISTS (
  SELECT 1
  FROM `items` i
  WHERE i.`item_name` = seed.`item_name`
);
